# Creating and Ingesting Data into the DB via Python

This notebook shows the way one can access data from the database using sqlalchemy 
- Write to the database
- Create tables 

All using sqlalchemy

In [1]:
import pandas as pd
from sqlalchemy import create_engine, types
from sqlalchemy import text # to be able to pass string

# 1. Create a database connection 🔌🏦

### A ``connection string`` for postgresql could look like this:

```python
url = '<dialect>://<user>:<password>@<host>:<port>/<database>'
```

In [2]:
# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']

In [3]:
# Now building the URL with the values from the .env file

url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# without specifying the schema default connection is to the schema `public`
# url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

In [4]:
pg_db

'nf_180825'

In [5]:
engine = create_engine(url, echo=False)

In [6]:
engine.url # password is hidden

postgresql://jingwang:***@data-analytics-course-2.c8g8r1deus2v.eu-central-1.rds.amazonaws.com:5432/nf_180825

In [19]:
my_schema = 's_jingwang' # update it to your schema

with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {my_schema};'))

2025-10-27 21:28:43,142 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-10-27 21:28:43,144 INFO sqlalchemy.engine.Engine SET search_path TO s_jingwang;
2025-10-27 21:28:43,145 INFO sqlalchemy.engine.Engine [cached since 29.89s ago] {}
2025-10-27 21:28:43,199 INFO sqlalchemy.engine.Engine COMMIT

# 2. Run SQL statements 🔧✏️📚
With an `engine` defined we can now send plain SQL statements to the server.
***PREVIEW: Simple reading example***

In [17]:
with engine.begin() as conn: # Done with echo=False
    result = conn.execute(text(f'''
                               SELECT * FROM students; 
                                '''))
    data = result.all()

### Let's create a dataframe out of that
df = pd.DataFrame(data, columns=['student_id', 'first_name', 'email']) 
df

   student_id first_name             email
0           1       Anna    anna@gmail.com
1           2     Joseph  joseph@gmail.com
2           3     Scally  scally@gmail.com
3           4       Liam    liam@gmail.com
4           5       Elif    elif@gmail.com

### 🔧 2.1 Create a new table ``seminars``:

Connecting to a database works like opening a connection to a local file.  

The connection stays open within the `with` block and will be closed afterwards. 

`conn.execute` sends the SQL statement to the server and optionally 
returns a result set.

In [14]:
with engine.begin() as conn:
    conn.execute(text(f"""
        DROP TABLE IF EXISTS seminars;
        CREATE TABLE seminars (
            seminar_name VARCHAR PRIMARY KEY,
            seminar_start DATE,
            seminar_end DATE,
            instructor_id VARCHAR
        );    
    """))

>#### Check your Schema in DBeaver for changes

### ✏️2.2 Insert some data:

Within a connection context we can send one or several statements at once:

In [18]:
# let's switch the logging on. because the engine is getting renewed we need to specify the schema again.
engine = create_engine(url, echo=True)

my_schema = 's_jingwang' # change it to your schema name

with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {my_schema};'))

2025-10-27 21:28:13,075 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-10-27 21:28:13,078 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-27 21:28:13,139 INFO sqlalchemy.engine.Engine select current_schema()
2025-10-27 21:28:13,140 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-27 21:28:13,193 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-10-27 21:28:13,193 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-27 21:28:13,248 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-10-27 21:28:13,250 INFO sqlalchemy.engine.Engine SET search_path TO s_jingwang;
2025-10-27 21:28:13,250 INFO sqlalchemy.engine.Engine [generated in 0.00054s] {}
2025-10-27 21:28:13,309 INFO sqlalchemy.engine.Engine COMMIT

In [20]:
with engine.begin() as conn: # Done with echo=True
    conn.execute(text("INSERT INTO seminars VALUES ('art', '2024-03-23', '2024-05-23', 't23')"))
    conn.execute(text("INSERT INTO seminars VALUES ('ethics', '2024-03-17', '2024-04-05', 't12')"))
    conn.execute(text("INSERT INTO seminars VALUES ('engineering', '2024-10-09', '2024-11-08', 't45')"))
    conn.execute(text("INSERT INTO seminars VALUES ('politics', '2024-07-11', '2024-08-31', 't37')"))
    conn.execute(text("INSERT INTO seminars VALUES ('python', '2024-08-01', '2024-12-01', 't08')"))

2025-10-27 21:29:07,073 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-10-27 21:29:07,076 INFO sqlalchemy.engine.Engine INSERT INTO seminars VALUES ('art', '2024-03-23', '2024-05-23', 't23')
2025-10-27 21:29:07,076 INFO sqlalchemy.engine.Engine [generated in 0.00066s] {}
2025-10-27 21:29:07,135 INFO sqlalchemy.engine.Engine INSERT INTO seminars VALUES ('ethics', '2024-03-17', '2024-04-05', 't12')
2025-10-27 21:29:07,135 INFO sqlalchemy.engine.Engine [generated in 0.00059s] {}
2025-10-27 21:29:07,165 INFO sqlalchemy.engine.Engine INSERT INTO seminars VALUES ('engineering', '2024-10-09', '2024-11-08', 't45')
2025-10-27 21:29:07,165 INFO sqlalchemy.engine.Engine [generated in 0.00040s] {}
2025-10-27 21:29:07,195 INFO sqlalchemy.engine.Engine INSERT INTO seminars VALUES ('politics', '2024-07-11', '2024-08-31', 't37')
2025-10-27 21:29:07,196 INFO sqlalchemy.engine.Engine [generated in 0.00135s] {}
2025-10-27 21:29:07,224 INFO sqlalchemy.engine.Engine INSERT INTO seminars VALUES ('python', '2024-08-01', '2024-12-01', 't08')
2025-10-27 21:29:07,225 INFO sqlalchemy.engine.Engine [generated in 0.00039s] {}
2025-10-27 21:29:07,255 INFO sqlalchemy.engine.Engine COMMIT

### OR

In [ ]:
with engine.begin() as conn: # Done with echo=True
    conn.execute(text('''
                        TRUNCATE TABLE seminars; -- we need to empty the table due to Primary Key constraint
                        INSERT INTO seminars VALUES ('art', '2024-03-23', '2024-05-23', 't23');
                        INSERT INTO seminars VALUES ('ethics', '2024-03-17', '2024-04-05', 't12');
                        INSERT INTO seminars VALUES ('engineering', '2024-10-09', '2024-11-08', 't45');
                        INSERT INTO seminars VALUES ('politics', '2024-07-11', '2024-08-31', 't37');
                        INSERT INTO seminars VALUES ('python', '2024-08-01', '2024-12-01', 't08');                      
                    '''))

#### Side Bar: Transactions

>
>**engine.begin():**  
The statements withing the `with` block are executed as a *transaction*. A transaction bundles several SQL statements into a single atomic unit (all 'conn.execute()' are treated as a single transaction). If any query fails (e.g., due to an error or constraint violation), the entire transaction is rolled back, and none of the queries take effect. **It is all or nothing.**
>
This is called *atomicity* and is one of the key features of a relational database. To send the statements without transaction use `engine.connect()` instead of `engine.begin()`.
>
>**engine.connect():**  
Each `conn.execute()` line is treated as a separate transaction. If a query fails, it doesn’t affect other queries executed earlier. You need to explicitly handle the transactions (commit or rollback) for each individual query.

### 📚 3.3 Reading data

We can also run `SELECT` statements and store the result in a variable `result`  

The method `result.all()` reads all rows from the result object and returns a list
of tuples:

In [21]:
# let's read the newly created table

with engine.begin() as conn: # Done with echo=True
    result = conn.execute(text("SELECT * FROM seminars;"))
    seminars_data = result.all()

print(seminars_data)
#returns a list of tuples, each tuple being a row in the table

2025-10-27 21:33:31,473 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-10-27 21:33:31,476 INFO sqlalchemy.engine.Engine SELECT * FROM seminars;
2025-10-27 21:33:31,477 INFO sqlalchemy.engine.Engine [generated in 0.00102s] {}
2025-10-27 21:33:31,559 INFO sqlalchemy.engine.Engine COMMIT
[('art', datetime.date(2024, 3, 23), datetime.date(2024, 5, 23), 't23'), ('ethics', datetime.date(2024, 3, 17), datetime.date(2024, 4, 5), 't12'), ('engineering', datetime.date(2024, 10, 9), datetime.date(2024, 11, 8), 't45'), ('politics', datetime.date(2024, 7, 11), datetime.date(2024, 8, 31), 't37'), ('python', datetime.date(2024, 8, 1), datetime.date(2024, 12, 1), 't08')]

The list of rows can then be converted into a `pd.DataFrame`:

In [27]:
df = pd.DataFrame(seminars_data, columns=['seminar_name', 'seminar_start', 'seminar_end', 'instructor_id'])
#df.set_index('seminar_name')
df

  seminar_name seminar_start seminar_end instructor_id
0          art    2024-03-23  2024-05-23           t23
1       ethics    2024-03-17  2024-04-05           t12
2  engineering    2024-10-09  2024-11-08           t45
3     politics    2024-07-11  2024-08-31           t37
4       python    2024-08-01  2024-12-01           t08

In [29]:
# let's switch the logging off again. .
engine = create_engine(url, echo=False)

my_schema = 's_jingwang'

with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {my_schema};'))

>NOTE: if you don't have `students`, `enrolments` and `exam_tables` anymore. Please find the sql file `academy_tables.sql` in the lecture folder and run the queries in your schema in DBeaver.

# 4. Reading 📚 and Writing ✏️ tables with pandas 🐼

In [30]:
# reading students table into a dataframe

students = pd.read_sql(sql=text('SELECT * FROM students;'), con=engine)
# enrolments = pd.read_sql(sql=text('SELECT * FROM enrolments;'), con=engine.connect())
students

   student_id student_name             email
0           1         Anna    anna@gmail.com
1           2       Joseph  joseph@gmail.com
2           3       Scally  scally@gmail.com
3           4         Liam    liam@gmail.com
4           5         Elif    elif@gmail.com

In [31]:
# reading exam_scores table into a dataframe

exam_scores = pd.read_sql(sql=text('SELECT * FROM exam_grades;'), con=engine)
exam_scores

  seminar_name  student_id  grade
0          art           5    1.3
1       ethics           2    1.0
2  engineering           4    2.1
3     politics           1    3.5
4          art           3    2.3

In [33]:
# let's merge students and exam_scores on "student_id"

student_scores = pd.merge(students, exam_scores, on=('student_id'), how='inner')
student_scores

   student_id student_name             email seminar_name  grade
0           1         Anna    anna@gmail.com     politics    3.5
1           2       Joseph  joseph@gmail.com       ethics    1.0
2           3       Scally  scally@gmail.com          art    2.3
3           4         Liam    liam@gmail.com  engineering    2.1
4           5         Elif    elif@gmail.com          art    1.3

In [34]:
# optionally adding student_id as index 
student_scores.set_index('student_id', inplace=True)
student_scores

           student_name             email seminar_name  grade
student_id
1                  Anna    anna@gmail.com     politics    3.5
2                Joseph  joseph@gmail.com       ethics    1.0
3                Scally  scally@gmail.com          art    2.3
4                  Liam    liam@gmail.com  engineering    2.1
5                  Elif    elif@gmail.com          art    1.3

In [43]:
#### With a one-liner, you can also import new data into the database:
#student_scores.to_sql('student_scores', engine, if_exists='append', index=True)

In [41]:
# Drop the table manually if it exists
#with engine.connect() as connection:
    #connection.execute(text("DROP TABLE IF EXISTS student_scores"))

In [42]:
student_scores.to_sql('student_scores', engine, if_exists='replace',index=True)

5

In the background, this creates a new table with column definitions and inserts the data into the table.   
>**Note:** Check the data type of the columns. For example the last column `grade` is currently a **float8**

To get more control over the data types of the table 
you can run a `CREATE TABLE` statement before inserting data with pandas:

In [44]:
with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS student_grades;"))
    conn.execute(text("""
                        CREATE TABLE student_grades (
                                                    student_id INT,
                                                    student_name VARCHAR,
                                                    email VARCHAR,
                                                    seminar_name VARCHAR,
                                                    grade NUMERIC
                                                    );
                        """))
    student_scores.to_sql('student_grades', conn, if_exists='append', index='student_id') 
    # here we use the variable `conn` as this line is still indented under the `with engine.begin() as conn`statement and is using the open connection to db.

> check now in DBeaver the data type of the columns.
or we can define a **dictionary** with the data types and pass it to the pandas `.to_sql()` method. In this case would use the `engine` directly as we are not opening a connection within a `WITH` statement.