In [49]:
# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']
pg_api_key  =config['X-RapidAPI-Key']

In [14]:
import pprint

In [15]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/monthly"

querystring = {"station":"10637","start":"2020-01-01","end":"2020-12-31"}

headers = {
	"x-rapidapi-key": pg_api_key, #use the value of env file
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

result = response.json()

pprint.pprint(result)

{'data': [{'date': '2020-01-01 00:00:00',
           'prcp': 36.9,
           'pres': 1025.2,
           'tavg': 4.1,
           'tmax': 7.0,
           'tmin': 1.0,
           'tsun': 3306,
           'wspd': None},
          {'date': '2020-02-01 00:00:00',
           'prcp': 78.9,
           'pres': 1016.1,
           'tavg': 6.5,
           'tmax': 10.2,
           'tmin': 2.4,
           'tsun': 4608,
           'wspd': None},
          {'date': '2020-03-01 00:00:00',
           'prcp': 47.9,
           'pres': 1018.1,
           'tavg': 7.4,
           'tmax': 12.3,
           'tmin': 2.3,
           'tsun': 11244,
           'wspd': None},
          {'date': '2020-04-01 00:00:00',
           'prcp': 21.8,
           'pres': 1017.5,
           'tavg': 12.9,
           'tmax': 20.3,
           'tmin': 5.1,
           'tsun': 18402,
           'wspd': None},
          {'date': '2020-05-01 00:00:00',
           'prcp': 31.1,
           'pres': 1020.3,
           'tavg': 14.2,
           'tmax': 20.2,
           'tmin': 7.4,
           'tsun': 18240,
           'wspd': None},
          {'date': '2020-06-01 00:00:00',
           'prcp': 44.4,
           'pres': 1013.3,
           'tavg': 18.6,
           'tmax': 24.2,
           'tmin': 12.6,
           'tsun': 13260,
           'wspd': None},
          {'date': '2020-07-01 00:00:00',
           'prcp': 15.5,
           'pres': 1016.6,
           'tavg': 20.6,
           'tmax': 26.8,
           'tmin': 13.9,
           'tsun': 16074,
           'wspd': None},
          {'date': '2020-08-01 00:00:00',
           'prcp': 76.0,
           'pres': 1013.6,
           'tavg': 22.0,
           'tmax': 28.1,
           'tmin': 16.2,
           'tsun': 12552,
           'wspd': None},
          {'date': '2020-09-01 00:00:00',
           'prcp': 32.0,
           'pres': 1016.7,
           'tavg': 17.0,
           'tmax': 23.5,
           'tmin': 10.9,
           'tsun': 13674,
           'wspd': None},
          {'date': '2020-10-01 00:00:00',
           'prcp': 60.7,
           'pres': 1013.1,
           'tavg': 11.3,
           'tmax': 14.8,
           'tmin': 7.3,
           'tsun': 3648,
           'wspd': None},
          {'date': '2020-11-01 00:00:00',
           'prcp': 16.2,
           'pres': 1025.2,
           'tavg': 6.6,
           'tmax': 10.1,
           'tmin': 3.0,
           'tsun': 5490,
           'wspd': None},
          {'date': '2020-12-01 00:00:00',
           'prcp': 81.1,
           'pres': 1009.0,
           'tavg': 4.3,
           'tmax': 6.5,
           'tmin': 1.8,
           'tsun': 1176,
           'wspd': None}],
 'meta': {'generated': '2025-10-30 07:14:22'}}

In [16]:
print(result)

{'meta': {'generated': '2025-10-30 07:14:22'}, 'data': [{'date': '2020-01-01 00:00:00', 'tavg': 4.1, 'tmin': 1.0, 'tmax': 7.0, 'prcp': 36.9, 'wspd': None, 'pres': 1025.2, 'tsun': 3306}, {'date': '2020-02-01 00:00:00', 'tavg': 6.5, 'tmin': 2.4, 'tmax': 10.2, 'prcp': 78.9, 'wspd': None, 'pres': 1016.1, 'tsun': 4608}, {'date': '2020-03-01 00:00:00', 'tavg': 7.4, 'tmin': 2.3, 'tmax': 12.3, 'prcp': 47.9, 'wspd': None, 'pres': 1018.1, 'tsun': 11244}, {'date': '2020-04-01 00:00:00', 'tavg': 12.9, 'tmin': 5.1, 'tmax': 20.3, 'prcp': 21.8, 'wspd': None, 'pres': 1017.5, 'tsun': 18402}, {'date': '2020-05-01 00:00:00', 'tavg': 14.2, 'tmin': 7.4, 'tmax': 20.2, 'prcp': 31.1, 'wspd': None, 'pres': 1020.3, 'tsun': 18240}, {'date': '2020-06-01 00:00:00', 'tavg': 18.6, 'tmin': 12.6, 'tmax': 24.2, 'prcp': 44.4, 'wspd': None, 'pres': 1013.3, 'tsun': 13260}, {'date': '2020-07-01 00:00:00', 'tavg': 20.6, 'tmin': 13.9, 'tmax': 26.8, 'prcp': 15.5, 'wspd': None, 'pres': 1016.6, 'tsun': 16074}, {'date': '2020-08-01 00:00:00', 'tavg': 22.0, 'tmin': 16.2, 'tmax': 28.1, 'prcp': 76.0, 'wspd': None, 'pres': 1013.6, 'tsun': 12552}, {'date': '2020-09-01 00:00:00', 'tavg': 17.0, 'tmin': 10.9, 'tmax': 23.5, 'prcp': 32.0, 'wspd': None, 'pres': 1016.7, 'tsun': 13674}, {'date': '2020-10-01 00:00:00', 'tavg': 11.3, 'tmin': 7.3, 'tmax': 14.8, 'prcp': 60.7, 'wspd': None, 'pres': 1013.1, 'tsun': 3648}, {'date': '2020-11-01 00:00:00', 'tavg': 6.6, 'tmin': 3.0, 'tmax': 10.1, 'prcp': 16.2, 'wspd': None, 'pres': 1025.2, 'tsun': 5490}, {'date': '2020-12-01 00:00:00', 'tavg': 4.3, 'tmin': 1.8, 'tmax': 6.5, 'prcp': 81.1, 'wspd': None, 'pres': 1009.0, 'tsun': 1176}]}

In [17]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [18]:
# inspect the data: string, dictionary, etc.
# json normalization

## api call and response

In [19]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/monthly"

querystring = {"station":"10488","start":"2020-01-01","end":"2020-12-31"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

result=response.json()

pprint.pprint(result)

{'data': [{'date': '2020-01-01 00:00:00',
           'prcp': 17.6,
           'pres': 1023.7,
           'tavg': 3.1,
           'tmax': 6.1,
           'tmin': 0.0,
           'tsun': 3870,
           'wspd': None},
          {'date': '2020-02-01 00:00:00',
           'prcp': 88.9,
           'pres': 1013.1,
           'tavg': 5.6,
           'tmax': 8.8,
           'tmin': 2.4,
           'tsun': 3252,
           'wspd': None},
          {'date': '2020-03-01 00:00:00',
           'prcp': 25.5,
           'pres': 1018.6,
           'tavg': 5.3,
           'tmax': 9.6,
           'tmin': 0.8,
           'tsun': 10626,
           'wspd': None},
          {'date': '2020-04-01 00:00:00',
           'prcp': 1.9,
           'pres': 1018.4,
           'tavg': 11.0,
           'tmax': 16.7,
           'tmin': 4.4,
           'tsun': 17814,
           'wspd': None},
          {'date': '2020-05-01 00:00:00',
           'prcp': 42.7,
           'pres': 1019.6,
           'tavg': 12.1,
           'tmax': 17.5,
           'tmin': 6.7,
           'tsun': 12852,
           'wspd': None},
          {'date': '2020-06-01 00:00:00',
           'prcp': 40.5,
           'pres': 1012.5,
           'tavg': 18.1,
           'tmax': 23.4,
           'tmin': 13.2,
           'tsun': 11862,
           'wspd': None},
          {'date': '2020-07-01 00:00:00',
           'prcp': 17.0,
           'pres': 1015.9,
           'tavg': 19.3,
           'tmax': 25.2,
           'tmin': 13.4,
           'tsun': 15300,
           'wspd': None},
          {'date': '2020-08-01 00:00:00',
           'prcp': 119.4,
           'pres': 1013.6,
           'tavg': 21.2,
           'tmax': 26.7,
           'tmin': 15.7,
           'tsun': 13734,
           'wspd': None},
          {'date': '2020-09-01 00:00:00',
           'prcp': 49.7,
           'pres': 1016.9,
           'tavg': 16.0,
           'tmax': 21.4,
           'tmin': 10.0,
           'tsun': 13566,
           'wspd': None},
          {'date': '2020-10-01 00:00:00',
           'prcp': 105.8,
           'pres': 1012.6,
           'tavg': 10.9,
           'tmax': 14.0,
           'tmin': 7.9,
           'tsun': 4980,
           'wspd': None},
          {'date': '2020-11-01 00:00:00',
           'prcp': 6.1,
           'pres': 1024.8,
           'tavg': 6.1,
           'tmax': 9.4,
           'tmin': 3.1,
           'tsun': 6162,
           'wspd': None},
          {'date': '2020-12-01 00:00:00',
           'prcp': 20.9,
           'pres': 1010.1,
           'tavg': 3.6,
           'tmax': 5.9,
           'tmin': 1.3,
           'tsun': 5310,
           'wspd': None}],
 'meta': {'generated': '2025-10-28 11:26:12'}}

In [20]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [21]:
weather_monthly_df=result

## flatten data

In [22]:
import pandas as pd

weather_monthly_df=pd.json_normalize(weather_monthly_df)

In [23]:
# weather monthly raw data:
weather_monthly_df

                                                data       meta.generated
0  [{'date': '2020-01-01 00:00:00', 'tavg': 3.1, ...  2025-10-28 11:26:12

In [24]:
# try to flatten the data, meta data is not needed, only data is needed.
# 0 is because there is only one row in the table of the raw data.
# [0, 'data'] is helping me to extract the weather monthly data for the following station:
# "station":"10488","start":"2020-01-01","end":"2020-12-31"
weather_monthly_df.loc[0,'data']

[{'date': '2020-01-01 00:00:00',
  'tavg': 3.1,
  'tmin': 0.0,
  'tmax': 6.1,
  'prcp': 17.6,
  'wspd': None,
  'pres': 1023.7,
  'tsun': 3870},
 {'date': '2020-02-01 00:00:00',
  'tavg': 5.6,
  'tmin': 2.4,
  'tmax': 8.8,
  'prcp': 88.9,
  'wspd': None,
  'pres': 1013.1,
  'tsun': 3252},
 {'date': '2020-03-01 00:00:00',
  'tavg': 5.3,
  'tmin': 0.8,
  'tmax': 9.6,
  'prcp': 25.5,
  'wspd': None,
  'pres': 1018.6,
  'tsun': 10626},
 {'date': '2020-04-01 00:00:00',
  'tavg': 11.0,
  'tmin': 4.4,
  'tmax': 16.7,
  'prcp': 1.9,
  'wspd': None,
  'pres': 1018.4,
  'tsun': 17814},
 {'date': '2020-05-01 00:00:00',
  'tavg': 12.1,
  'tmin': 6.7,
  'tmax': 17.5,
  'prcp': 42.7,
  'wspd': None,
  'pres': 1019.6,
  'tsun': 12852},
 {'date': '2020-06-01 00:00:00',
  'tavg': 18.1,
  'tmin': 13.2,
  'tmax': 23.4,
  'prcp': 40.5,
  'wspd': None,
  'pres': 1012.5,
  'tsun': 11862},
 {'date': '2020-07-01 00:00:00',
  'tavg': 19.3,
  'tmin': 13.4,
  'tmax': 25.2,
  'prcp': 17.0,
  'wspd': None,
  'pres': 1015.9,
  'tsun': 15300},
 {'date': '2020-08-01 00:00:00',
  'tavg': 21.2,
  'tmin': 15.7,
  'tmax': 26.7,
  'prcp': 119.4,
  'wspd': None,
  'pres': 1013.6,
  'tsun': 13734},
 {'date': '2020-09-01 00:00:00',
  'tavg': 16.0,
  'tmin': 10.0,
  'tmax': 21.4,
  'prcp': 49.7,
  'wspd': None,
  'pres': 1016.9,
  'tsun': 13566},
 {'date': '2020-10-01 00:00:00',
  'tavg': 10.9,
  'tmin': 7.9,
  'tmax': 14.0,
  'prcp': 105.8,
  'wspd': None,
  'pres': 1012.6,
  'tsun': 4980},
 {'date': '2020-11-01 00:00:00',
  'tavg': 6.1,
  'tmin': 3.1,
  'tmax': 9.4,
  'prcp': 6.1,
  'wspd': None,
  'pres': 1024.8,
  'tsun': 6162},
 {'date': '2020-12-01 00:00:00',
  'tavg': 3.6,
  'tmin': 1.3,
  'tmax': 5.9,
  'prcp': 20.9,
  'wspd': None,
  'pres': 1010.1,
  'tsun': 5310}]

In [25]:
weather_monthly_df_station_10488=pd.json_normalize(weather_monthly_df.loc[0,'data'])

In [38]:
weather_monthly_df_station_10488

                   date  tavg  tmin  tmax   prcp  wspd    pres   tsun
0   2020-01-01 00:00:00   3.1   0.0   6.1   17.6  None  1023.7   3870
1   2020-02-01 00:00:00   5.6   2.4   8.8   88.9  None  1013.1   3252
2   2020-03-01 00:00:00   5.3   0.8   9.6   25.5  None  1018.6  10626
3   2020-04-01 00:00:00  11.0   4.4  16.7    1.9  None  1018.4  17814
4   2020-05-01 00:00:00  12.1   6.7  17.5   42.7  None  1019.6  12852
5   2020-06-01 00:00:00  18.1  13.2  23.4   40.5  None  1012.5  11862
6   2020-07-01 00:00:00  19.3  13.4  25.2   17.0  None  1015.9  15300
7   2020-08-01 00:00:00  21.2  15.7  26.7  119.4  None  1013.6  13734
8   2020-09-01 00:00:00  16.0  10.0  21.4   49.7  None  1016.9  13566
9   2020-10-01 00:00:00  10.9   7.9  14.0  105.8  None  1012.6   4980
10  2020-11-01 00:00:00   6.1   3.1   9.4    6.1  None  1024.8   6162
11  2020-12-01 00:00:00   3.6   1.3   5.9   20.9  None  1010.1   5310

## write data from pandas to sql: two options

### Version 1: Using SET search_path

In [40]:
from sqlalchemy import create_engine, types
from sqlalchemy import text # to be able to pass string

# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}' #the same like version 1

# let's switch the logging off again. .
engine = create_engine(url, echo=False) #the same like version 1

my_schema = pg_schema 

with engine.begin() as conn:
    conn.execute(text(f'SET search_path TO {my_schema};'))

weather_monthly_df_station_10488.to_sql('weather_monthly_df_station_10488_test_1', engine, if_exists='replace',index=True)

12

### Version 2: Using schema parameter in to_sql

In [73]:
# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}' #the same like version 1

# let's switch the logging off again. .
engine = create_engine(url, echo=False) #the same like version 1


# writing dataframe to DB : Pandas Dataframe to DB Table in my own Schema
weather_monthly_df_station_10488.to_sql(name = 'weather_monthly_df_station_10488_test_2', 
                       con = engine, 
                       schema = pg_schema, # pandas is allowing to specify, in which schema the table shall be created
                       if_exists='replace', 
                       index=False
                      )

12

## read data from sql to pandas

### version 1: Using SET search_path/my_schema: my_schema = pg_schema is defined as a separate variable.

In [74]:
# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']
pg_api_key  =config['X-RapidAPI-Key']

# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# let's switch the logging off again. .
engine = create_engine(url, echo=False)

my_schema = pg_schema # update it to your schema

with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {my_schema};'))

query_weather_monthly_df_station_10488_test_2 ='''
SELECT * FROM weather_monthly_df_station_10488_test_2
LIMIT 10
'''

weather_monthly_df_station_10488_test_2 = pd.read_sql(query_weather_monthly_df_station_10488_test_2, con=engine)
weather_monthly_df_station_10488_test_2.head()

                  date  tavg  tmin  tmax  prcp  wspd    pres   tsun
0  2020-01-01 00:00:00   3.1   0.0   6.1  17.6  None  1023.7   3870
1  2020-02-01 00:00:00   5.6   2.4   8.8  88.9  None  1013.1   3252
2  2020-03-01 00:00:00   5.3   0.8   9.6  25.5  None  1018.6  10626
3  2020-04-01 00:00:00  11.0   4.4  16.7   1.9  None  1018.4  17814
4  2020-05-01 00:00:00  12.1   6.7  17.5  42.7  None  1019.6  12852

### version 2: Using SET search_path/pg_schema: directly use pg_schema without defining my_schema

In [75]:
import pandas as pd

# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']
pg_api_key  =config['X-RapidAPI-Key']

# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# let's switch the logging off again. .
engine = create_engine(url, echo=False)

with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {pg_schema};'))

query_weather_monthly_df_station_10488_test_2 =f'''
SELECT * FROM weather_monthly_df_station_10488_test_2
LIMIT 10;
'''
weather_monthly_df_station_10488_test_2 = pd.read_sql(query_weather_monthly_df_station_10488_test_2, con=engine)
weather_monthly_df_station_10488_test_2.head()

                  date  tavg  tmin  tmax  prcp  wspd    pres   tsun
0  2020-01-01 00:00:00   3.1   0.0   6.1  17.6  None  1023.7   3870
1  2020-02-01 00:00:00   5.6   2.4   8.8  88.9  None  1013.1   3252
2  2020-03-01 00:00:00   5.3   0.8   9.6  25.5  None  1018.6  10626
3  2020-04-01 00:00:00  11.0   4.4  16.7   1.9  None  1018.4  17814
4  2020-05-01 00:00:00  12.1   6.7  17.5  42.7  None  1019.6  12852

### version 3: don’t set the search path, but explicitly include the schema in every query.
### Example: df = pd.read_sql("SELECT * FROM my_schema.weather_data", con=engine)

In [77]:
import pandas as pd

# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']
pg_api_key  =config['X-RapidAPI-Key']

# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# let's switch the logging off again. .
engine = create_engine(url, echo=False)

query_weather_monthly_df_station_10488_test_2 =f'''
SELECT * FROM {pg_schema}.weather_monthly_df_station_10488_test_2
LIMIT 10;
'''
weather_monthly_df_station_10488_test_2 = pd.read_sql(query_weather_monthly_df_station_10488_test_2, con=engine)
weather_monthly_df_station_10488_test_2.head()

                  date  tavg  tmin  tmax  prcp  wspd    pres   tsun
0  2020-01-01 00:00:00   3.1   0.0   6.1  17.6  None  1023.7   3870
1  2020-02-01 00:00:00   5.6   2.4   8.8  88.9  None  1013.1   3252
2  2020-03-01 00:00:00   5.3   0.8   9.6  25.5  None  1018.6  10626
3  2020-04-01 00:00:00  11.0   4.4  16.7   1.9  None  1018.4  17814
4  2020-05-01 00:00:00  12.1   6.7  17.5  42.7  None  1019.6  12852

### Summary: where to put the schema connection

In [78]:
# | Version | Schema Handling                              | Pros                          | Cons                               |
# | ------- | -------------------------------------------- | ----------------------------- | ---------------------------------- |
# | **1**   | `SET search_path` (via connection)           | Clean SQL; schema set once    | Requires session command each time |
# | **2**   | Same as #1 (slightly cleaner variable usage) | Same as above                 | Same as above                      |
# | **3**   | Schema included in SQL query                 | Portable; no need to set path | Longer SQL; schema repeated        |

## Summary: to_sql/pd.read.sql

In [ ]:
# Summary of df.to_sql/pd.read_sql
# | Goal                             | Correct function                         | Example                                                     |
# | -------------------------------- | ---------------------------------------- | ----------------------------------------------------------- |
# | Write a DataFrame → PostgreSQL   | `.to_sql()`                              | `df.to_sql(name='mytable', con=engine, schema='myschema')`  |
# | Read from PostgreSQL → DataFrame | `pd.read_sql()` or `pd.read_sql_table()` | `pd.read_sql('SELECT * FROM myschema.mytable', con=engine)` |

In [ ]:
# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# let's switch the logging off again. .
engine = create_engine(url, echo=False)

# writing dataframe to DB : Pandas Dataframe to DB Table in my own Schema

weather_monthly_df_station_10488_test_2.read_sql(
                       con = engine, 
                       schema = pg_schema, # pandas is allowing to specify, in which schema the table shall be created
                      )

In [ ]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/hourly"

querystring = {"station":"10637","start":"2020-01-01","end":"2020-01-01","tz":"Europe/Berlin"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

In [ ]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

In [ ]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/daily"

querystring = {"station":"10637","start":"2020-01-01","end":"2020-01-31"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

In [ ]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

In [ ]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/normals"

querystring = {"station":"10637","start":"1961","end":"1990"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

In [ ]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

In [ ]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/meta"

querystring = {"id":"10637"}

headers = {
	"x-rapidapi-key": "266de98c8bmshe6415149f05acb9p1b51b7jsn1848d2d70180",
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

In [ ]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

In [ ]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/nearby"

querystring = {"lat":"51.5085","lon":"-0.1257"}

headers = {
	"x-rapidapi-key":pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

In [ ]:
# If you see 200, the request succeeded ✅.
print(response.status_code)