In [1]:
# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']
pg_api_key  =config['X-RapidAPI-Key']

In [31]:
import pprint

In [13]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/monthly"

querystring = {"station":"10637","start":"2020-01-01","end":"2020-12-31"}

headers = {
	"x-rapidapi-key": pg_api_key, #use the value of env file
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

result = response.json()

pprint.pprint(result)

{'data': [{'date': '2020-01-01 00:00:00',
           'prcp': 36.9,
           'pres': 1025.2,
           'tavg': 4.1,
           'tmax': 7.0,
           'tmin': 1.0,
           'tsun': 3306,
           'wspd': None},
          {'date': '2020-02-01 00:00:00',
           'prcp': 78.9,
           'pres': 1016.1,
           'tavg': 6.5,
           'tmax': 10.2,
           'tmin': 2.4,
           'tsun': 4608,
           'wspd': None},
          {'date': '2020-03-01 00:00:00',
           'prcp': 47.9,
           'pres': 1018.1,
           'tavg': 7.4,
           'tmax': 12.3,
           'tmin': 2.3,
           'tsun': 11244,
           'wspd': None},
          {'date': '2020-04-01 00:00:00',
           'prcp': 21.8,
           'pres': 1017.5,
           'tavg': 12.9,
           'tmax': 20.3,
           'tmin': 5.1,
           'tsun': 18402,
           'wspd': None},
          {'date': '2020-05-01 00:00:00',
           'prcp': 31.1,
           'pres': 1020.3,
           'tavg': 14.2,
           'tmax': 20.2,
           'tmin': 7.4,
           'tsun': 18240,
           'wspd': None},
          {'date': '2020-06-01 00:00:00',
           'prcp': 44.4,
           'pres': 1013.3,
           'tavg': 18.6,
           'tmax': 24.2,
           'tmin': 12.6,
           'tsun': 13260,
           'wspd': None},
          {'date': '2020-07-01 00:00:00',
           'prcp': 15.5,
           'pres': 1016.6,
           'tavg': 20.6,
           'tmax': 26.8,
           'tmin': 13.9,
           'tsun': 16074,
           'wspd': None},
          {'date': '2020-08-01 00:00:00',
           'prcp': 76.0,
           'pres': 1013.6,
           'tavg': 22.0,
           'tmax': 28.1,
           'tmin': 16.2,
           'tsun': 12552,
           'wspd': None},
          {'date': '2020-09-01 00:00:00',
           'prcp': 32.0,
           'pres': 1016.7,
           'tavg': 17.0,
           'tmax': 23.5,
           'tmin': 10.9,
           'tsun': 13674,
           'wspd': None},
          {'date': '2020-10-01 00:00:00',
           'prcp': 60.7,
           'pres': 1013.1,
           'tavg': 11.3,
           'tmax': 14.8,
           'tmin': 7.3,
           'tsun': 3648,
           'wspd': None},
          {'date': '2020-11-01 00:00:00',
           'prcp': 16.2,
           'pres': 1025.2,
           'tavg': 6.6,
           'tmax': 10.1,
           'tmin': 3.0,
           'tsun': 5490,
           'wspd': None},
          {'date': '2020-12-01 00:00:00',
           'prcp': 81.1,
           'pres': 1009.0,
           'tavg': 4.3,
           'tmax': 6.5,
           'tmin': 1.8,
           'tsun': 1176,
           'wspd': None}],
 'meta': {'generated': '2025-10-28 10:48:56'}}

In [53]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [14]:
# inspect the data: string, dictionary, etc.
# json normalization

In [ ]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/monthly"

querystring = {"station":"10488","start":"2020-01-01","end":"2020-12-31"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

result=response.json()

pprint.pprint(result)

{'data': [{'date': '2020-01-01 00:00:00',
           'prcp': 17.6,
           'pres': 1023.7,
           'tavg': 3.1,
           'tmax': 6.1,
           'tmin': 0.0,
           'tsun': 3870,
           'wspd': None},
          {'date': '2020-02-01 00:00:00',
           'prcp': 88.9,
           'pres': 1013.1,
           'tavg': 5.6,
           'tmax': 8.8,
           'tmin': 2.4,
           'tsun': 3252,
           'wspd': None},
          {'date': '2020-03-01 00:00:00',
           'prcp': 25.5,
           'pres': 1018.6,
           'tavg': 5.3,
           'tmax': 9.6,
           'tmin': 0.8,
           'tsun': 10626,
           'wspd': None},
          {'date': '2020-04-01 00:00:00',
           'prcp': 1.9,
           'pres': 1018.4,
           'tavg': 11.0,
           'tmax': 16.7,
           'tmin': 4.4,
           'tsun': 17814,
           'wspd': None},
          {'date': '2020-05-01 00:00:00',
           'prcp': 42.7,
           'pres': 1019.6,
           'tavg': 12.1,
           'tmax': 17.5,
           'tmin': 6.7,
           'tsun': 12852,
           'wspd': None},
          {'date': '2020-06-01 00:00:00',
           'prcp': 40.5,
           'pres': 1012.5,
           'tavg': 18.1,
           'tmax': 23.4,
           'tmin': 13.2,
           'tsun': 11862,
           'wspd': None},
          {'date': '2020-07-01 00:00:00',
           'prcp': 17.0,
           'pres': 1015.9,
           'tavg': 19.3,
           'tmax': 25.2,
           'tmin': 13.4,
           'tsun': 15300,
           'wspd': None},
          {'date': '2020-08-01 00:00:00',
           'prcp': 119.4,
           'pres': 1013.6,
           'tavg': 21.2,
           'tmax': 26.7,
           'tmin': 15.7,
           'tsun': 13734,
           'wspd': None},
          {'date': '2020-09-01 00:00:00',
           'prcp': 49.7,
           'pres': 1016.9,
           'tavg': 16.0,
           'tmax': 21.4,
           'tmin': 10.0,
           'tsun': 13566,
           'wspd': None},
          {'date': '2020-10-01 00:00:00',
           'prcp': 105.8,
           'pres': 1012.6,
           'tavg': 10.9,
           'tmax': 14.0,
           'tmin': 7.9,
           'tsun': 4980,
           'wspd': None},
          {'date': '2020-11-01 00:00:00',
           'prcp': 6.1,
           'pres': 1024.8,
           'tavg': 6.1,
           'tmax': 9.4,
           'tmin': 3.1,
           'tsun': 6162,
           'wspd': None},
          {'date': '2020-12-01 00:00:00',
           'prcp': 20.9,
           'pres': 1010.1,
           'tavg': 3.6,
           'tmax': 5.9,
           'tmin': 1.3,
           'tsun': 5310,
           'wspd': None}],
 'meta': {'generated': '2025-10-28 11:26:12'}}

In [54]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [34]:
weather_monthly_df=result

In [45]:
import pandas as pd

weather_monthly_df=pd.json_normalize(weather_monthly_df)

In [60]:
# weather monthly raw data:
weather_monthly_df

                                                data       meta.generated
0  [{'date': '2020-01-01 00:00:00', 'tavg': 3.1, ...  2025-10-28 11:26:12

In [62]:
# try to flatten the data, meta data is not needed, only data is needed.
# 0 is because there is only one row in the table of the raw data.
# [0, 'data'] is helping me to extract the weather monthly data for the following station:
# "station":"10488","start":"2020-01-01","end":"2020-12-31"
weather_monthly_df.loc[0,'data']

[{'date': '2020-01-01 00:00:00',
  'tavg': 3.1,
  'tmin': 0.0,
  'tmax': 6.1,
  'prcp': 17.6,
  'wspd': None,
  'pres': 1023.7,
  'tsun': 3870},
 {'date': '2020-02-01 00:00:00',
  'tavg': 5.6,
  'tmin': 2.4,
  'tmax': 8.8,
  'prcp': 88.9,
  'wspd': None,
  'pres': 1013.1,
  'tsun': 3252},
 {'date': '2020-03-01 00:00:00',
  'tavg': 5.3,
  'tmin': 0.8,
  'tmax': 9.6,
  'prcp': 25.5,
  'wspd': None,
  'pres': 1018.6,
  'tsun': 10626},
 {'date': '2020-04-01 00:00:00',
  'tavg': 11.0,
  'tmin': 4.4,
  'tmax': 16.7,
  'prcp': 1.9,
  'wspd': None,
  'pres': 1018.4,
  'tsun': 17814},
 {'date': '2020-05-01 00:00:00',
  'tavg': 12.1,
  'tmin': 6.7,
  'tmax': 17.5,
  'prcp': 42.7,
  'wspd': None,
  'pres': 1019.6,
  'tsun': 12852},
 {'date': '2020-06-01 00:00:00',
  'tavg': 18.1,
  'tmin': 13.2,
  'tmax': 23.4,
  'prcp': 40.5,
  'wspd': None,
  'pres': 1012.5,
  'tsun': 11862},
 {'date': '2020-07-01 00:00:00',
  'tavg': 19.3,
  'tmin': 13.4,
  'tmax': 25.2,
  'prcp': 17.0,
  'wspd': None,
  'pres': 1015.9,
  'tsun': 15300},
 {'date': '2020-08-01 00:00:00',
  'tavg': 21.2,
  'tmin': 15.7,
  'tmax': 26.7,
  'prcp': 119.4,
  'wspd': None,
  'pres': 1013.6,
  'tsun': 13734},
 {'date': '2020-09-01 00:00:00',
  'tavg': 16.0,
  'tmin': 10.0,
  'tmax': 21.4,
  'prcp': 49.7,
  'wspd': None,
  'pres': 1016.9,
  'tsun': 13566},
 {'date': '2020-10-01 00:00:00',
  'tavg': 10.9,
  'tmin': 7.9,
  'tmax': 14.0,
  'prcp': 105.8,
  'wspd': None,
  'pres': 1012.6,
  'tsun': 4980},
 {'date': '2020-11-01 00:00:00',
  'tavg': 6.1,
  'tmin': 3.1,
  'tmax': 9.4,
  'prcp': 6.1,
  'wspd': None,
  'pres': 1024.8,
  'tsun': 6162},
 {'date': '2020-12-01 00:00:00',
  'tavg': 3.6,
  'tmin': 1.3,
  'tmax': 5.9,
  'prcp': 20.9,
  'wspd': None,
  'pres': 1010.1,
  'tsun': 5310}]

In [50]:
weather_monthly_df_station_10488=pd.json_normalize(weather_monthly_df.loc[0,'data'])

In [51]:
weather_monthly_df_station_10488

                   date  tavg  tmin  tmax   prcp  wspd    pres   tsun
0   2020-01-01 00:00:00   3.1   0.0   6.1   17.6  None  1023.7   3870
1   2020-02-01 00:00:00   5.6   2.4   8.8   88.9  None  1013.1   3252
2   2020-03-01 00:00:00   5.3   0.8   9.6   25.5  None  1018.6  10626
3   2020-04-01 00:00:00  11.0   4.4  16.7    1.9  None  1018.4  17814
4   2020-05-01 00:00:00  12.1   6.7  17.5   42.7  None  1019.6  12852
5   2020-06-01 00:00:00  18.1  13.2  23.4   40.5  None  1012.5  11862
6   2020-07-01 00:00:00  19.3  13.4  25.2   17.0  None  1015.9  15300
7   2020-08-01 00:00:00  21.2  15.7  26.7  119.4  None  1013.6  13734
8   2020-09-01 00:00:00  16.0  10.0  21.4   49.7  None  1016.9  13566
9   2020-10-01 00:00:00  10.9   7.9  14.0  105.8  None  1012.6   4980
10  2020-11-01 00:00:00   6.1   3.1   9.4    6.1  None  1024.8   6162
11  2020-12-01 00:00:00   3.6   1.3   5.9   20.9  None  1010.1   5310

In [52]:
from sqlalchemy import create_engine, types
from sqlalchemy import text # to be able to pass string

In [55]:
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

In [56]:
engine = create_engine(url, echo=False)

In [57]:
engine.url # password is hidden

postgresql://jingwang:***@data-analytics-course-2.c8g8r1deus2v.eu-central-1.rds.amazonaws.com:5432/nf_180825

In [58]:
my_schema = 's_jingwang' # update it to your schema

with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {my_schema};'))

In [59]:
weather_monthly_df_station_10488.to_sql('weather_monthly_df_station_10488', engine, if_exists='replace',index=True)

12

In [29]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/hourly"

querystring = {"station":"10637","start":"2020-01-01","end":"2020-01-01","tz":"Europe/Berlin"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

{'data': [{'coco': 3,
           'dwpt': -1.5,
           'prcp': 0.0,
           'pres': 1036.9,
           'rhum': 88.0,
           'snow': None,
           'temp': 0.3,
           'time': '2020-01-01 00:00:00',
           'tsun': 0,
           'wdir': 40.0,
           'wpgt': 13.0,
           'wspd': 8.6},
          {'coco': 3,
           'dwpt': -1.4,
           'prcp': 0.0,
           'pres': 1036.5,
           'rhum': 90.0,
           'snow': 0.0,
           'temp': 0.0,
           'time': '2020-01-01 01:00:00',
           'tsun': 0,
           'wdir': 40.0,
           'wpgt': 15.0,
           'wspd': 9.7},
          {'coco': 5,
           'dwpt': -1.3,
           'prcp': 0.0,
           'pres': 1036.3,
           'rhum': 90.0,
           'snow': None,
           'temp': 0.1,
           'time': '2020-01-01 02:00:00',
           'tsun': 0,
           'wdir': 20.0,
           'wpgt': 15.0,
           'wspd': 10.1},
          {'coco': 2,
           'dwpt': -2.2,
           'prcp': 0.0,
           'pres': 1036.2,
           'rhum': 92.0,
           'snow': None,
           'temp': -1.1,
           'time': '2020-01-01 03:00:00',
           'tsun': 0,
           'wdir': 70.0,
           'wpgt': 13.0,
           'wspd': 7.9},
          {'coco': 3,
           'dwpt': -1.4,
           'prcp': 0.0,
           'pres': 1035.7,
           'rhum': 93.0,
           'snow': None,
           'temp': -0.4,
           'time': '2020-01-01 04:00:00',
           'tsun': 0,
           'wdir': 80.0,
           'wpgt': 11.0,
           'wspd': 5.8},
          {'coco': 3,
           'dwpt': -1.2,
           'prcp': 0.0,
           'pres': 1035.4,
           'rhum': 90.0,
           'snow': None,
           'temp': 0.2,
           'time': '2020-01-01 05:00:00',
           'tsun': 0,
           'wdir': 50.0,
           'wpgt': 11.0,
           'wspd': 7.2},
          {'coco': 2,
           'dwpt': -2.8,
           'prcp': 0.0,
           'pres': 1035.2,
           'rhum': 91.0,
           'snow': None,
           'temp': -1.5,
           'time': '2020-01-01 06:00:00',
           'tsun': 0,
           'wdir': 50.0,
           'wpgt': 13.0,
           'wspd': 8.3},
          {'coco': 1,
           'dwpt': -2.3,
           'prcp': 0.0,
           'pres': 1035.2,
           'rhum': 92.0,
           'snow': 0.0,
           'temp': -1.2,
           'time': '2020-01-01 07:00:00',
           'tsun': 0,
           'wdir': 50.0,
           'wpgt': 15.0,
           'wspd': 9.7},
          {'coco': 1,
           'dwpt': -2.5,
           'prcp': 0.0,
           'pres': 1035.4,
           'rhum': 92.0,
           'snow': None,
           'temp': -1.4,
           'time': '2020-01-01 08:00:00',
           'tsun': 0,
           'wdir': 10.0,
           'wpgt': 15.0,
           'wspd': 10.4},
          {'coco': 2,
           'dwpt': -2.5,
           'prcp': 0.0,
           'pres': 1035.8,
           'rhum': 91.0,
           'snow': None,
           'temp': -1.2,
           'time': '2020-01-01 09:00:00',
           'tsun': 0,
           'wdir': 30.0,
           'wpgt': 18.0,
           'wspd': 11.2},
          {'coco': 2,
           'dwpt': -2.4,
           'prcp': 0.0,
           'pres': 1036.1,
           'rhum': 87.0,
           'snow': None,
           'temp': -0.5,
           'time': '2020-01-01 10:00:00',
           'tsun': 53,
           'wdir': 30.0,
           'wpgt': 17.0,
           'wspd': 10.8},
          {'coco': 2,
           'dwpt': -2.1,
           'prcp': 0.0,
           'pres': 1036.0,
           'rhum': 82.0,
           'snow': None,
           'temp': 0.6,
           'time': '2020-01-01 11:00:00',
           'tsun': 60,
           'wdir': 20.0,
           'wpgt': 21.0,
           'wspd': 12.2},
          {'coco': 2,
           'dwpt': -1.2,
           'prcp': 0.0,
           'pres': 1035.3,
           'rhum': 77.0,
           'snow': None,
           'temp': 2.4,
           'time': '2020-01-01 12:00:00',
           'tsun': 60,
           'wdir': 40.0,
           'wpgt': 18.0,
           'wspd': 11.2},
          {'coco': 1,
           'dwpt': -0.9,
           'prcp': 0.0,
           'pres': 1034.6,
           'rhum': 73.0,
           'snow': 0.0,
           'temp': 3.5,
           'time': '2020-01-01 13:00:00',
           'tsun': 60,
           'wdir': 60.0,
           'wpgt': 22.0,
           'wspd': 14.8},
          {'coco': 1,
           'dwpt': -0.9,
           'prcp': 0.0,
           'pres': 1033.7,
           'rhum': 71.0,
           'snow': None,
           'temp': 3.9,
           'time': '2020-01-01 14:00:00',
           'tsun': 60,
           'wdir': 70.0,
           'wpgt': 21.0,
           'wspd': 13.7},
          {'coco': 1,
           'dwpt': -0.9,
           'prcp': 0.0,
           'pres': 1033.5,
           'rhum': 69.0,
           'snow': None,
           'temp': 4.3,
           'time': '2020-01-01 15:00:00',
           'tsun': 60,
           'wdir': 70.0,
           'wpgt': 22.0,
           'wspd': 14.0},
          {'coco': 1,
           'dwpt': -0.6,
           'prcp': 0.0,
           'pres': 1033.6,
           'rhum': 74.0,
           'snow': None,
           'temp': 3.6,
           'time': '2020-01-01 16:00:00',
           'tsun': 60,
           'wdir': 50.0,
           'wpgt': 18.0,
           'wspd': 11.2},
          {'coco': 1,
           'dwpt': -0.7,
           'prcp': 0.0,
           'pres': 1033.4,
           'rhum': 81.0,
           'snow': None,
           'temp': 2.2,
           'time': '2020-01-01 17:00:00',
           'tsun': 22,
           'wdir': 40.0,
           'wpgt': 15.0,
           'wspd': 8.3},
          {'coco': 1,
           'dwpt': -0.8,
           'prcp': 0.0,
           'pres': 1033.5,
           'rhum': 85.0,
           'snow': None,
           'temp': 1.4,
           'time': '2020-01-01 18:00:00',
           'tsun': 0,
           'wdir': 60.0,
           'wpgt': 11.0,
           'wspd': 5.8},
          {'coco': 1,
           'dwpt': -1.7,
           'prcp': 0.0,
           'pres': 1033.4,
           'rhum': 87.0,
           'snow': 0.0,
           'temp': 0.2,
           'time': '2020-01-01 19:00:00',
           'tsun': 0,
           'wdir': 60.0,
           'wpgt': 18.0,
           'wspd': 12.6},
          {'coco': 1,
           'dwpt': -2.5,
           'prcp': 0.0,
           'pres': 1033.8,
           'rhum': 87.0,
           'snow': None,
           'temp': -0.6,
           'time': '2020-01-01 20:00:00',
           'tsun': 0,
           'wdir': 60.0,
           'wpgt': 22.0,
           'wspd': 14.0},
          {'coco': 1,
           'dwpt': -2.8,
           'prcp': 0.0,
           'pres': 1033.7,
           'rhum': 89.0,
           'snow': None,
           'temp': -1.2,
           'time': '2020-01-01 21:00:00',
           'tsun': 0,
           'wdir': 50.0,
           'wpgt': 11.0,
           'wspd': 8.3},
          {'coco': 1,
           'dwpt': -2.2,
           'prcp': 0.0,
           'pres': 1033.1,
           'rhum': 92.0,
           'snow': None,
           'temp': -1.1,
           'time': '2020-01-01 22:00:00',
           'tsun': 0,
           'wdir': 60.0,
           'wpgt': 13.0,
           'wspd': 7.6},
          {'coco': 1,
           'dwpt': -2.1,
           'prcp': 0.0,
           'pres': 1032.8,
           'rhum': 93.0,
           'snow': None,
           'temp': -1.1,
           'time': '2020-01-01 23:00:00',
           'tsun': 0,
           'wdir': 20.0,
           'wpgt': 18.0,
           'wspd': 8.6}],
 'meta': {'generated': '2025-10-28 13:16:07'}}

In [17]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [30]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/daily"

querystring = {"station":"10637","start":"2020-01-01","end":"2020-01-31"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

{'data': [{'date': '2020-01-01 00:00:00',
           'prcp': 0.1,
           'pres': 1035.5,
           'snow': 0.0,
           'tavg': 0.4,
           'tmax': 4.5,
           'tmin': -3.6,
           'tsun': 438,
           'wdir': None,
           'wpgt': 22.3,
           'wspd': 10.1},
          {'date': '2020-01-02 00:00:00',
           'prcp': 0.0,
           'pres': 1031.2,
           'snow': 0.0,
           'tavg': -0.5,
           'tmax': 1.4,
           'tmin': -2.4,
           'tsun': 0,
           'wdir': None,
           'wpgt': 25.9,
           'wspd': 6.1},
          {'date': '2020-01-03 00:00:00',
           'prcp': 0.5,
           'pres': 1024.4,
           'snow': 0.0,
           'tavg': 5.8,
           'tmax': 9.3,
           'tmin': 1.3,
           'tsun': 0,
           'wdir': None,
           'wpgt': 46.8,
           'wspd': 15.5},
          {'date': '2020-01-04 00:00:00',
           'prcp': 0.2,
           'pres': 1031.5,
           'snow': 0.0,
           'tavg': 5.4,
           'tmax': 6.8,
           'tmin': 2.4,
           'tsun': 0,
           'wdir': None,
           'wpgt': 47.5,
           'wspd': 15.8},
          {'date': '2020-01-05 00:00:00',
           'prcp': 1.1,
           'pres': 1036.6,
           'snow': 0.0,
           'tavg': 4.8,
           'tmax': 6.3,
           'tmin': 2.7,
           'tsun': 0,
           'wdir': None,
           'wpgt': 23.4,
           'wspd': 6.8},
          {'date': '2020-01-06 00:00:00',
           'prcp': 0.0,
           'pres': 1030.6,
           'snow': 0.0,
           'tavg': 1.1,
           'tmax': 4.6,
           'tmin': -0.9,
           'tsun': 0,
           'wdir': None,
           'wpgt': 19.8,
           'wspd': 6.5},
          {'date': '2020-01-07 00:00:00',
           'prcp': 0.0,
           'pres': 1029.9,
           'snow': 0.0,
           'tavg': 3.4,
           'tmax': 8.0,
           'tmin': -0.1,
           'tsun': 168,
           'wdir': None,
           'wpgt': 22.3,
           'wspd': 9.7},
          {'date': '2020-01-08 00:00:00',
           'prcp': 10.6,
           'pres': 1028.9,
           'snow': 0.0,
           'tavg': 4.9,
           'tmax': 7.5,
           'tmin': 2.8,
           'tsun': 0,
           'wdir': None,
           'wpgt': 27.7,
           'wspd': 11.9},
          {'date': '2020-01-09 00:00:00',
           'prcp': 8.6,
           'pres': 1019.9,
           'snow': 0.0,
           'tavg': 9.2,
           'tmax': 11.2,
           'tmin': 7.4,
           'tsun': 0,
           'wdir': None,
           'wpgt': 29.5,
           'wspd': 11.5},
          {'date': '2020-01-10 00:00:00',
           'prcp': 2.1,
           'pres': 1021.6,
           'snow': 0.0,
           'tavg': 8.3,
           'tmax': 11.6,
           'tmin': 4.0,
           'tsun': 168,
           'wdir': None,
           'wpgt': 44.3,
           'wspd': 15.8},
          {'date': '2020-01-11 00:00:00',
           'prcp': 0.0,
           'pres': 1034.3,
           'snow': 0.0,
           'tavg': 2.1,
           'tmax': 6.8,
           'tmin': -1.8,
           'tsun': 210,
           'wdir': None,
           'wpgt': 20.5,
           'wspd': 6.1},
          {'date': '2020-01-12 00:00:00',
           'prcp': 0.1,
           'pres': 1028.3,
           'snow': 0.0,
           'tavg': 2.4,
           'tmax': 5.5,
           'tmin': -2.6,
           'tsun': 0,
           'wdir': None,
           'wpgt': 37.8,
           'wspd': 14.0},
          {'date': '2020-01-13 00:00:00',
           'prcp': 0.0,
           'pres': 1022.7,
           'snow': 0.0,
           'tavg': 5.4,
           'tmax': 6.7,
           'tmin': 3.8,
           'tsun': 0,
           'wdir': None,
           'wpgt': 25.2,
           'wspd': 11.2},
          {'date': '2020-01-14 00:00:00',
           'prcp': 0.0,
           'pres': 1015.3,
           'snow': 0.0,
           'tavg': 8.0,
           'tmax': 10.4,
           'tmin': 4.0,
           'tsun': 6,
           'wdir': None,
           'wpgt': 37.1,
           'wspd': 15.8},
          {'date': '2020-01-15 00:00:00',
           'prcp': 0.1,
           'pres': 1019.1,
           'snow': 0.0,
           'tavg': 10.2,
           'tmax': 13.4,
           'tmin': 6.3,
           'tsun': 414,
           'wdir': None,
           'wpgt': 31.3,
           'wspd': 13.3},
          {'date': '2020-01-16 00:00:00',
           'prcp': 0.0,
           'pres': 1027.5,
           'snow': 0.0,
           'tavg': 8.3,
           'tmax': 13.7,
           'tmin': 2.2,
           'tsun': 444,
           'wdir': None,
           'wpgt': 20.5,
           'wspd': 6.1},
          {'date': '2020-01-17 00:00:00',
           'prcp': 0.0,
           'pres': 1021.6,
           'snow': 0.0,
           'tavg': 4.0,
           'tmax': 7.6,
           'tmin': -1.2,
           'tsun': 144,
           'wdir': None,
           'wpgt': 38.9,
           'wspd': 6.5},
          {'date': '2020-01-18 00:00:00',
           'prcp': 0.3,
           'pres': 1027.5,
           'snow': 0.0,
           'tavg': 4.1,
           'tmax': 6.7,
           'tmin': 1.1,
           'tsun': 150,
           'wdir': None,
           'wpgt': 38.9,
           'wspd': 12.6},
          {'date': '2020-01-19 00:00:00',
           'prcp': 0.0,
           'pres': 1038.1,
           'snow': 0.0,
           'tavg': 3.6,
           'tmax': 6.8,
           'tmin': -0.2,
           'tsun': 36,
           'wdir': None,
           'wpgt': 34.6,
           'wspd': 9.7},
          {'date': '2020-01-20 00:00:00',
           'prcp': 0.0,
           'pres': 1047.5,
           'snow': 0.0,
           'tavg': 2.2,
           'tmax': 7.2,
           'tmin': -1.9,
           'tsun': 366,
           'wdir': None,
           'wpgt': 32.8,
           'wspd': 9.7},
          {'date': '2020-01-21 00:00:00',
           'prcp': 0.0,
           'pres': 1043.5,
           'snow': 0.0,
           'tavg': 0.1,
           'tmax': 5.4,
           'tmin': -4.1,
           'tsun': 498,
           'wdir': None,
           'wpgt': 16.6,
           'wspd': 6.8},
          {'date': '2020-01-22 00:00:00',
           'prcp': 0.0,
           'pres': 1038.6,
           'snow': 0.0,
           'tavg': -2.9,
           'tmax': -0.4,
           'tmin': -5.6,
           'tsun': 0,
           'wdir': None,
           'wpgt': 18.0,
           'wspd': 5.4},
          {'date': '2020-01-23 00:00:00',
           'prcp': 0.0,
           'pres': 1033.7,
           'snow': 0.0,
           'tavg': 1.4,
           'tmax': 4.3,
           'tmin': -0.5,
           'tsun': 114,
           'wdir': None,
           'wpgt': 27.0,
           'wspd': 9.7},
          {'date': '2020-01-24 00:00:00',
           'prcp': 0.0,
           'pres': 1026.7,
           'snow': 0.0,
           'tavg': 0.5,
           'tmax': 1.1,
           'tmin': 0.1,
           'tsun': 0,
           'wdir': None,
           'wpgt': 20.5,
           'wspd': 6.5},
          {'date': '2020-01-25 00:00:00',
           'prcp': 0.0,
           'pres': 1024.5,
           'snow': 0.0,
           'tavg': 0.7,
           'tmax': 1.6,
           'tmin': 0.0,
           'tsun': 0,
           'wdir': None,
           'wpgt': 13.7,
           'wspd': 4.0},
          {'date': '2020-01-26 00:00:00',
           'prcp': 0.0,
           'pres': 1021.2,
           'snow': 0.0,
           'tavg': 1.4,
           'tmax': 2.2,
           'tmin': 0.2,
           'tsun': 0,
           'wdir': None,
           'wpgt': 18.4,
           'wspd': 5.4},
          {'date': '2020-01-27 00:00:00',
           'prcp': 9.9,
           'pres': 1012.4,
           'snow': 0.0,
           'tavg': 5.0,
           'tmax': 7.7,
           'tmin': 2.0,
           'tsun': 0,
           'wdir': None,
           'wpgt': 35.3,
           'wspd': 13.3},
          {'date': '2020-01-28 00:00:00',
           'prcp': 2.9,
           'pres': 1000.9,
           'snow': 0.0,
           'tavg': 5.3,
           'tmax': 7.6,
           'tmin': 2.0,
           'tsun': 18,
           'wdir': None,
           'wpgt': 77.0,
           'wspd': 24.5},
          {'date': '2020-01-29 00:00:00',
           'prcp': 0.1,
           'pres': 1011.0,
           'snow': 0.0,
           'tavg': 4.1,
           'tmax': 7.8,
           'tmin': 1.3,
           'tsun': 24,
           'wdir': None,
           'wpgt': 46.8,
           'wspd': 18.7},
          {'date': '2020-01-30 00:00:00',
           'prcp': 0.3,
           'pres': 1013.7,
           'snow': 0.0,
           'tavg': 6.8,
           'tmax': 9.2,
           'tmin': 3.4,
           'tsun': 84,
           'wdir': None,
           'wpgt': 37.1,
           'wspd': 17.6},
          {'date': '2020-01-31 00:00:00',
           'prcp': 0.0,
           'pres': 1011.9,
           'snow': 0.0,
           'tavg': 12.6,
           'tmax': 15.1,
           'tmin': 9.0,
           'tsun': 24,
           'wdir': None,
           'wpgt': 43.2,
           'wspd': 22.0}],
 'meta': {'generated': '2025-10-28 13:17:21'}}

In [20]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [22]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/normals"

querystring = {"station":"10637","start":"1961","end":"1990"}

headers = {
	"x-rapidapi-key": pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

{'data': [{'month': 1,
           'prcp': 43.8,
           'pres': 1018.0,
           'tavg': 0.5,
           'tmax': 3.1,
           'tmin': -2.1,
           'tsun': 2454,
           'wspd': 12.4},
          {'month': 2,
           'prcp': 39.8,
           'pres': 1017.5,
           'tavg': 1.8,
           'tmax': 5.2,
           'tmin': -1.6,
           'tsun': 4494,
           'wspd': 11.9},
          {'month': 3,
           'prcp': 51.1,
           'pres': 1014.9,
           'tavg': 5.3,
           'tmax': 9.7,
           'tmin': 0.9,
           'tsun': 6984,
           'wspd': 12.9},
          {'month': 4,
           'prcp': 51.5,
           'pres': 1014.2,
           'tavg': 9.0,
           'tmax': 14.2,
           'tmin': 3.9,
           'tsun': 9756,
           'wspd': 12.4},
          {'month': 5,
           'prcp': 61.3,
           'pres': 1014.6,
           'tavg': 13.4,
           'tmax': 19.0,
           'tmin': 7.9,
           'tsun': 12390,
           'wspd': 11.0},
          {'month': 6,
           'prcp': 70.2,
           'pres': 1015.6,
           'tavg': 16.8,
           'tmax': 22.2,
           'tmin': 11.3,
           'tsun': 12564,
           'wspd': 11.0},
          {'month': 7,
           'prcp': 63.0,
           'pres': 1016.6,
           'tavg': 18.6,
           'tmax': 24.2,
           'tmin': 13.0,
           'tsun': 13470,
           'wspd': 10.9},
          {'month': 8,
           'prcp': 64.8,
           'pres': 1016.1,
           'tavg': 18.3,
           'tmax': 23.9,
           'tmin': 12.7,
           'tsun': 12234,
           'wspd': 10.2},
          {'month': 9,
           'prcp': 48.3,
           'pres': 1018.3,
           'tavg': 15.0,
           'tmax': 20.2,
           'tmin': 9.7,
           'tsun': 9450,
           'wspd': 10.2},
          {'month': 10,
           'prcp': 50.5,
           'pres': 1017.6,
           'tavg': 10.0,
           'tmax': 14.2,
           'tmin': 5.8,
           'tsun': 6150,
           'wspd': 10.0},
          {'month': 11,
           'prcp': 59.4,
           'pres': 1018.3,
           'tavg': 4.6,
           'tmax': 7.6,
           'tmin': 1.7,
           'tsun': 2904,
           'wspd': 12.1},
          {'month': 12,
           'prcp': 54.1,
           'pres': 1016.9,
           'tavg': 1.5,
           'tmax': 4.1,
           'tmin': -1.0,
           'tsun': 2310,
           'wspd': 12.1}],
 'meta': {'generated': '2025-10-28 09:31:10'}}

In [23]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [24]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/meta"

querystring = {"id":"10637"}

headers = {
	"x-rapidapi-key": "266de98c8bmshe6415149f05acb9p1b51b7jsn1848d2d70180",
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

{'data': {'country': 'DE',
          'id': '10637',
          'identifier': {'icao': 'EDDF', 'national': '01420', 'wmo': '10637'},
          'inventory': {'daily': {'end': '2025-10-25', 'start': '1934-05-01'},
                        'hourly': {'end': '2025-09-30', 'start': '1926-01-01'},
                        'model': {'end': '2025-10-10', 'start': '2018-01-28'},
                        'monthly': {'end': 2022, 'start': 1934},
                        'normals': {'end': 2020, 'start': 1961}},
          'location': {'elevation': 111, 'latitude': 50.05, 'longitude': 8.6},
          'name': {'de': 'Frankfurt Flughafen',
                   'en': 'Frankfurt Airport',
                   'es': 'Aeropuerto de Fráncfort'},
          'region': 'HE',
          'timezone': 'Europe/Berlin'},
 'meta': {'generated': '2025-10-28 04:58:32'}}

In [25]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200

In [27]:
import requests

url = "https://meteostat.p.rapidapi.com/stations/nearby"

querystring = {"lat":"51.5085","lon":"-0.1257"}

headers = {
	"x-rapidapi-key":pg_api_key,
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

pprint.pprint(response.json())

{'data': [{'distance': 1104.3,
           'id': '03779',
           'name': {'en': 'London Weather Centre'}},
          {'distance': 16804.1,
           'id': 'EGLC0',
           'name': {'en': 'London / Abbey Wood'}},
          {'distance': 20652.3, 'id': '03672', 'name': {'en': 'Northolt'}},
          {'distance': 22624.4,
           'id': '03772',
           'name': {'en': 'London Heathrow Airport'}},
          {'distance': 23370.0, 'id': '03781', 'name': {'en': 'Kenley'}},
          {'distance': 24009.3,
           'id': 'EGKB0',
           'name': {'en': "Biggin Hill / berry's green"}},
          {'distance': 27961.2,
           'id': 'EGTI0',
           'name': {'en': 'Leavesden / North Watford'}},
          {'distance': 40063.6,
           'id': '03776',
           'name': {'en': 'London Gatwick Airport'}},
          {'distance': 43155.8,
           'id': '03673',
           'name': {'en': 'London / Chiltern Green / Newmill End / Stopsley / '
                          'Lilley'}},
          {'distance': 46423.7,
           'id': 'EGUH0',
           'name': {'en': 'High Wycombe / Sands'}}],
 'meta': {'generated': '2025-10-27 19:42:44'}}

In [28]:
# If you see 200, the request succeeded ✅.
print(response.status_code)

200