# 🌤️ Extracting `Daily Weather Data` from the Meteostat API and Loading It into a Database

Learning Goals

By the end of this notebook, you should be able to:

- Understand how to connect to and extract data from an external API (Meteostat).

- Load raw JSON data into a PostgreSQL database using Python and SQLAlchemy.

- Appreciate how this fits into a real data pipeline (Extract → Load → Transform).

## 1. Context: Where We Are in the Pipeline

In analytics workflows, the first step is often data ingestion.
Before we can analyze, clean, or visualize, we need to get the data out of APIs and into a database.

Today, we’ll:

- Extract daily weather data for 3 major US airports.

- Store the raw JSON response as-is in our database (so it can be transformed later).

- Later, we’ll transform it into structured tables for analysis.

- Think of this as building the “E” and “L” in ELT.

The Goal of this Notebook is to get raw JSON data for Daily and Hourly Weather for 3 airport weather stations and load it as it is to our database.
- Find Station IDs for **defined** airports 
- Define the start and end of the period
- get the API Key from the `.env`

## 2. Prerequisites and Setup

We’ll need:

- An API key for Meteostat on RapidAPI.

- A `.env` file containing both API and database credentials.

- Libraries: requests, pandas, sqlalchemy, dotenv.

In [1]:
# we will need the credentials we saved in the .env file
from dotenv import dotenv_values

# We also will need SQLAlchemy and its functions
from sqlalchemy import create_engine, types
from sqlalchemy.dialects.postgresql import JSON as postgres_json

import pandas as pd

# requests library will make the API calls. 
# the json package will parse the JSON string and convert it to Python data structures
import requests
import json

# with 'datetime' we want to catch the timestamp of the API call. For the actuality reference. 
# and 'time' for slowing down a .bit
from datetime import datetime
import time

### Defining Airports and finding the Station IDs

For our Pipeline we will use weather data from the weather stations at the 3 highly frequented airports
- **JFK**: John F. Kennedy Airport
- **MIA**: Miami International Airport
- **LAX**: Los Angeles Airport

To find the Station IDs for the airports without stressing our API Call limits, we will use the   search option of the **https://meteostat.net/**  

We can search for the names of the airports above and find the Station IDs.

Let's add them to the dictionary below.

In [ ]:
airport_staids = {
    'JFK': '74486',   # John F. Kennedy International Airport
    'MIA': '72202',   # Miami International Airport
    'LAX': '72295',   # Los Angeles Airport
           }

### Defining the period

Our flight Data is from 2024-01-01 until 2024-03-31. For the lectures we will use the same period for the meteostat JSON API.

In [3]:
period_start = "2024-01-01"
period_end = "2024-03-31"

## 3. Load API and DB Credentials

In [4]:
# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

pg_api_key = config['X-RapidAPI-Key']  # align the key label with your .env file
pg_user = config['POSTGRES_USER']
pg_pass = config['POSTGRES_PASS']
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']

## 4. Building and Testing the API Call

Let’s test the querystring for one airport.

Each API call will get 3 months of weather data for one Station ID.  

In the [**RapidAPI**](https://rapidapi.com/meteostat/api/meteostat/playground) interface you can find the code syntax we need to make the call. 

For each call we need to create a querystring with required parameters.

In [5]:
url = "https://meteostat.p.rapidapi.com/stations/daily"

headers = {
    "X-RapidAPI-Key": pg_api_key,
    "X-RapidAPI-Host": "meteostat.p.rapidapi.com"
}

# Just to inspect the query for one airport
for airport in airport_staids:
    querystring = {
        "station": airport_staids[airport],
        "start": period_start,
        "end": period_end,
        "model": "true"  # use model-based data where necessary
    }
    print(airport, "\n", querystring)

JFK
 {'station': '74486', 'start': '2024-01-01', 'end': '2024-03-31', 'model': 'true'}
MIA
 {'station': '72202', 'start': '2024-01-01', 'end': '2024-03-31', 'model': 'true'}
LAX
 {'station': '72295', 'start': '2024-01-01', 'end': '2024-03-31', 'model': 'true'}

### Objectives -  Daily Station Data:

- create a for-loop for the 3 airports, generating a **querystring for each API call**
- define an empty dictionary to collect: 
  - time of the call
  - airport code
  - station id
  - related data
- make the API calls using the for-loop and fill the dictionary
- create pandas dataframe from the dictionary
- load the DB credentials from the `.env`
- create the engine
- define data types for the postgresql table columns
- using pandas import the dataframe to the Table in the Schema of the DB

### API CALL daily (per station)

In [ ]:
#  let's catch each response in a dictionary. create an empty dictionary with the following keys:

weather_dict = {'extracted_at':[], 
                'airport_code':[], 
                'station_id':[], 
                'extracted_data':[]
               }


# for-loop for the querystrings
for airport in airport_staids:
    querystring = {
        "station":airport_staids[airport]
        ,"start":period_start
        ,"end":period_end
        ,"model":"true"
    }
    
    # making one call with the current querystring
    response = requests.get(url, headers=headers, params=querystring)

    # Add a slight delay to respect API limits
    time.sleep(1)
                
    # appending data to the dictionary:
    weather_dict['extracted_at'].append(pd.Timestamp.now())       # timestamp, or DateTime.now()
    weather_dict['airport_code'].append(airport)       # airport code    
    weather_dict['station_id'].append(airport_staids[airport])         # weater Station ID
    weather_dict['extracted_data'].append(json.loads(response.text))   # JSON string

In [51]:
result = response.json()

In [52]:
import pprint

pprint.pprint(result)  # Print only the first 2 entries nicely

{'data': [{'date': '2024-01-01 00:00:00',
           'prcp': 0.0,
           'pres': 1018.5,
           'snow': None,
           'tavg': 14.0,
           'tmax': 19.4,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.6},
          {'date': '2024-01-02 00:00:00',
           'prcp': 0.0,
           'pres': 1022.6,
           'snow': None,
           'tavg': 13.3,
           'tmax': 18.3,
           'tmin': 8.3,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.4},
          {'date': '2024-01-03 00:00:00',
           'prcp': 5.1,
           'pres': 1018.3,
           'snow': None,
           'tavg': 13.6,
           'tmax': 16.1,
           'tmin': 11.1,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 17.3},
          {'date': '2024-01-04 00:00:00',
           'prcp': 0.0,
           'pres': 1019.8,
           'snow': None,
           'tavg': 14.1,
           'tmax': 18.3,
           'tmin': 11.1,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 15.1},
          {'date': '2024-01-05 00:00:00',
           'prcp': 0.0,
           'pres': 1020.7,
           'snow': None,
           'tavg': 13.1,
           'tmax': 18.3,
           'tmin': 7.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.4},
          {'date': '2024-01-06 00:00:00',
           'prcp': 0.0,
           'pres': 1019.1,
           'snow': None,
           'tavg': 12.1,
           'tmax': 16.7,
           'tmin': 6.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 13.3},
          {'date': '2024-01-07 00:00:00',
           'prcp': 0.0,
           'pres': 1014.4,
           'snow': None,
           'tavg': 13.1,
           'tmax': 15.0,
           'tmin': 9.4,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 25.6},
          {'date': '2024-01-08 00:00:00',
           'prcp': 0.0,
           'pres': 1023.0,
           'snow': None,
           'tavg': 11.2,
           'tmax': 15.0,
           'tmin': 7.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.8},
          {'date': '2024-01-09 00:00:00',
           'prcp': 0.0,
           'pres': 1022.0,
           'snow': None,
           'tavg': 10.9,
           'tmax': 16.7,
           'tmin': 5.6,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.3},
          {'date': '2024-01-10 00:00:00',
           'prcp': 0.0,
           'pres': 1015.5,
           'snow': None,
           'tavg': 11.1,
           'tmax': 16.1,
           'tmin': 6.1,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.4},
          {'date': '2024-01-11 00:00:00',
           'prcp': 0.0,
           'pres': 1016.1,
           'snow': None,
           'tavg': 13.0,
           'tmax': 17.8,
           'tmin': 10.6,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 18.4},
          {'date': '2024-01-12 00:00:00',
           'prcp': 0.0,
           'pres': 1021.0,
           'snow': None,
           'tavg': 11.5,
           'tmax': 15.6,
           'tmin': 5.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.8},
          {'date': '2024-01-13 00:00:00',
           'prcp': 0.0,
           'pres': 1018.6,
           'snow': None,
           'tavg': 11.2,
           'tmax': 15.6,
           'tmin': 6.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 7.2},
          {'date': '2024-01-14 00:00:00',
           'prcp': 0.0,
           'pres': 1017.3,
           'snow': None,
           'tavg': 11.7,
           'tmax': 15.6,
           'tmin': 6.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.6},
          {'date': '2024-01-15 00:00:00',
           'prcp': 0.0,
           'pres': 1017.8,
           'snow': None,
           'tavg': 12.2,
           'tmax': 16.1,
           'tmin': 7.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 7.6},
          {'date': '2024-01-16 00:00:00',
           'prcp': 0.0,
           'pres': 1018.1,
           'snow': None,
           'tavg': 12.7,
           'tmax': 16.7,
           'tmin': 8.9,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.3},
          {'date': '2024-01-17 00:00:00',
           'prcp': 0.0,
           'pres': 1017.3,
           'snow': None,
           'tavg': 13.4,
           'tmax': 15.0,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 6.5},
          {'date': '2024-01-18 00:00:00',
           'prcp': 0.0,
           'pres': 1018.4,
           'snow': None,
           'tavg': 14.3,
           'tmax': 18.9,
           'tmin': 11.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.6},
          {'date': '2024-01-19 00:00:00',
           'prcp': 0.0,
           'pres': 1016.2,
           'snow': None,
           'tavg': 14.2,
           'tmax': 19.4,
           'tmin': 10.6,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.0},
          {'date': '2024-01-20 00:00:00',
           'prcp': 13.0,
           'pres': 1012.7,
           'snow': None,
           'tavg': 13.9,
           'tmax': 15.0,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 13.0},
          {'date': '2024-01-21 00:00:00',
           'prcp': 1.0,
           'pres': 1012.2,
           'snow': None,
           'tavg': 13.9,
           'tmax': 17.8,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.1},
          {'date': '2024-01-22 00:00:00',
           'prcp': 29.2,
           'pres': 1008.6,
           'snow': None,
           'tavg': 14.1,
           'tmax': 15.0,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 14.0},
          {'date': '2024-01-23 00:00:00',
           'prcp': 0.0,
           'pres': 1012.7,
           'snow': None,
           'tavg': 13.7,
           'tmax': 17.8,
           'tmin': 10.6,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.8},
          {'date': '2024-01-24 00:00:00',
           'prcp': 0.0,
           'pres': 1019.6,
           'snow': None,
           'tavg': 14.6,
           'tmax': 16.7,
           'tmin': 12.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.4},
          {'date': '2024-01-25 00:00:00',
           'prcp': 1.3,
           'pres': 1020.2,
           'snow': None,
           'tavg': 14.6,
           'tmax': 16.1,
           'tmin': 11.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.4},
          {'date': '2024-01-26 00:00:00',
           'prcp': 0.0,
           'pres': 1022.4,
           'snow': None,
           'tavg': 14.1,
           'tmax': 21.1,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 6.5},
          {'date': '2024-01-27 00:00:00',
           'prcp': 0.0,
           'pres': 1021.6,
           'snow': None,
           'tavg': 16.6,
           'tmax': 24.4,
           'tmin': 11.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 7.2},
          {'date': '2024-01-28 00:00:00',
           'prcp': 0.0,
           'pres': 1019.5,
           'snow': None,
           'tavg': 18.2,
           'tmax': 25.6,
           'tmin': 10.6,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 7.6},
          {'date': '2024-01-29 00:00:00',
           'prcp': 0.0,
           'pres': 1018.8,
           'snow': None,
           'tavg': 18.6,
           'tmax': 25.6,
           'tmin': 12.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.4},
          {'date': '2024-01-30 00:00:00',
           'prcp': 0.0,
           'pres': 1017.0,
           'snow': None,
           'tavg': 15.8,
           'tmax': 22.2,
           'tmin': 11.1,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.4},
          {'date': '2024-01-31 00:00:00',
           'prcp': 0.0,
           'pres': 1014.5,
           'snow': None,
           'tavg': 14.4,
           'tmax': 17.8,
           'tmin': 11.1,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.7},
          {'date': '2024-02-01 00:00:00',
           'prcp': 63.2,
           'pres': 1008.3,
           'snow': None,
           'tavg': 12.4,
           'tmax': 15.0,
           'tmin': 9.4,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 18.4},
          {'date': '2024-02-02 00:00:00',
           'prcp': 0.3,
           'pres': 1012.8,
           'snow': None,
           'tavg': 12.9,
           'tmax': 15.6,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 22.7},
          {'date': '2024-02-03 00:00:00',
           'prcp': 2.3,
           'pres': 1016.2,
           'snow': None,
           'tavg': 12.1,
           'tmax': 14.4,
           'tmin': 8.9,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.4},
          {'date': '2024-02-04 00:00:00',
           'prcp': 44.7,
           'pres': 1013.8,
           'snow': None,
           'tavg': 12.2,
           'tmax': 14.4,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 21.6},
          {'date': '2024-02-05 00:00:00',
           'prcp': 65.3,
           'pres': 1010.5,
           'snow': None,
           'tavg': 13.2,
           'tmax': 13.9,
           'tmin': 11.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 11.9},
          {'date': '2024-02-06 00:00:00',
           'prcp': 27.4,
           'pres': 1005.8,
           'snow': None,
           'tavg': 11.8,
           'tmax': 12.2,
           'tmin': 8.9,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 7.9},
          {'date': '2024-02-07 00:00:00',
           'prcp': 4.6,
           'pres': 1011.8,
           'snow': None,
           'tavg': 10.4,
           'tmax': 15.0,
           'tmin': 7.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 19.4},
          {'date': '2024-02-08 00:00:00',
           'prcp': 0.0,
           'pres': 1015.6,
           'snow': None,
           'tavg': 11.4,
           'tmax': 14.4,
           'tmin': 7.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 18.7},
          {'date': '2024-02-09 00:00:00',
           'prcp': 0.3,
           'pres': 1016.9,
           'snow': None,
           'tavg': 11.8,
           'tmax': 15.6,
           'tmin': 8.3,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 14.8},
          {'date': '2024-02-10 00:00:00',
           'prcp': 0.0,
           'pres': 1016.8,
           'snow': None,
           'tavg': 12.9,
           'tmax': 19.4,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 13.0},
          {'date': '2024-02-11 00:00:00',
           'prcp': 0.0,
           'pres': 1021.7,
           'snow': None,
           'tavg': 12.4,
           'tmax': 17.2,
           'tmin': 6.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.7},
          {'date': '2024-02-12 00:00:00',
           'prcp': 0.0,
           'pres': 1019.0,
           'snow': None,
           'tavg': 12.4,
           'tmax': 18.3,
           'tmin': 7.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.8},
          {'date': '2024-02-13 00:00:00',
           'prcp': 0.0,
           'pres': 1016.3,
           'snow': None,
           'tavg': 12.3,
           'tmax': 17.8,
           'tmin': 6.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.4},
          {'date': '2024-02-14 00:00:00',
           'prcp': 0.0,
           'pres': 1020.2,
           'snow': None,
           'tavg': 13.2,
           'tmax': 16.1,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.8},
          {'date': '2024-02-15 00:00:00',
           'prcp': 0.0,
           'pres': 1021.3,
           'snow': None,
           'tavg': 12.9,
           'tmax': 16.7,
           'tmin': 8.9,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 12.2},
          {'date': '2024-02-16 00:00:00',
           'prcp': 0.0,
           'pres': 1019.5,
           'snow': None,
           'tavg': 14.2,
           'tmax': 17.2,
           'tmin': 12.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.1},
          {'date': '2024-02-17 00:00:00',
           'prcp': 0.3,
           'pres': 1018.6,
           'snow': None,
           'tavg': 13.6,
           'tmax': 16.1,
           'tmin': 12.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.7},
          {'date': '2024-02-18 00:00:00',
           'prcp': 0.0,
           'pres': 1017.7,
           'snow': None,
           'tavg': 14.3,
           'tmax': 17.2,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 7.6},
          {'date': '2024-02-19 00:00:00',
           'prcp': 24.4,
           'pres': 1018.3,
           'snow': None,
           'tavg': 14.2,
           'tmax': 14.4,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 14.8},
          {'date': '2024-02-20 00:00:00',
           'prcp': 14.2,
           'pres': 1019.2,
           'snow': None,
           'tavg': 13.4,
           'tmax': 15.0,
           'tmin': 12.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 13.0},
          {'date': '2024-02-21 00:00:00',
           'prcp': 6.4,
           'pres': 1019.6,
           'snow': None,
           'tavg': 14.1,
           'tmax': 16.7,
           'tmin': 11.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 12.6},
          {'date': '2024-02-22 00:00:00',
           'prcp': 0.0,
           'pres': 1022.0,
           'snow': None,
           'tavg': 13.9,
           'tmax': 17.2,
           'tmin': 10.6,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.8},
          {'date': '2024-02-23 00:00:00',
           'prcp': 0.0,
           'pres': 1017.6,
           'snow': None,
           'tavg': 15.7,
           'tmax': 24.4,
           'tmin': 11.1,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.3},
          {'date': '2024-02-24 00:00:00',
           'prcp': 0.0,
           'pres': 1016.7,
           'snow': None,
           'tavg': 17.1,
           'tmax': 24.4,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.4},
          {'date': '2024-02-25 00:00:00',
           'prcp': 0.0,
           'pres': 1017.3,
           'snow': None,
           'tavg': 14.9,
           'tmax': 17.8,
           'tmin': 12.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 10.1},
          {'date': '2024-02-26 00:00:00',
           'prcp': 1.3,
           'pres': 1016.3,
           'snow': None,
           'tavg': 13.9,
           'tmax': 17.2,
           'tmin': 11.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 7.9},
          {'date': '2024-02-27 00:00:00',
           'prcp': 0.0,
           'pres': 1015.4,
           'snow': None,
           'tavg': 13.9,
           'tmax': 16.7,
           'tmin': 11.7,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.3},
          {'date': '2024-02-28 00:00:00',
           'prcp': 0.0,
           'pres': 1016.9,
           'snow': None,
           'tavg': 14.1,
           'tmax': 17.8,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 9.7},
          {'date': '2024-02-29 00:00:00',
           'prcp': 0.0,
           'pres': 1020.7,
           'snow': None,
           'tavg': 14.5,
           'tmax': 16.1,
           'tmin': 13.3,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 12.6},
          {'date': '2024-03-01 00:00:00',
           'prcp': 0.3,
           'pres': 1020.1,
           'snow': None,
           'tavg': 13.8,
           'tmax': 16.7,
           'tmin': 12.2,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 14.0},
          {'date': '2024-03-02 00:00:00',
           'prcp': 5.8,
           'pres': 1016.6,
           'snow': None,
           'tavg': 14.3,
           'tmax': 15.6,
           'tmin': 11.1,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 19.8},
          {'date': '2024-03-03 00:00:00',
           'prcp': 1.8,
           'pres': 1017.1,
           'snow': None,
           'tavg': 12.7,
           'tmax': 16.1,
           'tmin': 9.4,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 17.3},
          {'date': '2024-03-04 00:00:00',
           'prcp': 0.0,
           'pres': 1018.5,
           'snow': None,
           'tavg': 12.8,
           'tmax': 17.2,
           'tmin': 7.8,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 8.6},
          {'date': '2024-03-05 00:00:00',
           'prcp': 0.0,
           'pres': 1017.3,
           'snow': None,
           'tavg': 13.1,
           'tmax': 16.7,
           'tmin': 8.3,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 11.9},
          {'date': '2024-03-06 00:00:00',
           'prcp': 17.0,
           'pres': 1012.6,
           'snow': None,
           'tavg': 12.9,
           'tmax': 16.1,
           'tmin': 10.0,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 11.9},
          {'date': '2024-03-07 00:00:00',
           'prcp': 0.8,
           'pres': 1012.5,
           'snow': None,
           'tavg': 12.7,
           'tmax': 16.7,
           'tmin': 8.9,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 13.0},
          {'date': '2024-03-08 00:00:00',
           'prcp': 0.0,
           'pres': 1019.3,
           'snow': None,
           'tavg': 13.6,
           'tmax': 20.6,
           'tmin': 9.4,
           'tsun': None,
           'wdir': None,
           'wpgt': None,
           'wspd': 12.2},
          {'date': '2024-03-09 00:00:00',

In [36]:
weather_dict

{'extracted_at': [Timestamp('2025-10-28 22:21:16.919358'),
  Timestamp('2025-10-28 22:21:18.113380'),
  Timestamp('2025-10-28 22:21:19.305329')],
 'airport_code': ['JFK', 'MIA', 'LAX'],
 'station_id': ['74486', '72202', '72295'],
 'extracted_data': [{'meta': {'generated': '2025-10-28 13:56:32'},
   'data': [{'date': '2024-01-01 00:00:00',
     'tavg': 5.5,
     'tmin': 1.7,
     'tmax': 8.3,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 10.8,
     'wpgt': None,
     'pres': 1016.9,
     'tsun': None},
    {'date': '2024-01-02 00:00:00',
     'tavg': 2.1,
     'tmin': -2.1,
     'tmax': 5.6,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 15.8,
     'wpgt': None,
     'pres': 1018.1,
     'tsun': None},
    {'date': '2024-01-03 00:00:00',
     'tavg': 3.7,
     'tmin': 0.6,
     'tmax': 7.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 13.7,
     'wpgt': None,
     'pres': 1016.4,
     'tsun': None},
    {'date': '2024-01-04 00:00:00',
     'tavg': 4.6,
     'tmin': -2.1,
     'tmax': 7.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 23.0,
     'wpgt': None,
     'pres': 1016.0,
     'tsun': None},
    {'date': '2024-01-05 00:00:00',
     'tavg': -0.4,
     'tmin': -3.2,
     'tmax': 3.3,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 21.2,
     'wpgt': None,
     'pres': 1024.7,
     'tsun': None},
    {'date': '2024-01-06 00:00:00',
     'tavg': 0.6,
     'tmin': -2.7,
     'tmax': 3.9,
     'prcp': 13.7,
     'snow': 0.0,
     'wdir': None,
     'wspd': 18.0,
     'wpgt': None,
     'pres': 1018.0,
     'tsun': None},
    {'date': '2024-01-07 00:00:00',
     'tavg': 2.8,
     'tmin': 1.7,
     'tmax': 3.9,
     'prcp': 7.1,
     'snow': 0.0,
     'wdir': None,
     'wspd': 25.2,
     'wpgt': None,
     'pres': 1004.9,
     'tsun': None},
    {'date': '2024-01-08 00:00:00',
     'tavg': 3.7,
     'tmin': 0.0,
     'tmax': 7.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 19.8,
     'wpgt': None,
     'pres': 1026.0,
     'tsun': None},
    {'date': '2024-01-09 00:00:00',
     'tavg': 2.9,
     'tmin': -2.1,
     'tmax': 12.2,
     'prcp': 40.4,
     'snow': 0.0,
     'wdir': None,
     'wspd': 26.6,
     'wpgt': None,
     'pres': 1018.2,
     'tsun': None},
    {'date': '2024-01-10 00:00:00',
     'tavg': 9.9,
     'tmin': 6.1,
     'tmax': 12.2,
     'prcp': 7.1,
     'snow': 0.0,
     'wdir': None,
     'wspd': 36.4,
     'wpgt': None,
     'pres': 992.9,
     'tsun': None},
    {'date': '2024-01-11 00:00:00',
     'tavg': 6.4,
     'tmin': 3.9,
     'tmax': 7.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 23.8,
     'wpgt': None,
     'pres': 1010.8,
     'tsun': None},
    {'date': '2024-01-12 00:00:00',
     'tavg': 5.6,
     'tmin': 1.1,
     'tmax': 8.9,
     'prcp': 1.5,
     'snow': 0.0,
     'wdir': None,
     'wspd': 18.4,
     'wpgt': None,
     'pres': 1018.6,
     'tsun': None},
    {'date': '2024-01-13 00:00:00',
     'tavg': 9.4,
     'tmin': 1.7,
     'tmax': 13.3,
     'prcp': 28.7,
     'snow': 0.0,
     'wdir': None,
     'wspd': 36.7,
     'wpgt': None,
     'pres': 995.9,
     'tsun': None},
    {'date': '2024-01-14 00:00:00',
     'tavg': 2.6,
     'tmin': -3.2,
     'tmax': 6.7,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 34.6,
     'wpgt': None,
     'pres': 1012.7,
     'tsun': None},
    {'date': '2024-01-15 00:00:00',
     'tavg': -2.8,
     'tmin': -4.9,
     'tmax': -1.6,
     'prcp': 1.5,
     'snow': 0.0,
     'wdir': None,
     'wspd': 15.1,
     'wpgt': None,
     'pres': 1023.6,
     'tsun': None},
    {'date': '2024-01-16 00:00:00',
     'tavg': -2.1,
     'tmin': -5.5,
     'tmax': 0.0,
     'prcp': 9.1,
     'snow': 5.0,
     'wdir': None,
     'wspd': 23.0,
     'wpgt': None,
     'pres': 1011.8,
     'tsun': None},
    {'date': '2024-01-17 00:00:00',
     'tavg': -5.7,
     'tmin': -7.7,
     'tmax': -4.3,
     'prcp': 0.0,
     'snow': 3.0,
     'wdir': None,
     'wspd': 29.2,
     'wpgt': None,
     'pres': 1015.8,
     'tsun': None},
    {'date': '2024-01-18 00:00:00',
     'tavg': -3.5,
     'tmin': -5.5,
     'tmax': 0.6,
     'prcp': 0.0,
     'snow': 3.0,
     'wdir': None,
     'wspd': 18.4,
     'wpgt': None,
     'pres': 1020.8,
     'tsun': None},
    {'date': '2024-01-19 00:00:00',
     'tavg': -1.1,
     'tmin': -3.8,
     'tmax': 0.6,
     'prcp': 0.3,
     'snow': 0.0,
     'wdir': None,
     'wspd': 17.6,
     'wpgt': None,
     'pres': 1011.0,
     'tsun': None},
    {'date': '2024-01-20 00:00:00',
     'tavg': -5.2,
     'tmin': -7.7,
     'tmax': -3.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 33.5,
     'wpgt': None,
     'pres': 1014.8,
     'tsun': None},
    {'date': '2024-01-21 00:00:00',
     'tavg': -4.8,
     'tmin': -7.1,
     'tmax': 0.0,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 28.8,
     'wpgt': None,
     'pres': 1026.4,
     'tsun': None},
    {'date': '2024-01-22 00:00:00',
     'tavg': -2.1,
     'tmin': -5.5,
     'tmax': 2.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 20.2,
     'wpgt': None,
     'pres': 1033.6,
     'tsun': None},
    {'date': '2024-01-23 00:00:00',
     'tavg': 2.0,
     'tmin': 0.0,
     'tmax': 4.4,
     'prcp': 0.3,
     'snow': 0.0,
     'wdir': None,
     'wspd': 12.2,
     'wpgt': None,
     'pres': 1032.6,
     'tsun': None},
    {'date': '2024-01-24 00:00:00',
     'tavg': 4.1,
     'tmin': 2.2,
     'tmax': 7.2,
     'prcp': 2.3,
     'snow': 0.0,
     'wdir': None,
     'wspd': 8.6,
     'wpgt': None,
     'pres': 1031.3,
     'tsun': None},
    {'date': '2024-01-25 00:00:00',
     'tavg': 8.4,
     'tmin': 6.1,
     'tmax': 12.8,
     'prcp': 6.9,
     'snow': 0.0,
     'wdir': None,
     'wspd': 9.7,
     'wpgt': None,
     'pres': 1020.9,
     'tsun': None},
    {'date': '2024-01-26 00:00:00',
     'tavg': 7.1,
     'tmin': 5.0,
     'tmax': 7.8,
     'prcp': 5.3,
     'snow': 0.0,
     'wdir': None,
     'wspd': 13.0,
     'wpgt': None,
     'pres': 1018.3,
     'tsun': None},
    {'date': '2024-01-27 00:00:00',
     'tavg': 6.1,
     'tmin': 5.0,
     'tmax': 8.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 8.6,
     'wpgt': None,
     'pres': 1022.2,
     'tsun': None},
    {'date': '2024-01-28 00:00:00',
     'tavg': 4.4,
     'tmin': 2.8,
     'tmax': 5.0,
     'prcp': 23.4,
     'snow': 0.0,
     'wdir': None,
     'wspd': 22.0,
     'wpgt': None,
     'pres': 1010.1,
     'tsun': None},
    {'date': '2024-01-29 00:00:00',
     'tavg': 2.9,
     'tmin': 1.7,
     'tmax': 4.4,
     'prcp': 0.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 25.6,
     'wpgt': None,
     'pres': 1010.4,
     'tsun': None},
    {'date': '2024-01-30 00:00:00',
     'tavg': 2.2,
     'tmin': 1.1,
     'tmax': 3.3,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 12.6,
     'wpgt': None,
     'pres': 1022.4,
     'tsun': None},
    {'date': '2024-01-31 00:00:00',
     'tavg': 2.3,
     'tmin': 1.1,
     'tmax': 3.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 11.5,
     'wpgt': None,
     'pres': 1020.4,
     'tsun': None},
    {'date': '2024-02-01 00:00:00',
     'tavg': 3.4,
     'tmin': 0.0,
     'tmax': 6.7,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 11.9,
     'wpgt': None,
     'pres': 1016.0,
     'tsun': None},
    {'date': '2024-02-02 00:00:00',
     'tavg': 5.1,
     'tmin': 2.8,
     'tmax': 5.6,
     'prcp': 4.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 13.7,
     'wpgt': None,
     'pres': 1012.2,
     'tsun': None},
    {'date': '2024-02-03 00:00:00',
     'tavg': 2.8,
     'tmin': 0.0,
     'tmax': 6.1,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 22.7,
     'wpgt': None,
     'pres': 1017.1,
     'tsun': None},
    {'date': '2024-02-04 00:00:00',
     'tavg': 2.7,
     'tmin': -1.0,
     'tmax': 7.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 17.3,
     'wpgt': None,
     'pres': 1015.6,
     'tsun': None},
    {'date': '2024-02-05 00:00:00',
     'tavg': 2.9,
     'tmin': -1.0,
     'tmax': 7.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 20.5,
     'wpgt': None,
     'pres': 1014.1,
     'tsun': None},
    {'date': '2024-02-06 00:00:00',
     'tavg': 1.2,
     'tmin': -2.7,
     'tmax': 5.6,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 16.9,
     'wpgt': None,
     'pres': 1021.6,
     'tsun': None},
    {'date': '2024-02-07 00:00:00',
     'tavg': 2.8,
     'tmin': -1.6,
     'tmax': 8.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1025.6,
     'tsun': None},
    {'date': '2024-02-08 00:00:00',
     'tavg': 4.3,
     'tmin': 0.0,
     'tmax': 8.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1026.0,
     'tsun': None},
    {'date': '2024-02-09 00:00:00',
     'tavg': 6.2,
     'tmin': 3.3,
     'tmax': 9.4,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 15.8,
     'wpgt': None,
     'pres': 1019.7,
     'tsun': None},
    {'date': '2024-02-10 00:00:00',
     'tavg': 6.6,
     'tmin': 2.2,
     'tmax': 12.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 10.8,
     'wpgt': None,
     'pres': 1011.4,
     'tsun': None},
    {'date': '2024-02-11 00:00:00',
     'tavg': 8.8,
     'tmin': 6.1,
     'tmax': 10.6,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 15.5,
     'wpgt': None,
     'pres': 1012.7,
     'tsun': None},
    {'date': '2024-02-12 00:00:00',
     'tavg': 5.3,
     'tmin': 2.2,
     'tmax': 7.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 10.8,
     'wpgt': None,
     'pres': 1012.3,
     'tsun': None},
    {'date': '2024-02-13 00:00:00',
     'tavg': 2.3,
     'tmin': 0.0,
     'tmax': 3.9,
     'prcp': 16.5,
     'snow': 0.0,
     'wdir': None,
     'wspd': 23.4,
     'wpgt': None,
     'pres': 1003.2,
     'tsun': None},
    {'date': '2024-02-14 00:00:00',
     'tavg': 1.1,
     'tmin': -2.1,
     'tmax': 3.3,
     'prcp': 0.0,
     'snow': 5.0,
     'wdir': None,
     'wspd': 37.4,
     'wpgt': None,
     'pres': 1015.7,
     'tsun': None},
    {'date': '2024-02-15 00:00:00',
     'tavg': -0.8,
     'tmin': -3.2,
     'tmax': 2.2,
     'prcp': 0.0,
     'snow': 3.0,
     'wdir': None,
     'wspd': 20.2,
     'wpgt': None,
     'pres': 1018.5,
     'tsun': None},
    {'date': '2024-02-16 00:00:00',
     'tavg': 3.1,
     'tmin': 1.1,
     'tmax': 6.1,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 24.5,
     'wpgt': None,
     'pres': 1011.3,
     'tsun': None},
    {'date': '2024-02-17 00:00:00',
     'tavg': 0.4,
     'tmin': -3.2,
     'tmax': 2.2,
     'prcp': 8.4,
     'snow': 15.0,
     'wdir': None,
     'wspd': 18.4,
     'wpgt': None,
     'pres': 1009.7,
     'tsun': None},
    {'date': '2024-02-18 00:00:00',
     'tavg': -0.9,
     'tmin': -3.8,
     'tmax': 4.4,
     'prcp': 0.0,
     'snow': 8.0,
     'wdir': None,
     'wspd': 28.1,
     'wpgt': None,
     'pres': 1012.2,
     'tsun': None},
    {'date': '2024-02-19 00:00:00',
     'tavg': 2.2,
     'tmin': -1.6,
     'tmax': 5.0,
     'prcp': 0.0,
     'snow': 3.0,
     'wdir': None,
     'wspd': 17.3,
     'wpgt': None,
     'pres': 1020.8,
     'tsun': None},
    {'date': '2024-02-20 00:00:00',
     'tavg': -0.4,
     'tmin': -3.8,
     'tmax': 2.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 12.2,
     'wpgt': None,
     'pres': 1031.9,
     'tsun': None},
    {'date': '2024-02-21 00:00:00',
     'tavg': -0.2,
     'tmin': -4.3,
     'tmax': 3.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 12.2,
     'wpgt': None,
     'pres': 1030.5,
     'tsun': None},
    {'date': '2024-02-22 00:00:00',
     'tavg': 2.6,
     'tmin': 0.6,
     'tmax': 5.0,
     'prcp': 1.3,
     'snow': 0.0,
     'wdir': None,
     'wspd': 13.7,
     'wpgt': None,
     'pres': 1016.3,
     'tsun': None},
    {'date': '2024-02-23 00:00:00',
     'tavg': 6.2,
     'tmin': 4.4,
     'tmax': 8.9,
     'prcp': 1.3,
     'snow': 0.0,
     'wdir': None,
     'wspd': 11.9,
     'wpgt': None,
     'pres': 999.6,
     'tsun': None},
    {'date': '2024-02-24 00:00:00',
     'tavg': 5.7,
     'tmin': -2.1,
     'tmax': 7.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 22.7,
     'wpgt': None,
     'pres': 1005.2,
     'tsun': None},
    {'date': '2024-02-25 00:00:00',
     'tavg': -1.3,
     'tmin': -6.0,
     'tmax': 2.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 16.9,
     'wpgt': None,
     'pres': 1020.2,
     'tsun': None},
    {'date': '2024-02-26 00:00:00',
     'tavg': 3.5,
     'tmin': 0.0,
     'tmax': 8.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 14.0,
     'wpgt': None,
     'pres': 1018.0,
     'tsun': None},
    {'date': '2024-02-27 00:00:00',
     'tavg': 6.0,
     'tmin': 1.1,
     'tmax': 11.1,
     'prcp': 8.4,
     'snow': 0.0,
     'wdir': None,
     'wspd': 20.2,
     'wpgt': None,
     'pres': 1015.6,
     'tsun': None},
    {'date': '2024-02-28 00:00:00',
     'tavg': 9.1,
     'tmin': 6.7,
     'tmax': 13.3,
     'prcp': 2.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 35.3,
     'wpgt': None,
     'pres': 1005.8,
     'tsun': None},
    {'date': '2024-02-29 00:00:00',
     'tavg': 3.9,
     'tmin': -0.5,
     'tmax': 6.7,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 30.6,
     'wpgt': None,
     'pres': 1023.2,
     'tsun': None},
    {'date': '2024-03-01 00:00:00',
     'tavg': 1.9,
     'tmin': -2.1,
     'tmax': 5.0,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 16.9,
     'wpgt': None,
     'pres': 1035.7,
     'tsun': None},
    {'date': '2024-03-02 00:00:00',
     'tavg': 6.8,
     'tmin': 5.0,
     'tmax': 11.7,
     'prcp': 36.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 18.0,
     'wpgt': None,
     'pres': 1025.9,
     'tsun': None},
    {'date': '2024-03-03 00:00:00',
     'tavg': 11.7,
     'tmin': 8.3,
     'tmax': 20.0,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 16.6,
     'wpgt': None,
     'pres': 1021.2,
     'tsun': None},
    {'date': '2024-03-04 00:00:00',
     'tavg': 10.1,
     'tmin': 5.6,
     'tmax': 12.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 16.9,
     'wpgt': None,
     'pres': 1027.9,
     'tsun': None},
    {'date': '2024-03-05 00:00:00',
     'tavg': 6.9,
     'tmin': 5.6,
     'tmax': 8.9,
     'prcp': 10.7,
     'snow': 0.0,
     'wdir': None,
     'wspd': 17.6,
     'wpgt': None,
     'pres': 1021.0,
     'tsun': None},
    {'date': '2024-03-06 00:00:00',
     'tavg': 8.0,
     'tmin': 7.2,
     'tmax': 10.6,
     'prcp': 47.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 11.5,
     'wpgt': None,
     'pres': 1015.4,
     'tsun': None},
    {'date': '2024-03-07 00:00:00',
     'tavg': 10.1,
     'tmin': 6.7,
     'tmax': 12.8,
     'prcp': 3.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 25.6,
     'wpgt': None,
     'pres': 1011.5,
     'tsun': None},
    {'date': '2024-03-08 00:00:00',
     'tavg': 7.4,
     'tmin': 3.9,
     'tmax': 18.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 16.9,
     'wpgt': None,
     'pres': 1025.2,
     'tsun': None},
    {'date': '2024-03-09 00:00:00',
     'tavg': 5.6,
     'tmin': 4.4,
     'tmax': 9.4,
     'prcp': 43.2,
     'snow': 0.0,
     'wdir': None,
     'wspd': 27.7,
     'wpgt': None,
     'pres': 1017.4,
     'tsun': None},
    {'date': '2024-03-10 00:00:00',
     'tavg': 7.8,
     'tmin': 2.8,
     'tmax': 11.7,
     'prcp': 0.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 31.3,
     'wpgt': None,
     'pres': 996.4,
     'tsun': None},
    {'date': '2024-03-11 00:00:00',
     'tavg': 5.9,
     'tmin': 1.7,
     'tmax': 11.7,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 42.8,
     'wpgt': None,
     'pres': 1004.0,
     'tsun': None},
    {'date': '2024-03-12 00:00:00',
     'tavg': 11.0,
     'tmin': 5.0,
     'tmax': 19.4,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 21.6,
     'wpgt': None,
     'pres': 1009.8,
     'tsun': None},
    {'date': '2024-03-13 00:00:00',
     'tavg': 10.6,
     'tmin': 5.0,
     'tmax': 13.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 9.7,
     'wpgt': None,
     'pres': 1013.2,
     'tsun': None},
    {'date': '2024-03-14 00:00:00',
     'tavg': 9.9,
     'tmin': 5.0,
     'tmax': 18.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 9.7,
     'wpgt': None,
     'pres': 1015.9,
     'tsun': None},
    {'date': '2024-03-15 00:00:00',
     'tavg': 14.2,
     'tmin': 9.4,
     'tmax': 22.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 18.0,
     'wpgt': None,
     'pres': 1007.2,
     'tsun': None},
    {'date': '2024-03-16 00:00:00',
     'tavg': 10.5,
     'tmin': 6.1,
     'tmax': 12.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 18.0,
     'wpgt': None,
     'pres': 1009.5,
     'tsun': None},
    {'date': '2024-03-17 00:00:00',
     'tavg': 11.7,
     'tmin': 8.3,
     'tmax': 17.2,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 22.0,
     'wpgt': None,
     'pres': 1002.7,
     'tsun': None},
    {'date': '2024-03-18 00:00:00',
     'tavg': 9.3,
     'tmin': 3.3,
     'tmax': 11.7,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 23.8,
     'wpgt': None,
     'pres': 1006.0,
     'tsun': None},
    {'date': '2024-03-19 00:00:00',
     'tavg': 4.9,
     'tmin': 1.7,
     'tmax': 8.9,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 26.3,
     'wpgt': None,
     'pres': 1007.5,
     'tsun': None},
    {'date': '2024-03-20 00:00:00',
     'tavg': 7.3,
     'tmin': 1.1,
     'tmax': 11.7,
     'prcp': 0.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 23.8,
     'wpgt': None,
     'pres': 1005.2,
     'tsun': None},
    {'date': '2024-03-21 00:00:00',
     'tavg': 2.6,
     'tmin': -1.0,
     'tmax': 6.7,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 31.0,
     'wpgt': None,
     'pres': 1018.7,
     'tsun': None},
    {'date': '2024-03-22 00:00:00',
     'tavg': 1.2,
     'tmin': -2.1,
     'tmax': 5.0,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 15.5,
     'wpgt': None,
     'pres': 1027.9,
     'tsun': None},
    {'date': '2024-03-23 00:00:00',
     'tavg': 7.2,
     'tmin': 1.7,
     'tmax': 11.1,
     'prcp': 79.5,
     'snow': 0.0,
     'wdir': None,
     'wspd': 27.0,
     'wpgt': None,
     'pres': 1011.8,
     'tsun': None},
    {'date': '2024-03-24 00:00:00',
     'tavg': 3.6,
     'tmin': -0.5,
     'tmax': 7.8,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 25.6,
     'wpgt': None,
     'pres': 1022.9,
     'tsun': None},
    {'date': '2024-03-25 00:00:00',
     'tavg': 5.1,
     'tmin': 1.1,
     'tmax': 11.1,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 20.5,
     'wpgt': None,
     'pres': 1030.0,
     'tsun': None},
    {'date': '2024-03-26 00:00:00',
     'tavg': 6.3,
     'tmin': 3.3,
     'tmax': 9.4,
     'prcp': 0.0,
     'snow': 0.0,
     'wdir': None,
     'wspd': 16.2,
     'wpgt': None,
     'pres': 1023.2,
     'tsun': None},
    {'date': '2024-03-27 00:00:00',
     'tavg': 6.7,
     'tmin': 4.4,
     'tmax': 10.0,
     'prcp': 2.8,
     'snow': 0.0,
     'wdir': None,
     'wspd': 8.6,
     'wpgt': None,
     'pres': 1019.5,
     'tsun': None},
    {'date': '2024-03-28 00:00:00',
     'tavg': 8.6,
     'tmin': 6.7,
     'tmax': 9.4,
     'prcp': 24.4,

## Preview the Extracted Data

In [7]:
# transform weather dict into a pandas dataframe:
weather_daily_df = pd.DataFrame(weather_dict)
weather_daily_df

,extracted_at,airport_code,station_id,extracted_data
0,2025-10-28 22:21:16.919358,JFK,74486,"{'meta': {'generated': '2025-10-28 13:56:32'},..."
1,2025-10-28 22:21:18.113380,MIA,72202,"{'meta': {'generated': '2025-10-28 12:21:52'},..."
2,2025-10-28 22:21:19.305329,LAX,72295,"{'meta': {'generated': '2025-10-28 12:21:54'},..."

Each row corresponds to:

- one API call

- one airport

- one JSON payload containing the weather data

⚠️ We’re not cleaning or flattening the JSON yet — that’s for the Transform step.

## 5. Load the Raw JSON into the Database

We’ll store it as raw data (no transformations yet).

Each record = one JSON blob.

Now all we need to create a table in your Schema in our database is part of the `weather_daily_df` dataframe.  
We can use pandas' ability to work with SQLAlchemy and "save" the data to the DB using the `.to_sql()` method

In [8]:
# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# creating the engine
engine = create_engine(url, echo=False)

In [9]:
engine.url # checking the url (pass is hidden)

postgresql://jingwang:***@data-analytics-course-2.c8g8r1deus2v.eu-central-1.rds.amazonaws.com:5432/nf_180825

In [10]:
# defining data types for the DB
dtype_dict = {
    'extracted_at':types.DateTime,
    'airport_code': types.String,
    'station_id': types.Integer,
    'extracted_data':postgres_json
             }

In [11]:
weather_daily_df.dtypes

extracted_at      datetime64[ns]
airport_code              object
station_id                object
extracted_data            object
dtype: object

In [12]:
weather_daily_df['extracted_at'] = pd.to_datetime(weather_daily_df['extracted_at'], errors='coerce')

In [13]:
weather_daily_df.dtypes

extracted_at      datetime64[ns]
airport_code              object
station_id                object
extracted_data            object
dtype: object

In [14]:
weather_daily_df['airport_code'] = weather_daily_df['airport_code'].astype('string')

In [15]:
weather_daily_df.dtypes

extracted_at      datetime64[ns]
airport_code      string[python]
station_id                object
extracted_data            object
dtype: object

In [16]:
weather_daily_df['station_id'] = weather_daily_df['station_id'].astype('int')

In [17]:
weather_daily_df.dtypes

extracted_at      datetime64[ns]
airport_code      string[python]
station_id                 int64
extracted_data            object
dtype: object

In [59]:
# writing dataframe to DB : Pandas Dataframe to DB Table in my own Schema
weather_daily_df.to_sql(name = 'weather_daily_raw', 
                       con = engine, 
                       schema = pg_schema, # pandas is allowing to specify, in which schema the table shall be created
                       if_exists='replace', 
                       dtype=dtype_dict,
                       index=False
                      )

#Pandas + SQLAlchemy will explicitly qualify the table name with the schema:

3

## Tests: not from the lecture

### Version 1: Using schema parameter in to_sql

In [79]:
# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# let's switch the logging off again. .
engine = create_engine(url, echo=False)

# writing dataframe to DB : Pandas Dataframe to DB Table in my own Schema
weather_daily_df.to_sql(name = 'weather_daily_test_1', 
                       con = engine, 
                       schema = pg_schema, # pandas is allowing to specify, in which schema the table shall be created
                       if_exists='replace', 
                       dtype=dtype_dict,
                       index=False
                      )

#Pandas + SQLAlchemy will explicitly qualify the table name with the schema: schema = pg_schema

3

In [ ]:
# Pandas + SQLAlchemy explicitly qualifies the table name with the schema:
# → "my_schema.weather_daily_test"
# The CREATE TABLE and all subsequent SQL statements include the schema-qualified name.
# The search_path (default schema) is not modified — everything is explicit.
# This is the cleanest, most direct way to specify schema in Pandas.

### Version 2: Using SET search_path

In [ ]:
#DISCUSSION

# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}' #the same like version 1

# let's switch the logging off again. .
engine = create_engine(url, echo=False) #the same like version 1

my_schema = pg_schema 

with engine.begin() as conn:
    conn.execute(text(f'SET search_path TO {my_schema};')) #connect to my own schema in postgresql, if i dont set it, the default schema is public

    weather_daily_df.to_sql(
        'weather_daily_test_2',
        con=conn, #different from the version 1: con=engine
        if_exists='replace',
        dtype=dtype_dict,
        index=False
    )

#I am telling PostgreSQL that for this connection, treat {my_schema} as the default schema instead of public schema

In [84]:
# You don’t pass a schema to Pandas.
# Instead, you change the database session’s search_path, which tells PostgreSQL to treat that schema as the default one.
# Then to_sql creates "weather_daily_test" in whatever schema is first in the search path (here: my_schema).

In [58]:
# Stick to schema=pg_schema in .to_sql() — it’s clean, explicit, and avoids per-session SQL commands like SET search_path.
# Use SET search_path only if:
# You’ll run multiple queries without schema-qualified names, and
# You control the connection lifetime (e.g., a long-lived session).

## summary:

In [ ]:
# | Aspect                     | Version 1 (`schema=pg_schema`) | Version 2 (`SET search_path`)                     |
# | -------------------------- | ------------------------------ | ------------------------------------------------- |
# | Schema handling            | Explicit, SQLAlchemy-qualified | Implicit, via session config                      |
# | Affected session           | No                             | Yes (search_path changed for that connection)     |
# | More portable              | ✅ Yes                          | ❌ No (depends on DB session state)                |
# | Recommended for production | ✅ Yes                          | ⚠️ Only if you control session settings carefully |

## 6. Query & Load Data from SQL into Pandas🔧✏️📚

### Create a database connection

In [38]:
from sqlalchemy import text # to be able to pass string

### Connection string:

In [40]:
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

### Create an ``engine``:

In [41]:
engine = create_engine(url, echo=False)

### Schema:

In [42]:
my_schema = 's_jingwang' # update it to your schema

with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {my_schema};'))

✅ You should see an output showing the number of rows written (should be 3).

Now check in DBeaver — you should see a new table:
`your_schema.weather_daily_raw`

### Read data from SQL in Pandas

In [43]:
weather_daily_raw= pd.read_sql('SELECT * FROM weather_daily_raw;', con=engine)
weather_daily_raw.head()

,extracted_at,airport_code,station_id,extracted_data
0,2025-10-28 22:21:16.919358,JFK,74486,"{'meta': {'generated': '2025-10-28 13:56:32'},..."
1,2025-10-28 22:21:18.113380,MIA,72202,"{'meta': {'generated': '2025-10-28 12:21:52'},..."
2,2025-10-28 22:21:19.305329,LAX,72295,"{'meta': {'generated': '2025-10-28 12:21:54'},..."

### Run queries:

In [47]:
# extract only airport_code, station_id and extracted_data from the table of weather daily raw.
query_weather_daily_raw= '''
SELECT 
    airport_code,
    station_id,
    extracted_data
FROM weather_daily_raw
'''

In [49]:
weather_daily_raw_filtered = pd.read_sql(query_weather_daily_raw, con=engine)
weather_daily_raw_filtered.index += 1
weather_daily_raw_filtered

  airport_code  station_id                                     extracted_data
1          JFK       74486  {'meta': {'generated': '2025-10-28 13:56:32'},...
2          MIA       72202  {'meta': {'generated': '2025-10-28 12:21:52'},...
3          LAX       72295  {'meta': {'generated': '2025-10-28 12:21:54'},...

-----------

## 💭 Wrap-up: What You Just Did

✅ You’ve completed the Extract and Load stages of a real-world ELT pipeline.

| Step    | Description                     | Tool                  |
| ------- | ------------------------------- | --------------------- |
| Extract | Called external API (Meteostat) | `requests`            |
| Load    | Saved raw JSON to PostgreSQL    | `pandas + SQLAlchemy` |


## 🚀 Next Steps (Transformation Preview)

In the next chapters, you’ll:

- Flatten the JSON data.

- Create structured tables (e.g. daily temperature, precipitation).

- Link it with flight data for analysis.

------------

## For the Curious: Quick Peek at the JSON Structure
Not part of the pipeline — just exploration

In [19]:
weather_daily_df['extracted_data']

0    {'meta': {'generated': '2025-10-28 13:56:32'},...
1    {'meta': {'generated': '2025-10-28 12:21:52'},...
2    {'meta': {'generated': '2025-10-28 12:21:54'},...
Name: extracted_data, dtype: object

In [20]:
sample_jfk = weather_daily_df['extracted_data'][0] #all data from the first airport:JFK, we can see that we have meta and data
print(json.dumps(sample_jfk, indent=2)[:1000])

{
  "meta": {
    "generated": "2025-10-28 13:56:32"
  },
  "data": [
    {
      "date": "2024-01-01 00:00:00",
      "tavg": 5.5,
      "tmin": 1.7,
      "tmax": 8.3,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 10.8,
      "wpgt": null,
      "pres": 1016.9,
      "tsun": null
    },
    {
      "date": "2024-01-02 00:00:00",
      "tavg": 2.1,
      "tmin": -2.1,
      "tmax": 5.6,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 15.8,
      "wpgt": null,
      "pres": 1018.1,
      "tsun": null
    },
    {
      "date": "2024-01-03 00:00:00",
      "tavg": 3.7,
      "tmin": 0.6,
      "tmax": 7.2,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 13.7,
      "wpgt": null,
      "pres": 1016.4,
      "tsun": null
    },
    {
      "date": "2024-01-04 00:00:00",
      "tavg": 4.6,
      "tmin": -2.1,
      "tmax": 7.8,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 23.0,
      "wpgt"

In [21]:
pd.json_normalize(sample_jfk)

                                                data       meta.generated
0  [{'date': '2024-01-01 00:00:00', 'tavg': 5.5, ...  2025-10-28 13:56:32

In [22]:
pd.json_normalize(weather_daily_df['extracted_data']).loc[0, 'data'] #extract only data from the json data of first airport:JFK

[{'date': '2024-01-01 00:00:00',
  'tavg': 5.5,
  'tmin': 1.7,
  'tmax': 8.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1016.9,
  'tsun': None},
 {'date': '2024-01-02 00:00:00',
  'tavg': 2.1,
  'tmin': -2.1,
  'tmax': 5.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.8,
  'wpgt': None,
  'pres': 1018.1,
  'tsun': None},
 {'date': '2024-01-03 00:00:00',
  'tavg': 3.7,
  'tmin': 0.6,
  'tmax': 7.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.7,
  'wpgt': None,
  'pres': 1016.4,
  'tsun': None},
 {'date': '2024-01-04 00:00:00',
  'tavg': 4.6,
  'tmin': -2.1,
  'tmax': 7.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 23.0,
  'wpgt': None,
  'pres': 1016.0,
  'tsun': None},
 {'date': '2024-01-05 00:00:00',
  'tavg': -0.4,
  'tmin': -3.2,
  'tmax': 3.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 21.2,
  'wpgt': None,
  'pres': 1024.7,
  'tsun': None},
 {'date': '2024-01-06 00:00:00',
  'tavg': 0.6,
  'tmin': -2.7,
  'tmax': 3.9,
  'prcp': 13.7,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.0,
  'wpgt': None,
  'pres': 1018.0,
  'tsun': None},
 {'date': '2024-01-07 00:00:00',
  'tavg': 2.8,
  'tmin': 1.7,
  'tmax': 3.9,
  'prcp': 7.1,
  'snow': 0.0,
  'wdir': None,
  'wspd': 25.2,
  'wpgt': None,
  'pres': 1004.9,
  'tsun': None},
 {'date': '2024-01-08 00:00:00',
  'tavg': 3.7,
  'tmin': 0.0,
  'tmax': 7.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 19.8,
  'wpgt': None,
  'pres': 1026.0,
  'tsun': None},
 {'date': '2024-01-09 00:00:00',
  'tavg': 2.9,
  'tmin': -2.1,
  'tmax': 12.2,
  'prcp': 40.4,
  'snow': 0.0,
  'wdir': None,
  'wspd': 26.6,
  'wpgt': None,
  'pres': 1018.2,
  'tsun': None},
 {'date': '2024-01-10 00:00:00',
  'tavg': 9.9,
  'tmin': 6.1,
  'tmax': 12.2,
  'prcp': 7.1,
  'snow': 0.0,
  'wdir': None,
  'wspd': 36.4,
  'wpgt': None,
  'pres': 992.9,
  'tsun': None},
 {'date': '2024-01-11 00:00:00',
  'tavg': 6.4,
  'tmin': 3.9,
  'tmax': 7.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 23.8,
  'wpgt': None,
  'pres': 1010.8,
  'tsun': None},
 {'date': '2024-01-12 00:00:00',
  'tavg': 5.6,
  'tmin': 1.1,
  'tmax': 8.9,
  'prcp': 1.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.4,
  'wpgt': None,
  'pres': 1018.6,
  'tsun': None},
 {'date': '2024-01-13 00:00:00',
  'tavg': 9.4,
  'tmin': 1.7,
  'tmax': 13.3,
  'prcp': 28.7,
  'snow': 0.0,
  'wdir': None,
  'wspd': 36.7,
  'wpgt': None,
  'pres': 995.9,
  'tsun': None},
 {'date': '2024-01-14 00:00:00',
  'tavg': 2.6,
  'tmin': -3.2,
  'tmax': 6.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 34.6,
  'wpgt': None,
  'pres': 1012.7,
  'tsun': None},
 {'date': '2024-01-15 00:00:00',
  'tavg': -2.8,
  'tmin': -4.9,
  'tmax': -1.6,
  'prcp': 1.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.1,
  'wpgt': None,
  'pres': 1023.6,
  'tsun': None},
 {'date': '2024-01-16 00:00:00',
  'tavg': -2.1,
  'tmin': -5.5,
  'tmax': 0.0,
  'prcp': 9.1,
  'snow': 5.0,
  'wdir': None,
  'wspd': 23.0,
  'wpgt': None,
  'pres': 1011.8,
  'tsun': None},
 {'date': '2024-01-17 00:00:00',
  'tavg': -5.7,
  'tmin': -7.7,
  'tmax': -4.3,
  'prcp': 0.0,
  'snow': 3.0,
  'wdir': None,
  'wspd': 29.2,
  'wpgt': None,
  'pres': 1015.8,
  'tsun': None},
 {'date': '2024-01-18 00:00:00',
  'tavg': -3.5,
  'tmin': -5.5,
  'tmax': 0.6,
  'prcp': 0.0,
  'snow': 3.0,
  'wdir': None,
  'wspd': 18.4,
  'wpgt': None,
  'pres': 1020.8,
  'tsun': None},
 {'date': '2024-01-19 00:00:00',
  'tavg': -1.1,
  'tmin': -3.8,
  'tmax': 0.6,
  'prcp': 0.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 17.6,
  'wpgt': None,
  'pres': 1011.0,
  'tsun': None},
 {'date': '2024-01-20 00:00:00',
  'tavg': -5.2,
  'tmin': -7.7,
  'tmax': -3.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 33.5,
  'wpgt': None,
  'pres': 1014.8,
  'tsun': None},
 {'date': '2024-01-21 00:00:00',
  'tavg': -4.8,
  'tmin': -7.1,
  'tmax': 0.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 28.8,
  'wpgt': None,
  'pres': 1026.4,
  'tsun': None},
 {'date': '2024-01-22 00:00:00',
  'tavg': -2.1,
  'tmin': -5.5,
  'tmax': 2.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 20.2,
  'wpgt': None,
  'pres': 1033.6,
  'tsun': None},
 {'date': '2024-01-23 00:00:00',
  'tavg': 2.0,
  'tmin': 0.0,
  'tmax': 4.4,
  'prcp': 0.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1032.6,
  'tsun': None},
 {'date': '2024-01-24 00:00:00',
  'tavg': 4.1,
  'tmin': 2.2,
  'tmax': 7.2,
  'prcp': 2.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1031.3,
  'tsun': None},
 {'date': '2024-01-25 00:00:00',
  'tavg': 8.4,
  'tmin': 6.1,
  'tmax': 12.8,
  'prcp': 6.9,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1020.9,
  'tsun': None},
 {'date': '2024-01-26 00:00:00',
  'tavg': 7.1,
  'tmin': 5.0,
  'tmax': 7.8,
  'prcp': 5.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.0,
  'wpgt': None,
  'pres': 1018.3,
  'tsun': None},
 {'date': '2024-01-27 00:00:00',
  'tavg': 6.1,
  'tmin': 5.0,
  'tmax': 8.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1022.2,
  'tsun': None},
 {'date': '2024-01-28 00:00:00',
  'tavg': 4.4,
  'tmin': 2.8,
  'tmax': 5.0,
  'prcp': 23.4,
  'snow': 0.0,
  'wdir': None,
  'wspd': 22.0,
  'wpgt': None,
  'pres': 1010.1,
  'tsun': None},
 {'date': '2024-01-29 00:00:00',
  'tavg': 2.9,
  'tmin': 1.7,
  'tmax': 4.4,
  'prcp': 0.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 25.6,
  'wpgt': None,
  'pres': 1010.4,
  'tsun': None},
 {'date': '2024-01-30 00:00:00',
  'tavg': 2.2,
  'tmin': 1.1,
  'tmax': 3.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1022.4,
  'tsun': None},
 {'date': '2024-01-31 00:00:00',
  'tavg': 2.3,
  'tmin': 1.1,
  'tmax': 3.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.5,
  'wpgt': None,
  'pres': 1020.4,
  'tsun': None},
 {'date': '2024-02-01 00:00:00',
  'tavg': 3.4,
  'tmin': 0.0,
  'tmax': 6.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 1016.0,
  'tsun': None},
 {'date': '2024-02-02 00:00:00',
  'tavg': 5.1,
  'tmin': 2.8,
  'tmax': 5.6,
  'prcp': 4.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.7,
  'wpgt': None,
  'pres': 1012.2,
  'tsun': None},
 {'date': '2024-02-03 00:00:00',
  'tavg': 2.8,
  'tmin': 0.0,
  'tmax': 6.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 22.7,
  'wpgt': None,
  'pres': 1017.1,
  'tsun': None},
 {'date': '2024-02-04 00:00:00',
  'tavg': 2.7,
  'tmin': -1.0,
  'tmax': 7.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 17.3,
  'wpgt': None,
  'pres': 1015.6,
  'tsun': None},
 {'date': '2024-02-05 00:00:00',
  'tavg': 2.9,
  'tmin': -1.0,
  'tmax': 7.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 20.5,
  'wpgt': None,
  'pres': 1014.1,
  'tsun': None},
 {'date': '2024-02-06 00:00:00',
  'tavg': 1.2,
  'tmin': -2.7,
  'tmax': 5.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.9,
  'wpgt': None,
  'pres': 1021.6,
  'tsun': None},
 {'date': '2024-02-07 00:00:00',
  'tavg': 2.8,
  'tmin': -1.6,
  'tmax': 8.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.2,
  'wpgt': None,
  'pres': 1025.6,
  'tsun': None},
 {'date': '2024-02-08 00:00:00',
  'tavg': 4.3,
  'tmin': 0.0,
  'tmax': 8.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1026.0,
  'tsun': None},
 {'date': '2024-02-09 00:00:00',
  'tavg': 6.2,
  'tmin': 3.3,
  'tmax': 9.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.8,
  'wpgt': None,
  'pres': 1019.7,
  'tsun': None},
 {'date': '2024-02-10 00:00:00',
  'tavg': 6.6,
  'tmin': 2.2,
  'tmax': 12.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1011.4,
  'tsun': None},
 {'date': '2024-02-11 00:00:00',
  'tavg': 8.8,
  'tmin': 6.1,
  'tmax': 10.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.5,
  'wpgt': None,
  'pres': 1012.7,
  'tsun': None},
 {'date': '2024-02-12 00:00:00',
  'tavg': 5.3,
  'tmin': 2.2,
  'tmax': 7.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1012.3,
  'tsun': None},
 {'date': '2024-02-13 00:00:00',
  'tavg': 2.3,
  'tmin': 0.0,
  'tmax': 3.9,
  'prcp': 16.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 23.4,
  'wpgt': None,
  'pres': 1003.2,
  'tsun': None},
 {'date': '2024-02-14 00:00:00',
  'tavg': 1.1,
  'tmin': -2.1,
  'tmax': 3.3,
  'prcp': 0.0,
  'snow': 5.0,
  'wdir': None,
  'wspd': 37.4,
  'wpgt': None,
  'pres': 1015.7,
  'tsun': None},
 {'date': '2024-02-15 00:00:00',
  'tavg': -0.8,
  'tmin': -3.2,
  'tmax': 2.2,
  'prcp': 0.0,
  'snow': 3.0,
  'wdir': None,
  'wspd': 20.2,
  'wpgt': None,
  'pres': 1018.5,
  'tsun': None},
 {'date': '2024-02-16 00:00:00',
  'tavg': 3.1,
  'tmin': 1.1,
  'tmax': 6.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 24.5,
  'wpgt': None,
  'pres': 1011.3,
  'tsun': None},
 {'date': '2024-02-17 00:00:00',
  'tavg': 0.4,
  'tmin': -3.2,
  'tmax': 2.2,
  'prcp': 8.4,
  'snow': 15.0,
  'wdir': None,
  'wspd': 18.4,
  'wpgt': None,
  'pres': 1009.7,
  'tsun': None},
 {'date': '2024-02-18 00:00:00',
  'tavg': -0.9,
  'tmin': -3.8,
  'tmax': 4.4,
  'prcp': 0.0,
  'snow': 8.0,
  'wdir': None,
  'wspd': 28.1,
  'wpgt': None,
  'pres': 1012.2,
  'tsun': None},
 {'date': '2024-02-19 00:00:00',
  'tavg': 2.2,
  'tmin': -1.6,
  'tmax': 5.0,
  'prcp': 0.0,
  'snow': 3.0,
  'wdir': None,
  'wspd': 17.3,
  'wpgt': None,
  'pres': 1020.8,
  'tsun': None},
 {'date': '2024-02-20 00:00:00',
  'tavg': -0.4,
  'tmin': -3.8,
  'tmax': 2.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1031.9,
  'tsun': None},
 {'date': '2024-02-21 00:00:00',
  'tavg': -0.2,
  'tmin': -4.3,
  'tmax': 3.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1030.5,
  'tsun': None},
 {'date': '2024-02-22 00:00:00',
  'tavg': 2.6,
  'tmin': 0.6,
  'tmax': 5.0,
  'prcp': 1.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.7,
  'wpgt': None,
  'pres': 1016.3,
  'tsun': None},
 {'date': '2024-02-23 00:00:00',
  'tavg': 6.2,
  'tmin': 4.4,
  'tmax': 8.9,
  'prcp': 1.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 999.6,
  'tsun': None},
 {'date': '2024-02-24 00:00:00',
  'tavg': 5.7,
  'tmin': -2.1,
  'tmax': 7.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 22.7,
  'wpgt': None,
  'pres': 1005.2,
  'tsun': None},
 {'date': '2024-02-25 00:00:00',
  'tavg': -1.3,
  'tmin': -6.0,
  'tmax': 2.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.9,
  'wpgt': None,
  'pres': 1020.2,
  'tsun': None},
 {'date': '2024-02-26 00:00:00',
  'tavg': 3.5,
  'tmin': 0.0,
  'tmax': 8.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.0,
  'wpgt': None,
  'pres': 1018.0,
  'tsun': None},
 {'date': '2024-02-27 00:00:00',
  'tavg': 6.0,
  'tmin': 1.1,
  'tmax': 11.1,
  'prcp': 8.4,
  'snow': 0.0,
  'wdir': None,
  'wspd': 20.2,
  'wpgt': None,
  'pres': 1015.6,
  'tsun': None},
 {'date': '2024-02-28 00:00:00',
  'tavg': 9.1,
  'tmin': 6.7,
  'tmax': 13.3,
  'prcp': 2.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 35.3,
  'wpgt': None,
  'pres': 1005.8,
  'tsun': None},
 {'date': '2024-02-29 00:00:00',
  'tavg': 3.9,
  'tmin': -0.5,
  'tmax': 6.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 30.6,
  'wpgt': None,
  'pres': 1023.2,
  'tsun': None},
 {'date': '2024-03-01 00:00:00',
  'tavg': 1.9,
  'tmin': -2.1,
  'tmax': 5.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.9,
  'wpgt': None,
  'pres': 1035.7,
  'tsun': None},
 {'date': '2024-03-02 00:00:00',
  'tavg': 6.8,
  'tmin': 5.0,
  'tmax': 11.7,
  'prcp': 36.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.0,
  'wpgt': None,
  'pres': 1025.9,
  'tsun': None},
 {'date': '2024-03-03 00:00:00',
  'tavg': 11.7,
  'tmin': 8.3,
  'tmax': 20.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.6,
  'wpgt': None,
  'pres': 1021.2,
  'tsun': None},
 {'date': '2024-03-04 00:00:00',
  'tavg': 10.1,
  'tmin': 5.6,
  'tmax': 12.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.9,
  'wpgt': None,
  'pres': 1027.9,
  'tsun': None},
 {'date': '2024-03-05 00:00:00',
  'tavg': 6.9,
  'tmin': 5.6,
  'tmax': 8.9,
  'prcp': 10.7,
  'snow': 0.0,
  'wdir': None,
  'wspd': 17.6,
  'wpgt': None,
  'pres': 1021.0,
  'tsun': None},
 {'date': '2024-03-06 00:00:00',
  'tavg': 8.0,
  'tmin': 7.2,
  'tmax': 10.6,
  'prcp': 47.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.5,
  'wpgt': None,
  'pres': 1015.4,
  'tsun': None},
 {'date': '2024-03-07 00:00:00',
  'tavg': 10.1,
  'tmin': 6.7,
  'tmax': 12.8,
  'prcp': 3.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 25.6,
  'wpgt': None,
  'pres': 1011.5,
  'tsun': None},
 {'date': '2024-03-08 00:00:00',
  'tavg': 7.4,
  'tmin': 3.9,
  'tmax': 18.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.9,
  'wpgt': None,
  'pres': 1025.2,
  'tsun': None},
 {'date': '2024-03-09 00:00:00',
  'tavg': 5.6,
  'tmin': 4.4,
  'tmax': 9.4,
  'prcp': 43.2,
  'snow': 0.0,
  'wdir': None,
  'wspd': 27.7,
  'wpgt': None,
  'pres': 1017.4,
  'tsun': None},
 {'date': '2024-03-10 00:00:00',
  'tavg': 7.8,
  'tmin': 2.8,
  'tmax': 11.7,
  'prcp': 0.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 31.3,
  'wpgt': None,
  'pres': 996.4,
  'tsun': None},
 {'date': '2024-03-11 00:00:00',
  'tavg': 5.9,
  'tmin': 1.7,
  'tmax': 11.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 42.8,
  'wpgt': None,
  'pres': 1004.0,
  'tsun': None},
 {'date': '2024-03-12 00:00:00',
  'tavg': 11.0,
  'tmin': 5.0,
  'tmax': 19.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 21.6,
  'wpgt': None,
  'pres': 1009.8,
  'tsun': None},
 {'date': '2024-03-13 00:00:00',
  'tavg': 10.6,
  'tmin': 5.0,
  'tmax': 13.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1013.2,
  'tsun': None},
 {'date': '2024-03-14 00:00:00',
  'tavg': 9.9,
  'tmin': 5.0,
  'tmax': 18.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1015.9,
  'tsun': None},
 {'date': '2024-03-15 00:00:00',
  'tavg': 14.2,
  'tmin': 9.4,
  'tmax': 22.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.0,
  'wpgt': None,
  'pres': 1007.2,
  'tsun': None},
 {'date': '2024-03-16 00:00:00',
  'tavg': 10.5,
  'tmin': 6.1,
  'tmax': 12.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.0,
  'wpgt': None,
  'pres': 1009.5,
  'tsun': None},
 {'date': '2024-03-17 00:00:00',
  'tavg': 11.7,
  'tmin': 8.3,
  'tmax': 17.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 22.0,
  'wpgt': None,
  'pres': 1002.7,
  'tsun': None},
 {'date': '2024-03-18 00:00:00',
  'tavg': 9.3,
  'tmin': 3.3,
  'tmax': 11.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 23.8,
  'wpgt': None,
  'pres': 1006.0,
  'tsun': None},
 {'date': '2024-03-19 00:00:00',
  'tavg': 4.9,
  'tmin': 1.7,
  'tmax': 8.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 26.3,
  'wpgt': None,
  'pres': 1007.5,
  'tsun': None},
 {'date': '2024-03-20 00:00:00',
  'tavg': 7.3,
  'tmin': 1.1,
  'tmax': 11.7,
  'prcp': 0.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 23.8,
  'wpgt': None,
  'pres': 1005.2,
  'tsun': None},
 {'date': '2024-03-21 00:00:00',
  'tavg': 2.6,
  'tmin': -1.0,
  'tmax': 6.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 31.0,
  'wpgt': None,
  'pres': 1018.7,
  'tsun': None},
 {'date': '2024-03-22 00:00:00',
  'tavg': 1.2,
  'tmin': -2.1,
  'tmax': 5.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.5,
  'wpgt': None,
  'pres': 1027.9,
  'tsun': None},
 {'date': '2024-03-23 00:00:00',
  'tavg': 7.2,
  'tmin': 1.7,
  'tmax': 11.1,
  'prcp': 79.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 27.0,
  'wpgt': None,
  'pres': 1011.8,
  'tsun': None},
 {'date': '2024-03-24 00:00:00',
  'tavg': 3.6,
  'tmin': -0.5,
  'tmax': 7.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 25.6,
  'wpgt': None,
  'pres': 1022.9,
  'tsun': None},
 {'date': '2024-03-25 00:00:00',
  'tavg': 5.1,
  'tmin': 1.1,
  'tmax': 11.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 20.5,
  'wpgt': None,
  'pres': 1030.0,
  'tsun': None},
 {'date': '2024-03-26 00:00:00',
  'tavg': 6.3,
  'tmin': 3.3,
  'tmax': 9.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.2,
  'wpgt': None,
  'pres': 1023.2,
  'tsun': None},
 {'date': '2024-03-27 00:00:00',
  'tavg': 6.7,
  'tmin': 4.4,
  'tmax': 10.0,
  'prcp': 2.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1019.5,
  'tsun': None},
 {'date': '2024-03-28 00:00:00',
  'tavg': 8.6,
  'tmin': 6.7,
  'tmax': 9.4,
  'prcp': 24.4,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.6,
  'wpgt': None,
  'pres': 1014.0,
  'tsun': None},
 {'date': '2024-03-29 00:00:00',
  'tavg': 8.6,
  'tmin': 5.6,
  'tmax': 13.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 32.0,
  'wpgt': None,
  'pres': 1007.1,
  'tsun': None},
 {'date': '2024-03-30 00:00:00',
  'tavg': 9.1,
  'tmin': 5.0,
  'tmax': 16.1,
  'prcp': 0.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 26.6,
  'wpgt': None,
  'pres': 1008.4,
  'tsun': None},
 {'date': '2024-03-31 00:00:00',
  'tavg': 12.1,
  'tmin': 7.2,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 17.3,
  'wpgt': None,
  'pres': 1011.2,
  'tsun': None}]

In [23]:
# using pd.json_normalize() twice to get to the weather_stats of one airport under 'data'

df_JFK = pd.json_normalize(pd.json_normalize(weather_daily_df['extracted_data']).loc[0, 'data'])
df_JFK

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2024-01-01 00:00:00,5.5,1.7,8.3,0.0,0.0,None,10.8,None,1016.9,None
1,2024-01-02 00:00:00,2.1,-2.1,5.6,0.0,0.0,None,15.8,None,1018.1,None
2,2024-01-03 00:00:00,3.7,0.6,7.2,0.0,0.0,None,13.7,None,1016.4,None
3,2024-01-04 00:00:00,4.6,-2.1,7.8,0.0,0.0,None,23.0,None,1016.0,None
4,2024-01-05 00:00:00,-0.4,-3.2,3.3,0.0,0.0,None,21.2,None,1024.7,None
...,...,...,...,...,...,...,...,...,...,...,...
86,2024-03-27 00:00:00,6.7,4.4,10.0,2.8,0.0,None,8.6,None,1019.5,None
87,2024-03-28 00:00:00,8.6,6.7,9.4,24.4,0.0,None,16.6,None,1014.0,None
88,2024-03-29 00:00:00,8.6,5.6,13.9,0.0,0.0,None,32.0,None,1007.1,None
89,2024-03-30 00:00:00,9.1,5.0,16.1,0.5,0.0,None,26.6,None,1008.4,None
90,2024-03-31 00:00:00,12.1,7.2,16.7,0.0,0.0,None,17.3,None,1011.2,None

In [34]:
import pprint

In [24]:
#  compare if needed to the JSON for 'JFK', first row 
weather_daily_df.loc[0,'extracted_data']

{'meta': {'generated': '2025-10-28 13:56:32'},
 'data': [{'date': '2024-01-01 00:00:00',
   'tavg': 5.5,
   'tmin': 1.7,
   'tmax': 8.3,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 10.8,
   'wpgt': None,
   'pres': 1016.9,
   'tsun': None},
  {'date': '2024-01-02 00:00:00',
   'tavg': 2.1,
   'tmin': -2.1,
   'tmax': 5.6,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 15.8,
   'wpgt': None,
   'pres': 1018.1,
   'tsun': None},
  {'date': '2024-01-03 00:00:00',
   'tavg': 3.7,
   'tmin': 0.6,
   'tmax': 7.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 13.7,
   'wpgt': None,
   'pres': 1016.4,
   'tsun': None},
  {'date': '2024-01-04 00:00:00',
   'tavg': 4.6,
   'tmin': -2.1,
   'tmax': 7.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 23.0,
   'wpgt': None,
   'pres': 1016.0,
   'tsun': None},
  {'date': '2024-01-05 00:00:00',
   'tavg': -0.4,
   'tmin': -3.2,
   'tmax': 3.3,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 21.2,
   'wpgt': None,
   'pres': 1024.7,
   'tsun': None},
  {'date': '2024-01-06 00:00:00',
   'tavg': 0.6,
   'tmin': -2.7,
   'tmax': 3.9,
   'prcp': 13.7,
   'snow': 0.0,
   'wdir': None,
   'wspd': 18.0,
   'wpgt': None,
   'pres': 1018.0,
   'tsun': None},
  {'date': '2024-01-07 00:00:00',
   'tavg': 2.8,
   'tmin': 1.7,
   'tmax': 3.9,
   'prcp': 7.1,
   'snow': 0.0,
   'wdir': None,
   'wspd': 25.2,
   'wpgt': None,
   'pres': 1004.9,
   'tsun': None},
  {'date': '2024-01-08 00:00:00',
   'tavg': 3.7,
   'tmin': 0.0,
   'tmax': 7.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 19.8,
   'wpgt': None,
   'pres': 1026.0,
   'tsun': None},
  {'date': '2024-01-09 00:00:00',
   'tavg': 2.9,
   'tmin': -2.1,
   'tmax': 12.2,
   'prcp': 40.4,
   'snow': 0.0,
   'wdir': None,
   'wspd': 26.6,
   'wpgt': None,
   'pres': 1018.2,
   'tsun': None},
  {'date': '2024-01-10 00:00:00',
   'tavg': 9.9,
   'tmin': 6.1,
   'tmax': 12.2,
   'prcp': 7.1,
   'snow': 0.0,
   'wdir': None,
   'wspd': 36.4,
   'wpgt': None,
   'pres': 992.9,
   'tsun': None},
  {'date': '2024-01-11 00:00:00',
   'tavg': 6.4,
   'tmin': 3.9,
   'tmax': 7.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 23.8,
   'wpgt': None,
   'pres': 1010.8,
   'tsun': None},
  {'date': '2024-01-12 00:00:00',
   'tavg': 5.6,
   'tmin': 1.1,
   'tmax': 8.9,
   'prcp': 1.5,
   'snow': 0.0,
   'wdir': None,
   'wspd': 18.4,
   'wpgt': None,
   'pres': 1018.6,
   'tsun': None},
  {'date': '2024-01-13 00:00:00',
   'tavg': 9.4,
   'tmin': 1.7,
   'tmax': 13.3,
   'prcp': 28.7,
   'snow': 0.0,
   'wdir': None,
   'wspd': 36.7,
   'wpgt': None,
   'pres': 995.9,
   'tsun': None},
  {'date': '2024-01-14 00:00:00',
   'tavg': 2.6,
   'tmin': -3.2,
   'tmax': 6.7,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 34.6,
   'wpgt': None,
   'pres': 1012.7,
   'tsun': None},
  {'date': '2024-01-15 00:00:00',
   'tavg': -2.8,
   'tmin': -4.9,
   'tmax': -1.6,
   'prcp': 1.5,
   'snow': 0.0,
   'wdir': None,
   'wspd': 15.1,
   'wpgt': None,
   'pres': 1023.6,
   'tsun': None},
  {'date': '2024-01-16 00:00:00',
   'tavg': -2.1,
   'tmin': -5.5,
   'tmax': 0.0,
   'prcp': 9.1,
   'snow': 5.0,
   'wdir': None,
   'wspd': 23.0,
   'wpgt': None,
   'pres': 1011.8,
   'tsun': None},
  {'date': '2024-01-17 00:00:00',
   'tavg': -5.7,
   'tmin': -7.7,
   'tmax': -4.3,
   'prcp': 0.0,
   'snow': 3.0,
   'wdir': None,
   'wspd': 29.2,
   'wpgt': None,
   'pres': 1015.8,
   'tsun': None},
  {'date': '2024-01-18 00:00:00',
   'tavg': -3.5,
   'tmin': -5.5,
   'tmax': 0.6,
   'prcp': 0.0,
   'snow': 3.0,
   'wdir': None,
   'wspd': 18.4,
   'wpgt': None,
   'pres': 1020.8,
   'tsun': None},
  {'date': '2024-01-19 00:00:00',
   'tavg': -1.1,
   'tmin': -3.8,
   'tmax': 0.6,
   'prcp': 0.3,
   'snow': 0.0,
   'wdir': None,
   'wspd': 17.6,
   'wpgt': None,
   'pres': 1011.0,
   'tsun': None},
  {'date': '2024-01-20 00:00:00',
   'tavg': -5.2,
   'tmin': -7.7,
   'tmax': -3.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 33.5,
   'wpgt': None,
   'pres': 1014.8,
   'tsun': None},
  {'date': '2024-01-21 00:00:00',
   'tavg': -4.8,
   'tmin': -7.1,
   'tmax': 0.0,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 28.8,
   'wpgt': None,
   'pres': 1026.4,
   'tsun': None},
  {'date': '2024-01-22 00:00:00',
   'tavg': -2.1,
   'tmin': -5.5,
   'tmax': 2.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 20.2,
   'wpgt': None,
   'pres': 1033.6,
   'tsun': None},
  {'date': '2024-01-23 00:00:00',
   'tavg': 2.0,
   'tmin': 0.0,
   'tmax': 4.4,
   'prcp': 0.3,
   'snow': 0.0,
   'wdir': None,
   'wspd': 12.2,
   'wpgt': None,
   'pres': 1032.6,
   'tsun': None},
  {'date': '2024-01-24 00:00:00',
   'tavg': 4.1,
   'tmin': 2.2,
   'tmax': 7.2,
   'prcp': 2.3,
   'snow': 0.0,
   'wdir': None,
   'wspd': 8.6,
   'wpgt': None,
   'pres': 1031.3,
   'tsun': None},
  {'date': '2024-01-25 00:00:00',
   'tavg': 8.4,
   'tmin': 6.1,
   'tmax': 12.8,
   'prcp': 6.9,
   'snow': 0.0,
   'wdir': None,
   'wspd': 9.7,
   'wpgt': None,
   'pres': 1020.9,
   'tsun': None},
  {'date': '2024-01-26 00:00:00',
   'tavg': 7.1,
   'tmin': 5.0,
   'tmax': 7.8,
   'prcp': 5.3,
   'snow': 0.0,
   'wdir': None,
   'wspd': 13.0,
   'wpgt': None,
   'pres': 1018.3,
   'tsun': None},
  {'date': '2024-01-27 00:00:00',
   'tavg': 6.1,
   'tmin': 5.0,
   'tmax': 8.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 8.6,
   'wpgt': None,
   'pres': 1022.2,
   'tsun': None},
  {'date': '2024-01-28 00:00:00',
   'tavg': 4.4,
   'tmin': 2.8,
   'tmax': 5.0,
   'prcp': 23.4,
   'snow': 0.0,
   'wdir': None,
   'wspd': 22.0,
   'wpgt': None,
   'pres': 1010.1,
   'tsun': None},
  {'date': '2024-01-29 00:00:00',
   'tavg': 2.9,
   'tmin': 1.7,
   'tmax': 4.4,
   'prcp': 0.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 25.6,
   'wpgt': None,
   'pres': 1010.4,
   'tsun': None},
  {'date': '2024-01-30 00:00:00',
   'tavg': 2.2,
   'tmin': 1.1,
   'tmax': 3.3,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 12.6,
   'wpgt': None,
   'pres': 1022.4,
   'tsun': None},
  {'date': '2024-01-31 00:00:00',
   'tavg': 2.3,
   'tmin': 1.1,
   'tmax': 3.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 11.5,
   'wpgt': None,
   'pres': 1020.4,
   'tsun': None},
  {'date': '2024-02-01 00:00:00',
   'tavg': 3.4,
   'tmin': 0.0,
   'tmax': 6.7,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 11.9,
   'wpgt': None,
   'pres': 1016.0,
   'tsun': None},
  {'date': '2024-02-02 00:00:00',
   'tavg': 5.1,
   'tmin': 2.8,
   'tmax': 5.6,
   'prcp': 4.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 13.7,
   'wpgt': None,
   'pres': 1012.2,
   'tsun': None},
  {'date': '2024-02-03 00:00:00',
   'tavg': 2.8,
   'tmin': 0.0,
   'tmax': 6.1,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 22.7,
   'wpgt': None,
   'pres': 1017.1,
   'tsun': None},
  {'date': '2024-02-04 00:00:00',
   'tavg': 2.7,
   'tmin': -1.0,
   'tmax': 7.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 17.3,
   'wpgt': None,
   'pres': 1015.6,
   'tsun': None},
  {'date': '2024-02-05 00:00:00',
   'tavg': 2.9,
   'tmin': -1.0,
   'tmax': 7.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 20.5,
   'wpgt': None,
   'pres': 1014.1,
   'tsun': None},
  {'date': '2024-02-06 00:00:00',
   'tavg': 1.2,
   'tmin': -2.7,
   'tmax': 5.6,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.9,
   'wpgt': None,
   'pres': 1021.6,
   'tsun': None},
  {'date': '2024-02-07 00:00:00',
   'tavg': 2.8,
   'tmin': -1.6,
   'tmax': 8.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 11.2,
   'wpgt': None,
   'pres': 1025.6,
   'tsun': None},
  {'date': '2024-02-08 00:00:00',
   'tavg': 4.3,
   'tmin': 0.0,
   'tmax': 8.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 9.4,
   'wpgt': None,
   'pres': 1026.0,
   'tsun': None},
  {'date': '2024-02-09 00:00:00',
   'tavg': 6.2,
   'tmin': 3.3,
   'tmax': 9.4,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 15.8,
   'wpgt': None,
   'pres': 1019.7,
   'tsun': None},
  {'date': '2024-02-10 00:00:00',
   'tavg': 6.6,
   'tmin': 2.2,
   'tmax': 12.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 10.8,
   'wpgt': None,
   'pres': 1011.4,
   'tsun': None},
  {'date': '2024-02-11 00:00:00',
   'tavg': 8.8,
   'tmin': 6.1,
   'tmax': 10.6,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 15.5,
   'wpgt': None,
   'pres': 1012.7,
   'tsun': None},
  {'date': '2024-02-12 00:00:00',
   'tavg': 5.3,
   'tmin': 2.2,
   'tmax': 7.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 10.8,
   'wpgt': None,
   'pres': 1012.3,
   'tsun': None},
  {'date': '2024-02-13 00:00:00',
   'tavg': 2.3,
   'tmin': 0.0,
   'tmax': 3.9,
   'prcp': 16.5,
   'snow': 0.0,
   'wdir': None,
   'wspd': 23.4,
   'wpgt': None,
   'pres': 1003.2,
   'tsun': None},
  {'date': '2024-02-14 00:00:00',
   'tavg': 1.1,
   'tmin': -2.1,
   'tmax': 3.3,
   'prcp': 0.0,
   'snow': 5.0,
   'wdir': None,
   'wspd': 37.4,
   'wpgt': None,
   'pres': 1015.7,
   'tsun': None},
  {'date': '2024-02-15 00:00:00',
   'tavg': -0.8,
   'tmin': -3.2,
   'tmax': 2.2,
   'prcp': 0.0,
   'snow': 3.0,
   'wdir': None,
   'wspd': 20.2,
   'wpgt': None,
   'pres': 1018.5,
   'tsun': None},
  {'date': '2024-02-16 00:00:00',
   'tavg': 3.1,
   'tmin': 1.1,
   'tmax': 6.1,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 24.5,
   'wpgt': None,
   'pres': 1011.3,
   'tsun': None},
  {'date': '2024-02-17 00:00:00',
   'tavg': 0.4,
   'tmin': -3.2,
   'tmax': 2.2,
   'prcp': 8.4,
   'snow': 15.0,
   'wdir': None,
   'wspd': 18.4,
   'wpgt': None,
   'pres': 1009.7,
   'tsun': None},
  {'date': '2024-02-18 00:00:00',
   'tavg': -0.9,
   'tmin': -3.8,
   'tmax': 4.4,
   'prcp': 0.0,
   'snow': 8.0,
   'wdir': None,
   'wspd': 28.1,
   'wpgt': None,
   'pres': 1012.2,
   'tsun': None},
  {'date': '2024-02-19 00:00:00',
   'tavg': 2.2,
   'tmin': -1.6,
   'tmax': 5.0,
   'prcp': 0.0,
   'snow': 3.0,
   'wdir': None,
   'wspd': 17.3,
   'wpgt': None,
   'pres': 1020.8,
   'tsun': None},
  {'date': '2024-02-20 00:00:00',
   'tavg': -0.4,
   'tmin': -3.8,
   'tmax': 2.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 12.2,
   'wpgt': None,
   'pres': 1031.9,
   'tsun': None},
  {'date': '2024-02-21 00:00:00',
   'tavg': -0.2,
   'tmin': -4.3,
   'tmax': 3.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 12.2,
   'wpgt': None,
   'pres': 1030.5,
   'tsun': None},
  {'date': '2024-02-22 00:00:00',
   'tavg': 2.6,
   'tmin': 0.6,
   'tmax': 5.0,
   'prcp': 1.3,
   'snow': 0.0,
   'wdir': None,
   'wspd': 13.7,
   'wpgt': None,
   'pres': 1016.3,
   'tsun': None},
  {'date': '2024-02-23 00:00:00',
   'tavg': 6.2,
   'tmin': 4.4,
   'tmax': 8.9,
   'prcp': 1.3,
   'snow': 0.0,
   'wdir': None,
   'wspd': 11.9,
   'wpgt': None,
   'pres': 999.6,
   'tsun': None},
  {'date': '2024-02-24 00:00:00',
   'tavg': 5.7,
   'tmin': -2.1,
   'tmax': 7.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 22.7,
   'wpgt': None,
   'pres': 1005.2,
   'tsun': None},
  {'date': '2024-02-25 00:00:00',
   'tavg': -1.3,
   'tmin': -6.0,
   'tmax': 2.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.9,
   'wpgt': None,
   'pres': 1020.2,
   'tsun': None},
  {'date': '2024-02-26 00:00:00',
   'tavg': 3.5,
   'tmin': 0.0,
   'tmax': 8.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 14.0,
   'wpgt': None,
   'pres': 1018.0,
   'tsun': None},
  {'date': '2024-02-27 00:00:00',
   'tavg': 6.0,
   'tmin': 1.1,
   'tmax': 11.1,
   'prcp': 8.4,
   'snow': 0.0,
   'wdir': None,
   'wspd': 20.2,
   'wpgt': None,
   'pres': 1015.6,
   'tsun': None},
  {'date': '2024-02-28 00:00:00',
   'tavg': 9.1,
   'tmin': 6.7,
   'tmax': 13.3,
   'prcp': 2.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 35.3,
   'wpgt': None,
   'pres': 1005.8,
   'tsun': None},
  {'date': '2024-02-29 00:00:00',
   'tavg': 3.9,
   'tmin': -0.5,
   'tmax': 6.7,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 30.6,
   'wpgt': None,
   'pres': 1023.2,
   'tsun': None},
  {'date': '2024-03-01 00:00:00',
   'tavg': 1.9,
   'tmin': -2.1,
   'tmax': 5.0,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.9,
   'wpgt': None,
   'pres': 1035.7,
   'tsun': None},
  {'date': '2024-03-02 00:00:00',
   'tavg': 6.8,
   'tmin': 5.0,
   'tmax': 11.7,
   'prcp': 36.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 18.0,
   'wpgt': None,
   'pres': 1025.9,
   'tsun': None},
  {'date': '2024-03-03 00:00:00',
   'tavg': 11.7,
   'tmin': 8.3,
   'tmax': 20.0,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.6,
   'wpgt': None,
   'pres': 1021.2,
   'tsun': None},
  {'date': '2024-03-04 00:00:00',
   'tavg': 10.1,
   'tmin': 5.6,
   'tmax': 12.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.9,
   'wpgt': None,
   'pres': 1027.9,
   'tsun': None},
  {'date': '2024-03-05 00:00:00',
   'tavg': 6.9,
   'tmin': 5.6,
   'tmax': 8.9,
   'prcp': 10.7,
   'snow': 0.0,
   'wdir': None,
   'wspd': 17.6,
   'wpgt': None,
   'pres': 1021.0,
   'tsun': None},
  {'date': '2024-03-06 00:00:00',
   'tavg': 8.0,
   'tmin': 7.2,
   'tmax': 10.6,
   'prcp': 47.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 11.5,
   'wpgt': None,
   'pres': 1015.4,
   'tsun': None},
  {'date': '2024-03-07 00:00:00',
   'tavg': 10.1,
   'tmin': 6.7,
   'tmax': 12.8,
   'prcp': 3.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 25.6,
   'wpgt': None,
   'pres': 1011.5,
   'tsun': None},
  {'date': '2024-03-08 00:00:00',
   'tavg': 7.4,
   'tmin': 3.9,
   'tmax': 18.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.9,
   'wpgt': None,
   'pres': 1025.2,
   'tsun': None},
  {'date': '2024-03-09 00:00:00',
   'tavg': 5.6,
   'tmin': 4.4,
   'tmax': 9.4,
   'prcp': 43.2,
   'snow': 0.0,
   'wdir': None,
   'wspd': 27.7,
   'wpgt': None,
   'pres': 1017.4,
   'tsun': None},
  {'date': '2024-03-10 00:00:00',
   'tavg': 7.8,
   'tmin': 2.8,
   'tmax': 11.7,
   'prcp': 0.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 31.3,
   'wpgt': None,
   'pres': 996.4,
   'tsun': None},
  {'date': '2024-03-11 00:00:00',
   'tavg': 5.9,
   'tmin': 1.7,
   'tmax': 11.7,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 42.8,
   'wpgt': None,
   'pres': 1004.0,
   'tsun': None},
  {'date': '2024-03-12 00:00:00',
   'tavg': 11.0,
   'tmin': 5.0,
   'tmax': 19.4,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 21.6,
   'wpgt': None,
   'pres': 1009.8,
   'tsun': None},
  {'date': '2024-03-13 00:00:00',
   'tavg': 10.6,
   'tmin': 5.0,
   'tmax': 13.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 9.7,
   'wpgt': None,
   'pres': 1013.2,
   'tsun': None},
  {'date': '2024-03-14 00:00:00',
   'tavg': 9.9,
   'tmin': 5.0,
   'tmax': 18.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 9.7,
   'wpgt': None,
   'pres': 1015.9,
   'tsun': None},
  {'date': '2024-03-15 00:00:00',
   'tavg': 14.2,
   'tmin': 9.4,
   'tmax': 22.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 18.0,
   'wpgt': None,
   'pres': 1007.2,
   'tsun': None},
  {'date': '2024-03-16 00:00:00',
   'tavg': 10.5,
   'tmin': 6.1,
   'tmax': 12.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 18.0,
   'wpgt': None,
   'pres': 1009.5,
   'tsun': None},
  {'date': '2024-03-17 00:00:00',
   'tavg': 11.7,
   'tmin': 8.3,
   'tmax': 17.2,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 22.0,
   'wpgt': None,
   'pres': 1002.7,
   'tsun': None},
  {'date': '2024-03-18 00:00:00',
   'tavg': 9.3,
   'tmin': 3.3,
   'tmax': 11.7,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 23.8,
   'wpgt': None,
   'pres': 1006.0,
   'tsun': None},
  {'date': '2024-03-19 00:00:00',
   'tavg': 4.9,
   'tmin': 1.7,
   'tmax': 8.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 26.3,
   'wpgt': None,
   'pres': 1007.5,
   'tsun': None},
  {'date': '2024-03-20 00:00:00',
   'tavg': 7.3,
   'tmin': 1.1,
   'tmax': 11.7,
   'prcp': 0.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 23.8,
   'wpgt': None,
   'pres': 1005.2,
   'tsun': None},
  {'date': '2024-03-21 00:00:00',
   'tavg': 2.6,
   'tmin': -1.0,
   'tmax': 6.7,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 31.0,
   'wpgt': None,
   'pres': 1018.7,
   'tsun': None},
  {'date': '2024-03-22 00:00:00',
   'tavg': 1.2,
   'tmin': -2.1,
   'tmax': 5.0,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 15.5,
   'wpgt': None,
   'pres': 1027.9,
   'tsun': None},
  {'date': '2024-03-23 00:00:00',
   'tavg': 7.2,
   'tmin': 1.7,
   'tmax': 11.1,
   'prcp': 79.5,
   'snow': 0.0,
   'wdir': None,
   'wspd': 27.0,
   'wpgt': None,
   'pres': 1011.8,
   'tsun': None},
  {'date': '2024-03-24 00:00:00',
   'tavg': 3.6,
   'tmin': -0.5,
   'tmax': 7.8,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 25.6,
   'wpgt': None,
   'pres': 1022.9,
   'tsun': None},
  {'date': '2024-03-25 00:00:00',
   'tavg': 5.1,
   'tmin': 1.1,
   'tmax': 11.1,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 20.5,
   'wpgt': None,
   'pres': 1030.0,
   'tsun': None},
  {'date': '2024-03-26 00:00:00',
   'tavg': 6.3,
   'tmin': 3.3,
   'tmax': 9.4,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.2,
   'wpgt': None,
   'pres': 1023.2,
   'tsun': None},
  {'date': '2024-03-27 00:00:00',
   'tavg': 6.7,
   'tmin': 4.4,
   'tmax': 10.0,
   'prcp': 2.8,
   'snow': 0.0,
   'wdir': None,
   'wspd': 8.6,
   'wpgt': None,
   'pres': 1019.5,
   'tsun': None},
  {'date': '2024-03-28 00:00:00',
   'tavg': 8.6,
   'tmin': 6.7,
   'tmax': 9.4,
   'prcp': 24.4,
   'snow': 0.0,
   'wdir': None,
   'wspd': 16.6,
   'wpgt': None,
   'pres': 1014.0,
   'tsun': None},
  {'date': '2024-03-29 00:00:00',
   'tavg': 8.6,
   'tmin': 5.6,
   'tmax': 13.9,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 32.0,
   'wpgt': None,
   'pres': 1007.1,
   'tsun': None},
  {'date': '2024-03-30 00:00:00',
   'tavg': 9.1,
   'tmin': 5.0,
   'tmax': 16.1,
   'prcp': 0.5,
   'snow': 0.0,
   'wdir': None,
   'wspd': 26.6,
   'wpgt': None,
   'pres': 1008.4,
   'tsun': None},
  {'date': '2024-03-31 00:00:00',
   'tavg': 12.1,
   'tmin': 7.2,
   'tmax': 16.7,
   'prcp': 0.0,
   'snow': 0.0,
   'wdir': None,
   'wspd': 17.3,
   'wpgt': None,
   'pres': 1011.2,
   'tsun': None}]}

In [25]:
sample_mia = weather_daily_df['extracted_data'][1] #all data from the first airport:MIA, we can see that we have meta and data
print(json.dumps(sample_jfk, indent=2)[:1000])

{
  "meta": {
    "generated": "2025-10-28 13:56:32"
  },
  "data": [
    {
      "date": "2024-01-01 00:00:00",
      "tavg": 5.5,
      "tmin": 1.7,
      "tmax": 8.3,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 10.8,
      "wpgt": null,
      "pres": 1016.9,
      "tsun": null
    },
    {
      "date": "2024-01-02 00:00:00",
      "tavg": 2.1,
      "tmin": -2.1,
      "tmax": 5.6,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 15.8,
      "wpgt": null,
      "pres": 1018.1,
      "tsun": null
    },
    {
      "date": "2024-01-03 00:00:00",
      "tavg": 3.7,
      "tmin": 0.6,
      "tmax": 7.2,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 13.7,
      "wpgt": null,
      "pres": 1016.4,
      "tsun": null
    },
    {
      "date": "2024-01-04 00:00:00",
      "tavg": 4.6,
      "tmin": -2.1,
      "tmax": 7.8,
      "prcp": 0.0,
      "snow": 0.0,
      "wdir": null,
      "wspd": 23.0,
      "wpgt"

In [26]:
pd.json_normalize(sample_mia)

                                                data       meta.generated
0  [{'date': '2024-01-01 00:00:00', 'tavg': 16.7,...  2025-10-28 12:21:52

In [27]:
pd.json_normalize(weather_daily_df['extracted_data']).loc[1, 'data'] #extract only data from the json data of first airport:MIA

[{'date': '2024-01-01 00:00:00',
  'tavg': 16.7,
  'tmin': 11.1,
  'tmax': 22.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 3.2,
  'wpgt': None,
  'pres': 1022.8,
  'tsun': None},
 {'date': '2024-01-02 00:00:00',
  'tavg': 17.2,
  'tmin': 13.3,
  'tmax': 22.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 6.8,
  'wpgt': None,
  'pres': 1021.1,
  'tsun': None},
 {'date': '2024-01-03 00:00:00',
  'tavg': 17.3,
  'tmin': 12.8,
  'tmax': 23.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 7.9,
  'wpgt': None,
  'pres': 1018.7,
  'tsun': None},
 {'date': '2024-01-04 00:00:00',
  'tavg': 20.4,
  'tmin': 14.4,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1016.3,
  'tsun': None},
 {'date': '2024-01-05 00:00:00',
  'tavg': 20.7,
  'tmin': 16.7,
  'tmax': 25.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 20.2,
  'wpgt': None,
  'pres': 1018.2,
  'tsun': None},
 {'date': '2024-01-06 00:00:00',
  'tavg': 24.0,
  'tmin': 21.7,
  'tmax': 26.7,
  'prcp': 2.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1014.3,
  'tsun': None},
 {'date': '2024-01-07 00:00:00',
  'tavg': 21.3,
  'tmin': 16.7,
  'tmax': 23.3,
  'prcp': 1.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.0,
  'wpgt': None,
  'pres': 1017.7,
  'tsun': None},
 {'date': '2024-01-08 00:00:00',
  'tavg': 19.9,
  'tmin': 15.6,
  'tmax': 24.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 19.1,
  'wpgt': None,
  'pres': 1020.1,
  'tsun': None},
 {'date': '2024-01-09 00:00:00',
  'tavg': 24.2,
  'tmin': 22.2,
  'tmax': 26.7,
  'prcp': 0.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 25.9,
  'wpgt': None,
  'pres': 1013.2,
  'tsun': None},
 {'date': '2024-01-10 00:00:00',
  'tavg': 21.4,
  'tmin': 17.8,
  'tmax': 25.6,
  'prcp': 2.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 4.7,
  'wpgt': None,
  'pres': 1014.8,
  'tsun': None},
 {'date': '2024-01-11 00:00:00',
  'tavg': 19.4,
  'tmin': 17.2,
  'tmax': 22.2,
  'prcp': 9.7,
  'snow': 0.0,
  'wdir': None,
  'wspd': 7.9,
  'wpgt': None,
  'pres': 1016.6,
  'tsun': None},
 {'date': '2024-01-12 00:00:00',
  'tavg': 24.4,
  'tmin': 21.7,
  'tmax': 30.6,
  'prcp': 0.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.1,
  'wpgt': None,
  'pres': 1013.2,
  'tsun': None},
 {'date': '2024-01-13 00:00:00',
  'tavg': 25.2,
  'tmin': 20.0,
  'tmax': 30.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.6,
  'wpgt': None,
  'pres': 1013.8,
  'tsun': None},
 {'date': '2024-01-14 00:00:00',
  'tavg': 20.9,
  'tmin': 17.8,
  'tmax': 23.9,
  'prcp': 2.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.4,
  'wpgt': None,
  'pres': 1018.4,
  'tsun': None},
 {'date': '2024-01-15 00:00:00',
  'tavg': 23.7,
  'tmin': 21.7,
  'tmax': 27.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.6,
  'wpgt': None,
  'pres': 1017.5,
  'tsun': None},
 {'date': '2024-01-16 00:00:00',
  'tavg': 25.1,
  'tmin': 22.2,
  'tmax': 29.4,
  'prcp': 1.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.0,
  'wpgt': None,
  'pres': 1014.9,
  'tsun': None},
 {'date': '2024-01-17 00:00:00',
  'tavg': 21.7,
  'tmin': 18.3,
  'tmax': 23.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1019.6,
  'tsun': None},
 {'date': '2024-01-18 00:00:00',
  'tavg': 23.4,
  'tmin': 20.6,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1019.4,
  'tsun': None},
 {'date': '2024-01-19 00:00:00',
  'tavg': 22.7,
  'tmin': 20.6,
  'tmax': 25.0,
  'prcp': 0.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 5.0,
  'wpgt': None,
  'pres': 1017.1,
  'tsun': None},
 {'date': '2024-01-20 00:00:00',
  'tavg': 21.0,
  'tmin': 13.9,
  'tmax': 23.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1020.2,
  'tsun': None},
 {'date': '2024-01-21 00:00:00',
  'tavg': 15.9,
  'tmin': 11.1,
  'tmax': 21.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.7,
  'wpgt': None,
  'pres': 1026.0,
  'tsun': None},
 {'date': '2024-01-22 00:00:00',
  'tavg': 20.7,
  'tmin': 18.3,
  'tmax': 23.9,
  'prcp': 0.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 28.4,
  'wpgt': None,
  'pres': 1027.2,
  'tsun': None},
 {'date': '2024-01-23 00:00:00',
  'tavg': 23.2,
  'tmin': 21.1,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 24.8,
  'wpgt': None,
  'pres': 1024.7,
  'tsun': None},
 {'date': '2024-01-24 00:00:00',
  'tavg': 24.6,
  'tmin': 22.8,
  'tmax': 27.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 23.8,
  'wpgt': None,
  'pres': 1023.0,
  'tsun': None},
 {'date': '2024-01-25 00:00:00',
  'tavg': 24.7,
  'tmin': 23.3,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.4,
  'wpgt': None,
  'pres': 1022.0,
  'tsun': None},
 {'date': '2024-01-26 00:00:00',
  'tavg': 24.4,
  'tmin': 22.2,
  'tmax': 27.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.9,
  'wpgt': None,
  'pres': 1021.2,
  'tsun': None},
 {'date': '2024-01-27 00:00:00',
  'tavg': 25.1,
  'tmin': 22.8,
  'tmax': 27.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.8,
  'wpgt': None,
  'pres': 1019.6,
  'tsun': None},
 {'date': '2024-01-28 00:00:00',
  'tavg': 24.9,
  'tmin': 16.7,
  'tmax': 29.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.1,
  'wpgt': None,
  'pres': 1017.1,
  'tsun': None},
 {'date': '2024-01-29 00:00:00',
  'tavg': 17.1,
  'tmin': 13.9,
  'tmax': 20.0,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1018.5,
  'tsun': None},
 {'date': '2024-01-30 00:00:00',
  'tavg': 16.3,
  'tmin': 11.7,
  'tmax': 22.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 8.3,
  'wpgt': None,
  'pres': 1019.9,
  'tsun': None},
 {'date': '2024-01-31 00:00:00',
  'tavg': 17.4,
  'tmin': 12.8,
  'tmax': 22.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1018.3,
  'tsun': None},
 {'date': '2024-02-01 00:00:00',
  'tavg': 17.9,
  'tmin': 13.3,
  'tmax': 23.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 8.3,
  'wpgt': None,
  'pres': 1018.8,
  'tsun': None},
 {'date': '2024-02-02 00:00:00',
  'tavg': 19.9,
  'tmin': 16.1,
  'tmax': 25.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 7.2,
  'wpgt': None,
  'pres': 1015.3,
  'tsun': None},
 {'date': '2024-02-03 00:00:00',
  'tavg': 19.9,
  'tmin': 13.9,
  'tmax': 25.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 8.3,
  'wpgt': None,
  'pres': 1011.5,
  'tsun': None},
 {'date': '2024-02-04 00:00:00',
  'tavg': 20.9,
  'tmin': 16.7,
  'tmax': 23.9,
  'prcp': 18.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.0,
  'wpgt': None,
  'pres': 1005.3,
  'tsun': None},
 {'date': '2024-02-05 00:00:00',
  'tavg': 18.0,
  'tmin': 15.6,
  'tmax': 20.0,
  'prcp': 3.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 7.2,
  'wpgt': None,
  'pres': 1001.3,
  'tsun': None},
 {'date': '2024-02-06 00:00:00',
  'tavg': 16.2,
  'tmin': 13.9,
  'tmax': 21.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 19.1,
  'wpgt': None,
  'pres': 1006.3,
  'tsun': None},
 {'date': '2024-02-07 00:00:00',
  'tavg': 17.7,
  'tmin': 13.3,
  'tmax': 25.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.0,
  'wpgt': None,
  'pres': 1017.0,
  'tsun': None},
 {'date': '2024-02-08 00:00:00',
  'tavg': 19.5,
  'tmin': 15.0,
  'tmax': 25.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1021.6,
  'tsun': None},
 {'date': '2024-02-09 00:00:00',
  'tavg': 21.6,
  'tmin': 20.0,
  'tmax': 24.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.5,
  'wpgt': None,
  'pres': 1022.1,
  'tsun': None},
 {'date': '2024-02-10 00:00:00',
  'tavg': 22.8,
  'tmin': 20.0,
  'tmax': 25.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.7,
  'wpgt': None,
  'pres': 1020.5,
  'tsun': None},
 {'date': '2024-02-11 00:00:00',
  'tavg': 23.4,
  'tmin': 21.7,
  'tmax': 26.7,
  'prcp': 1.3,
  'snow': 0.0,
  'wdir': None,
  'wspd': 17.3,
  'wpgt': None,
  'pres': 1017.1,
  'tsun': None},
 {'date': '2024-02-12 00:00:00',
  'tavg': 24.7,
  'tmin': 22.2,
  'tmax': 29.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.6,
  'wpgt': None,
  'pres': 1013.7,
  'tsun': None},
 {'date': '2024-02-13 00:00:00',
  'tavg': 24.3,
  'tmin': 17.2,
  'tmax': 27.8,
  'prcp': 2.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1015.0,
  'tsun': None},
 {'date': '2024-02-14 00:00:00',
  'tavg': 19.9,
  'tmin': 14.4,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.5,
  'wpgt': None,
  'pres': 1019.5,
  'tsun': None},
 {'date': '2024-02-15 00:00:00',
  'tavg': 21.7,
  'tmin': 17.2,
  'tmax': 25.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 1021.1,
  'tsun': None},
 {'date': '2024-02-16 00:00:00',
  'tavg': 22.4,
  'tmin': 18.9,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1017.6,
  'tsun': None},
 {'date': '2024-02-17 00:00:00',
  'tavg': 23.4,
  'tmin': 18.9,
  'tmax': 28.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1012.7,
  'tsun': None},
 {'date': '2024-02-18 00:00:00',
  'tavg': 22.1,
  'tmin': 17.2,
  'tmax': 24.4,
  'prcp': 47.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1010.3,
  'tsun': None},
 {'date': '2024-02-19 00:00:00',
  'tavg': 17.9,
  'tmin': 14.4,
  'tmax': 21.1,
  'prcp': 2.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.0,
  'wpgt': None,
  'pres': 1016.5,
  'tsun': None},
 {'date': '2024-02-20 00:00:00',
  'tavg': 16.4,
  'tmin': 12.2,
  'tmax': 21.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1022.7,
  'tsun': None},
 {'date': '2024-02-21 00:00:00',
  'tavg': 17.3,
  'tmin': 12.8,
  'tmax': 23.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1022.1,
  'tsun': None},
 {'date': '2024-02-22 00:00:00',
  'tavg': 18.3,
  'tmin': 13.3,
  'tmax': 25.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 7.6,
  'wpgt': None,
  'pres': 1018.8,
  'tsun': None},
 {'date': '2024-02-23 00:00:00',
  'tavg': 20.1,
  'tmin': 13.3,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1014.0,
  'tsun': None},
 {'date': '2024-02-24 00:00:00',
  'tavg': 21.1,
  'tmin': 15.6,
  'tmax': 24.4,
  'prcp': 0.8,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1015.0,
  'tsun': None},
 {'date': '2024-02-25 00:00:00',
  'tavg': 18.5,
  'tmin': 12.2,
  'tmax': 25.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 7.6,
  'wpgt': None,
  'pres': 1021.2,
  'tsun': None},
 {'date': '2024-02-26 00:00:00',
  'tavg': 19.2,
  'tmin': 13.3,
  'tmax': 24.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1022.0,
  'tsun': None},
 {'date': '2024-02-27 00:00:00',
  'tavg': 20.3,
  'tmin': 15.0,
  'tmax': 25.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1020.8,
  'tsun': None},
 {'date': '2024-02-28 00:00:00',
  'tavg': 22.9,
  'tmin': 20.0,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.8,
  'wpgt': None,
  'pres': 1020.4,
  'tsun': None},
 {'date': '2024-02-29 00:00:00',
  'tavg': 22.9,
  'tmin': 18.9,
  'tmax': 27.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1022.0,
  'tsun': None},
 {'date': '2024-03-01 00:00:00',
  'tavg': 23.9,
  'tmin': 22.2,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 19.8,
  'wpgt': None,
  'pres': 1022.4,
  'tsun': None},
 {'date': '2024-03-02 00:00:00',
  'tavg': 24.1,
  'tmin': 22.2,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.0,
  'wpgt': None,
  'pres': 1020.7,
  'tsun': None},
 {'date': '2024-03-03 00:00:00',
  'tavg': 24.3,
  'tmin': 21.1,
  'tmax': 28.3,
  'prcp': 5.1,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.2,
  'wpgt': None,
  'pres': 1018.4,
  'tsun': None},
 {'date': '2024-03-04 00:00:00',
  'tavg': 23.9,
  'tmin': 20.0,
  'tmax': 29.4,
  'prcp': 1.5,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1017.0,
  'tsun': None},
 {'date': '2024-03-05 00:00:00',
  'tavg': 24.9,
  'tmin': 22.2,
  'tmax': 28.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1014.9,
  'tsun': None},
 {'date': '2024-03-06 00:00:00',
  'tavg': 24.6,
  'tmin': 21.1,
  'tmax': 27.8,
  'prcp': 14.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 7.9,
  'wpgt': None,
  'pres': 1013.0,
  'tsun': None},
 {'date': '2024-03-07 00:00:00',
  'tavg': 24.5,
  'tmin': 20.6,
  'tmax': 30.0,
  'prcp': 2.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 5.4,
  'wpgt': None,
  'pres': 1013.1,
  'tsun': None},
 {'date': '2024-03-08 00:00:00',
  'tavg': 25.2,
  'tmin': 21.1,
  'tmax': 29.4,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1015.0,
  'tsun': None},
 {'date': '2024-03-09 00:00:00',
  'tavg': 26.6,
  'tmin': 24.4,
  'tmax': 30.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 15.5,
  'wpgt': None,
  'pres': 1013.9,
  'tsun': None},
 {'date': '2024-03-10 00:00:00',
  'tavg': 26.4,
  'tmin': 21.7,
  'tmax': 31.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.7,
  'wpgt': None,
  'pres': 1013.9,
  'tsun': None},
 {'date': '2024-03-11 00:00:00',
  'tavg': 23.0,
  'tmin': 18.3,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.4,
  'wpgt': None,
  'pres': 1019.4,
  'tsun': None},
 {'date': '2024-03-12 00:00:00',
  'tavg': 23.1,
  'tmin': 19.4,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.2,
  'wpgt': None,
  'pres': 1020.0,
  'tsun': None},
 {'date': '2024-03-13 00:00:00',
  'tavg': 23.3,
  'tmin': 18.9,
  'tmax': 27.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1018.1,
  'tsun': None},
 {'date': '2024-03-14 00:00:00',
  'tavg': 24.7,
  'tmin': 21.1,
  'tmax': 28.9,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1018.7,
  'tsun': None},
 {'date': '2024-03-15 00:00:00',
  'tavg': 24.8,
  'tmin': 22.8,
  'tmax': 28.3,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.2,
  'wpgt': None,
  'pres': 1018.1,
  'tsun': None},
 {'date': '2024-03-16 00:00:00',
  'tavg': 25.5,
  'tmin': 21.1,
  'tmax': 30.0,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.2,
  'wpgt': None,
  'pres': 1015.2,
  'tsun': None},
 {'date': '2024-03-17 00:00:00',
  'tavg': 26.2,
  'tmin': 22.2,
  'tmax': 30.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1013.5,
  'tsun': None},
 {'date': '2024-03-18 00:00:00',
  'tavg': 26.9,
  'tmin': 22.8,
  'tmax': 32.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1013.0,
  'tsun': None},
 {'date': '2024-03-19 00:00:00',
  'tavg': 24.1,
  'tmin': 18.9,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 14.4,
  'wpgt': None,
  'pres': 1015.2,
  'tsun': None},
 {'date': '2024-03-20 00:00:00',
  'tavg': 21.3,
  'tmin': 17.2,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1017.6,
  'tsun': None},
 {'date': '2024-03-21 00:00:00',
  'tavg': 23.2,
  'tmin': 20.6,
  'tmax': 27.2,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 17.6,
  'wpgt': None,
  'pres': 1017.9,
  'tsun': None},
 {'date': '2024-03-22 00:00:00',
  'tavg': 22.4,
  'tmin': 20.0,
  'tmax': 23.9,
  'prcp': 59.4,
  'snow': 0.0,
  'wdir': None,
  'wspd': 17.3,
  'wpgt': None,
  'pres': 1015.4,
  'tsun': None},
 {'date': '2024-03-23 00:00:00',
  'tavg': 22.4,
  'tmin': 20.0,
  'tmax': 26.7,
  'prcp': 39.4,
  'snow': 0.0,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1008.2,
  'tsun': None},
 {'date': '2024-03-24 00:00:00',
  'tavg': 22.1,
  'tmin': 17.8,
  'tmax': 27.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.3,
  'wpgt': None,
  'pres': 1010.4,
  'tsun': None},
 {'date': '2024-03-25 00:00:00',
  'tavg': 23.9,
  'tmin': 22.2,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 24.8,
  'wpgt': None,
  'pres': 1014.6,
  'tsun': None},
 {'date': '2024-03-26 00:00:00',
  'tavg': 24.4,
  'tmin': 22.2,
  'tmax': 27.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 20.5,
  'wpgt': None,
  'pres': 1014.1,
  'tsun': None},
 {'date': '2024-03-27 00:00:00',
  'tavg': 25.1,
  'tmin': 22.8,
  'tmax': 27.8,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.0,
  'wpgt': None,
  'pres': 1014.0,
  'tsun': None},
 {'date': '2024-03-28 00:00:00',
  'tavg': 26.4,
  'tmin': 20.6,
  'tmax': 30.6,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 18.4,
  'wpgt': None,
  'pres': 1012.0,
  'tsun': None},
 {'date': '2024-03-29 00:00:00',
  'tavg': 22.4,
  'tmin': 18.3,
  'tmax': 26.7,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 16.6,
  'wpgt': None,
  'pres': 1018.3,
  'tsun': None},
 {'date': '2024-03-30 00:00:00',
  'tavg': 22.2,
  'tmin': 17.8,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 13.3,
  'wpgt': None,
  'pres': 1020.5,
  'tsun': None},
 {'date': '2024-03-31 00:00:00',
  'tavg': 22.5,
  'tmin': 17.8,
  'tmax': 26.1,
  'prcp': 0.0,
  'snow': 0.0,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 1020.3,
  'tsun': None}]

In [28]:
# using pd.json_normalize() twice to get to the weather_stats of one airport under 'data'

df_MIA = pd.json_normalize(pd.json_normalize(weather_daily_df['extracted_data']).loc[1, 'data'])
df_MIA

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2024-01-01 00:00:00,16.7,11.1,22.8,0.0,0.0,None,3.2,None,1022.8,None
1,2024-01-02 00:00:00,17.2,13.3,22.2,0.0,0.0,None,6.8,None,1021.1,None
2,2024-01-03 00:00:00,17.3,12.8,23.3,0.0,0.0,None,7.9,None,1018.7,None
3,2024-01-04 00:00:00,20.4,14.4,26.1,0.0,0.0,None,9.4,None,1016.3,None
4,2024-01-05 00:00:00,20.7,16.7,25.6,0.0,0.0,None,20.2,None,1018.2,None
...,...,...,...,...,...,...,...,...,...,...,...
86,2024-03-27 00:00:00,25.1,22.8,27.8,0.0,0.0,None,18.0,None,1014.0,None
87,2024-03-28 00:00:00,26.4,20.6,30.6,0.0,0.0,None,18.4,None,1012.0,None
88,2024-03-29 00:00:00,22.4,18.3,26.7,0.0,0.0,None,16.6,None,1018.3,None
89,2024-03-30 00:00:00,22.2,17.8,26.1,0.0,0.0,None,13.3,None,1020.5,None
90,2024-03-31 00:00:00,22.5,17.8,26.1,0.0,0.0,None,11.9,None,1020.3,None

In [29]:
sample_lax = weather_daily_df['extracted_data'][2] #all data from the first airport:LAX, we can see that we have meta and data
print(json.dumps(sample_lax, indent=2)[:1000])

{
  "meta": {
    "generated": "2025-10-28 12:21:54"
  },
  "data": [
    {
      "date": "2024-01-01 00:00:00",
      "tavg": 14.0,
      "tmin": 10.0,
      "tmax": 19.4,
      "prcp": 0.0,
      "snow": null,
      "wdir": null,
      "wspd": 8.6,
      "wpgt": null,
      "pres": 1018.5,
      "tsun": null
    },
    {
      "date": "2024-01-02 00:00:00",
      "tavg": 13.3,
      "tmin": 8.3,
      "tmax": 18.3,
      "prcp": 0.0,
      "snow": null,
      "wdir": null,
      "wspd": 10.4,
      "wpgt": null,
      "pres": 1022.6,
      "tsun": null
    },
    {
      "date": "2024-01-03 00:00:00",
      "tavg": 13.6,
      "tmin": 11.1,
      "tmax": 16.1,
      "prcp": 5.1,
      "snow": null,
      "wdir": null,
      "wspd": 17.3,
      "wpgt": null,
      "pres": 1018.3,
      "tsun": null
    },
    {
      "date": "2024-01-04 00:00:00",
      "tavg": 14.1,
      "tmin": 11.1,
      "tmax": 18.3,
      "prcp": 0.0,
      "snow": null,
      "wdir": null,
      "wspd": 15.1,

In [30]:
pd.json_normalize(sample_lax)

                                                data       meta.generated
0  [{'date': '2024-01-01 00:00:00', 'tavg': 14.0,...  2025-10-28 12:21:54

In [31]:
pd.json_normalize(weather_daily_df['extracted_data']).loc[2, 'data'] #extract only data from the json data of first airport:LAX

[{'date': '2024-01-01 00:00:00',
  'tavg': 14.0,
  'tmin': 10.0,
  'tmax': 19.4,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1018.5,
  'tsun': None},
 {'date': '2024-01-02 00:00:00',
  'tavg': 13.3,
  'tmin': 8.3,
  'tmax': 18.3,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1022.6,
  'tsun': None},
 {'date': '2024-01-03 00:00:00',
  'tavg': 13.6,
  'tmin': 11.1,
  'tmax': 16.1,
  'prcp': 5.1,
  'snow': None,
  'wdir': None,
  'wspd': 17.3,
  'wpgt': None,
  'pres': 1018.3,
  'tsun': None},
 {'date': '2024-01-04 00:00:00',
  'tavg': 14.1,
  'tmin': 11.1,
  'tmax': 18.3,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 15.1,
  'wpgt': None,
  'pres': 1019.8,
  'tsun': None},
 {'date': '2024-01-05 00:00:00',
  'tavg': 13.1,
  'tmin': 7.8,
  'tmax': 18.3,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1020.7,
  'tsun': None},
 {'date': '2024-01-06 00:00:00',
  'tavg': 12.1,
  'tmin': 6.7,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 13.3,
  'wpgt': None,
  'pres': 1019.1,
  'tsun': None},
 {'date': '2024-01-07 00:00:00',
  'tavg': 13.1,
  'tmin': 9.4,
  'tmax': 15.0,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 25.6,
  'wpgt': None,
  'pres': 1014.4,
  'tsun': None},
 {'date': '2024-01-08 00:00:00',
  'tavg': 11.2,
  'tmin': 7.2,
  'tmax': 15.0,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1023.0,
  'tsun': None},
 {'date': '2024-01-09 00:00:00',
  'tavg': 10.9,
  'tmin': 5.6,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.3,
  'wpgt': None,
  'pres': 1022.0,
  'tsun': None},
 {'date': '2024-01-10 00:00:00',
  'tavg': 11.1,
  'tmin': 6.1,
  'tmax': 16.1,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1015.5,
  'tsun': None},
 {'date': '2024-01-11 00:00:00',
  'tavg': 13.0,
  'tmin': 10.6,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 18.4,
  'wpgt': None,
  'pres': 1016.1,
  'tsun': None},
 {'date': '2024-01-12 00:00:00',
  'tavg': 11.5,
  'tmin': 5.0,
  'tmax': 15.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1021.0,
  'tsun': None},
 {'date': '2024-01-13 00:00:00',
  'tavg': 11.2,
  'tmin': 6.7,
  'tmax': 15.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 7.2,
  'wpgt': None,
  'pres': 1018.6,
  'tsun': None},
 {'date': '2024-01-14 00:00:00',
  'tavg': 11.7,
  'tmin': 6.7,
  'tmax': 15.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1017.3,
  'tsun': None},
 {'date': '2024-01-15 00:00:00',
  'tavg': 12.2,
  'tmin': 7.8,
  'tmax': 16.1,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 7.6,
  'wpgt': None,
  'pres': 1017.8,
  'tsun': None},
 {'date': '2024-01-16 00:00:00',
  'tavg': 12.7,
  'tmin': 8.9,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.3,
  'wpgt': None,
  'pres': 1018.1,
  'tsun': None},
 {'date': '2024-01-17 00:00:00',
  'tavg': 13.4,
  'tmin': 12.8,
  'tmax': 15.0,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 6.5,
  'wpgt': None,
  'pres': 1017.3,
  'tsun': None},
 {'date': '2024-01-18 00:00:00',
  'tavg': 14.3,
  'tmin': 11.7,
  'tmax': 18.9,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1018.4,
  'tsun': None},
 {'date': '2024-01-19 00:00:00',
  'tavg': 14.2,
  'tmin': 10.6,
  'tmax': 19.4,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.0,
  'wpgt': None,
  'pres': 1016.2,
  'tsun': None},
 {'date': '2024-01-20 00:00:00',
  'tavg': 13.9,
  'tmin': 12.8,
  'tmax': 15.0,
  'prcp': 13.0,
  'snow': None,
  'wdir': None,
  'wspd': 13.0,
  'wpgt': None,
  'pres': 1012.7,
  'tsun': None},
 {'date': '2024-01-21 00:00:00',
  'tavg': 13.9,
  'tmin': 12.8,
  'tmax': 17.8,
  'prcp': 1.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1012.2,
  'tsun': None},
 {'date': '2024-01-22 00:00:00',
  'tavg': 14.1,
  'tmin': 12.8,
  'tmax': 15.0,
  'prcp': 29.2,
  'snow': None,
  'wdir': None,
  'wspd': 14.0,
  'wpgt': None,
  'pres': 1008.6,
  'tsun': None},
 {'date': '2024-01-23 00:00:00',
  'tavg': 13.7,
  'tmin': 10.6,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1012.7,
  'tsun': None},
 {'date': '2024-01-24 00:00:00',
  'tavg': 14.6,
  'tmin': 12.2,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1019.6,
  'tsun': None},
 {'date': '2024-01-25 00:00:00',
  'tavg': 14.6,
  'tmin': 11.7,
  'tmax': 16.1,
  'prcp': 1.3,
  'snow': None,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1020.2,
  'tsun': None},
 {'date': '2024-01-26 00:00:00',
  'tavg': 14.1,
  'tmin': 10.0,
  'tmax': 21.1,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 6.5,
  'wpgt': None,
  'pres': 1022.4,
  'tsun': None},
 {'date': '2024-01-27 00:00:00',
  'tavg': 16.6,
  'tmin': 11.7,
  'tmax': 24.4,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 7.2,
  'wpgt': None,
  'pres': 1021.6,
  'tsun': None},
 {'date': '2024-01-28 00:00:00',
  'tavg': 18.2,
  'tmin': 10.6,
  'tmax': 25.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 7.6,
  'wpgt': None,
  'pres': 1019.5,
  'tsun': None},
 {'date': '2024-01-29 00:00:00',
  'tavg': 18.6,
  'tmin': 12.2,
  'tmax': 25.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1018.8,
  'tsun': None},
 {'date': '2024-01-30 00:00:00',
  'tavg': 15.8,
  'tmin': 11.1,
  'tmax': 22.2,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1017.0,
  'tsun': None},
 {'date': '2024-01-31 00:00:00',
  'tavg': 14.4,
  'tmin': 11.1,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1014.5,
  'tsun': None},
 {'date': '2024-02-01 00:00:00',
  'tavg': 12.4,
  'tmin': 9.4,
  'tmax': 15.0,
  'prcp': 63.2,
  'snow': None,
  'wdir': None,
  'wspd': 18.4,
  'wpgt': None,
  'pres': 1008.3,
  'tsun': None},
 {'date': '2024-02-02 00:00:00',
  'tavg': 12.9,
  'tmin': 10.0,
  'tmax': 15.6,
  'prcp': 0.3,
  'snow': None,
  'wdir': None,
  'wspd': 22.7,
  'wpgt': None,
  'pres': 1012.8,
  'tsun': None},
 {'date': '2024-02-03 00:00:00',
  'tavg': 12.1,
  'tmin': 8.9,
  'tmax': 14.4,
  'prcp': 2.3,
  'snow': None,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1016.2,
  'tsun': None},
 {'date': '2024-02-04 00:00:00',
  'tavg': 12.2,
  'tmin': 10.0,
  'tmax': 14.4,
  'prcp': 44.7,
  'snow': None,
  'wdir': None,
  'wspd': 21.6,
  'wpgt': None,
  'pres': 1013.8,
  'tsun': None},
 {'date': '2024-02-05 00:00:00',
  'tavg': 13.2,
  'tmin': 11.7,
  'tmax': 13.9,
  'prcp': 65.3,
  'snow': None,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 1010.5,
  'tsun': None},
 {'date': '2024-02-06 00:00:00',
  'tavg': 11.8,
  'tmin': 8.9,
  'tmax': 12.2,
  'prcp': 27.4,
  'snow': None,
  'wdir': None,
  'wspd': 7.9,
  'wpgt': None,
  'pres': 1005.8,
  'tsun': None},
 {'date': '2024-02-07 00:00:00',
  'tavg': 10.4,
  'tmin': 7.2,
  'tmax': 15.0,
  'prcp': 4.6,
  'snow': None,
  'wdir': None,
  'wspd': 19.4,
  'wpgt': None,
  'pres': 1011.8,
  'tsun': None},
 {'date': '2024-02-08 00:00:00',
  'tavg': 11.4,
  'tmin': 7.8,
  'tmax': 14.4,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 18.7,
  'wpgt': None,
  'pres': 1015.6,
  'tsun': None},
 {'date': '2024-02-09 00:00:00',
  'tavg': 11.8,
  'tmin': 8.3,
  'tmax': 15.6,
  'prcp': 0.3,
  'snow': None,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1016.9,
  'tsun': None},
 {'date': '2024-02-10 00:00:00',
  'tavg': 12.9,
  'tmin': 10.0,
  'tmax': 19.4,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 13.0,
  'wpgt': None,
  'pres': 1016.8,
  'tsun': None},
 {'date': '2024-02-11 00:00:00',
  'tavg': 12.4,
  'tmin': 6.7,
  'tmax': 17.2,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1021.7,
  'tsun': None},
 {'date': '2024-02-12 00:00:00',
  'tavg': 12.4,
  'tmin': 7.2,
  'tmax': 18.3,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1019.0,
  'tsun': None},
 {'date': '2024-02-13 00:00:00',
  'tavg': 12.3,
  'tmin': 6.7,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.4,
  'wpgt': None,
  'pres': 1016.3,
  'tsun': None},
 {'date': '2024-02-14 00:00:00',
  'tavg': 13.2,
  'tmin': 10.0,
  'tmax': 16.1,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1020.2,
  'tsun': None},
 {'date': '2024-02-15 00:00:00',
  'tavg': 12.9,
  'tmin': 8.9,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1021.3,
  'tsun': None},
 {'date': '2024-02-16 00:00:00',
  'tavg': 14.2,
  'tmin': 12.2,
  'tmax': 17.2,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1019.5,
  'tsun': None},
 {'date': '2024-02-17 00:00:00',
  'tavg': 13.6,
  'tmin': 12.2,
  'tmax': 16.1,
  'prcp': 0.3,
  'snow': None,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1018.6,
  'tsun': None},
 {'date': '2024-02-18 00:00:00',
  'tavg': 14.3,
  'tmin': 12.8,
  'tmax': 17.2,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 7.6,
  'wpgt': None,
  'pres': 1017.7,
  'tsun': None},
 {'date': '2024-02-19 00:00:00',
  'tavg': 14.2,
  'tmin': 12.8,
  'tmax': 14.4,
  'prcp': 24.4,
  'snow': None,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1018.3,
  'tsun': None},
 {'date': '2024-02-20 00:00:00',
  'tavg': 13.4,
  'tmin': 12.2,
  'tmax': 15.0,
  'prcp': 14.2,
  'snow': None,
  'wdir': None,
  'wspd': 13.0,
  'wpgt': None,
  'pres': 1019.2,
  'tsun': None},
 {'date': '2024-02-21 00:00:00',
  'tavg': 14.1,
  'tmin': 11.7,
  'tmax': 16.7,
  'prcp': 6.4,
  'snow': None,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1019.6,
  'tsun': None},
 {'date': '2024-02-22 00:00:00',
  'tavg': 13.9,
  'tmin': 10.6,
  'tmax': 17.2,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1022.0,
  'tsun': None},
 {'date': '2024-02-23 00:00:00',
  'tavg': 15.7,
  'tmin': 11.1,
  'tmax': 24.4,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.3,
  'wpgt': None,
  'pres': 1017.6,
  'tsun': None},
 {'date': '2024-02-24 00:00:00',
  'tavg': 17.1,
  'tmin': 12.8,
  'tmax': 24.4,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1016.7,
  'tsun': None},
 {'date': '2024-02-25 00:00:00',
  'tavg': 14.9,
  'tmin': 12.8,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1017.3,
  'tsun': None},
 {'date': '2024-02-26 00:00:00',
  'tavg': 13.9,
  'tmin': 11.7,
  'tmax': 17.2,
  'prcp': 1.3,
  'snow': None,
  'wdir': None,
  'wspd': 7.9,
  'wpgt': None,
  'pres': 1016.3,
  'tsun': None},
 {'date': '2024-02-27 00:00:00',
  'tavg': 13.9,
  'tmin': 11.7,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.3,
  'wpgt': None,
  'pres': 1015.4,
  'tsun': None},
 {'date': '2024-02-28 00:00:00',
  'tavg': 14.1,
  'tmin': 10.0,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1016.9,
  'tsun': None},
 {'date': '2024-02-29 00:00:00',
  'tavg': 14.5,
  'tmin': 13.3,
  'tmax': 16.1,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1020.7,
  'tsun': None},
 {'date': '2024-03-01 00:00:00',
  'tavg': 13.8,
  'tmin': 12.2,
  'tmax': 16.7,
  'prcp': 0.3,
  'snow': None,
  'wdir': None,
  'wspd': 14.0,
  'wpgt': None,
  'pres': 1020.1,
  'tsun': None},
 {'date': '2024-03-02 00:00:00',
  'tavg': 14.3,
  'tmin': 11.1,
  'tmax': 15.6,
  'prcp': 5.8,
  'snow': None,
  'wdir': None,
  'wspd': 19.8,
  'wpgt': None,
  'pres': 1016.6,
  'tsun': None},
 {'date': '2024-03-03 00:00:00',
  'tavg': 12.7,
  'tmin': 9.4,
  'tmax': 16.1,
  'prcp': 1.8,
  'snow': None,
  'wdir': None,
  'wspd': 17.3,
  'wpgt': None,
  'pres': 1017.1,
  'tsun': None},
 {'date': '2024-03-04 00:00:00',
  'tavg': 12.8,
  'tmin': 7.8,
  'tmax': 17.2,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 8.6,
  'wpgt': None,
  'pres': 1018.5,
  'tsun': None},
 {'date': '2024-03-05 00:00:00',
  'tavg': 13.1,
  'tmin': 8.3,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 1017.3,
  'tsun': None},
 {'date': '2024-03-06 00:00:00',
  'tavg': 12.9,
  'tmin': 10.0,
  'tmax': 16.1,
  'prcp': 17.0,
  'snow': None,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 1012.6,
  'tsun': None},
 {'date': '2024-03-07 00:00:00',
  'tavg': 12.7,
  'tmin': 8.9,
  'tmax': 16.7,
  'prcp': 0.8,
  'snow': None,
  'wdir': None,
  'wspd': 13.0,
  'wpgt': None,
  'pres': 1012.5,
  'tsun': None},
 {'date': '2024-03-08 00:00:00',
  'tavg': 13.6,
  'tmin': 9.4,
  'tmax': 20.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1019.3,
  'tsun': None},
 {'date': '2024-03-09 00:00:00',
  'tavg': 14.1,
  'tmin': 8.9,
  'tmax': 18.9,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1019.5,
  'tsun': None},
 {'date': '2024-03-10 00:00:00',
  'tavg': 13.8,
  'tmin': 9.4,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 11.2,
  'wpgt': None,
  'pres': 1018.2,
  'tsun': None},
 {'date': '2024-03-11 00:00:00',
  'tavg': 13.6,
  'tmin': 9.4,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1018.2,
  'tsun': None},
 {'date': '2024-03-12 00:00:00',
  'tavg': 13.9,
  'tmin': 11.1,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1019.4,
  'tsun': None},
 {'date': '2024-03-13 00:00:00',
  'tavg': 15.3,
  'tmin': 12.2,
  'tmax': 18.9,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 15.8,
  'wpgt': None,
  'pres': 1015.1,
  'tsun': None},
 {'date': '2024-03-14 00:00:00',
  'tavg': 16.0,
  'tmin': 11.1,
  'tmax': 21.1,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 15.5,
  'wpgt': None,
  'pres': 1009.7,
  'tsun': None},
 {'date': '2024-03-15 00:00:00',
  'tavg': 16.7,
  'tmin': 12.8,
  'tmax': 20.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 11.9,
  'wpgt': None,
  'pres': 1009.6,
  'tsun': None},
 {'date': '2024-03-16 00:00:00',
  'tavg': 14.9,
  'tmin': 11.1,
  'tmax': 18.9,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1016.2,
  'tsun': None},
 {'date': '2024-03-17 00:00:00',
  'tavg': 14.1,
  'tmin': 10.0,
  'tmax': 18.9,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 12.2,
  'wpgt': None,
  'pres': 1017.8,
  'tsun': None},
 {'date': '2024-03-18 00:00:00',
  'tavg': 14.8,
  'tmin': 10.6,
  'tmax': 20.6,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1017.0,
  'tsun': None},
 {'date': '2024-03-19 00:00:00',
  'tavg': 16.1,
  'tmin': 12.2,
  'tmax': 20.0,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.1,
  'wpgt': None,
  'pres': 1016.7,
  'tsun': None},
 {'date': '2024-03-20 00:00:00',
  'tavg': 14.6,
  'tmin': 12.2,
  'tmax': 18.3,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.7,
  'wpgt': None,
  'pres': 1016.2,
  'tsun': None},
 {'date': '2024-03-21 00:00:00',
  'tavg': 15.0,
  'tmin': 13.3,
  'tmax': 18.3,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 9.4,
  'wpgt': None,
  'pres': 1018.5,
  'tsun': None},
 {'date': '2024-03-22 00:00:00',
  'tavg': 14.7,
  'tmin': 11.7,
  'tmax': 18.3,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 11.2,
  'wpgt': None,
  'pres': 1017.8,
  'tsun': None},
 {'date': '2024-03-23 00:00:00',
  'tavg': 14.8,
  'tmin': 11.7,
  'tmax': 16.7,
  'prcp': 4.6,
  'snow': None,
  'wdir': None,
  'wspd': 28.4,
  'wpgt': None,
  'pres': 1011.9,
  'tsun': None},
 {'date': '2024-03-24 00:00:00',
  'tavg': 13.2,
  'tmin': 10.0,
  'tmax': 16.7,
  'prcp': 1.8,
  'snow': None,
  'wdir': None,
  'wspd': 20.5,
  'wpgt': None,
  'pres': 1009.1,
  'tsun': None},
 {'date': '2024-03-25 00:00:00',
  'tavg': 13.4,
  'tmin': 8.9,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 15.5,
  'wpgt': None,
  'pres': 1012.7,
  'tsun': None},
 {'date': '2024-03-26 00:00:00',
  'tavg': 13.4,
  'tmin': 10.0,
  'tmax': 17.2,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 12.6,
  'wpgt': None,
  'pres': 1017.1,
  'tsun': None},
 {'date': '2024-03-27 00:00:00',
  'tavg': 13.7,
  'tmin': 10.0,
  'tmax': 17.8,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 10.8,
  'wpgt': None,
  'pres': 1020.8,
  'tsun': None},
 {'date': '2024-03-28 00:00:00',
  'tavg': 13.6,
  'tmin': 11.1,
  'tmax': 16.7,
  'prcp': 0.0,
  'snow': None,
  'wdir': None,
  'wspd': 14.8,
  'wpgt': None,
  'pres': 1017.9,
  'tsun': None},
 {'date': '2024-03-29 00:00:00',
  'tavg': 13.3,
  'tmin': 10.6,
  'tmax': 16.7,
  'prcp': 3.6,
  'snow': None,
  'wdir': None,
  'wspd': 15.1,
  'wpgt': None,
  'pres': 1013.2,
  'tsun': None},
 {'date': '2024-03-30 00:00:00',
  'tavg': 12.2,
  'tmin': 10.0,
  'tmax': 13.3,
  'prcp': 47.5,
  'snow': None,
  'wdir': None,
  'wspd': 16.6,
  'wpgt': None,
  'pres': 1006.9,
  'tsun': None},
 {'date': '2024-03-31 00:00:00',
  'tavg': 12.0,
  'tmin': 9.4,
  'tmax': 16.7,
  'prcp': 0.3,
  'snow': None,
  'wdir': None,
  'wspd': 18.0,
  'wpgt': None,
  'pres': 1008.4,
  'tsun': None}]

In [32]:
# using pd.json_normalize() twice to get to the weather_stats of one airport under 'data'

df_LAX = pd.json_normalize(pd.json_normalize(weather_daily_df['extracted_data']).loc[2, 'data'])
df_LAX

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2024-01-01 00:00:00,14.0,10.0,19.4,0.0,None,None,8.6,None,1018.5,None
1,2024-01-02 00:00:00,13.3,8.3,18.3,0.0,None,None,10.4,None,1022.6,None
2,2024-01-03 00:00:00,13.6,11.1,16.1,5.1,None,None,17.3,None,1018.3,None
3,2024-01-04 00:00:00,14.1,11.1,18.3,0.0,None,None,15.1,None,1019.8,None
4,2024-01-05 00:00:00,13.1,7.8,18.3,0.0,None,None,9.4,None,1020.7,None
...,...,...,...,...,...,...,...,...,...,...,...
86,2024-03-27 00:00:00,13.7,10.0,17.8,0.0,None,None,10.8,None,1020.8,None
87,2024-03-28 00:00:00,13.6,11.1,16.7,0.0,None,None,14.8,None,1017.9,None
88,2024-03-29 00:00:00,13.3,10.6,16.7,3.6,None,None,15.1,None,1013.2,None
89,2024-03-30 00:00:00,12.2,10.0,13.3,47.5,None,None,16.6,None,1006.9,None
90,2024-03-31 00:00:00,12.0,9.4,16.7,0.3,None,None,18.0,None,1008.4,None