In [1]:
# we will need the credentials we saved in the .env file
from dotenv import dotenv_values

# We also will need SQLAlchemy and its functions
from sqlalchemy import create_engine, types
from sqlalchemy.dialects.postgresql import JSON as postgres_json

import pandas as pd

# requests library will make the API calls. 
# the json package will parse the JSON string and convert it to Python data structures
import requests
import json

# with 'datetime' we want to catch the timestamp of the API call. For the actuality reference. 
# and 'time' for slowing down a .bit
from datetime import datetime
import time

In [2]:
airport_staids = {
    'JFK': '74486',   # John F. Kennedy International
    'MIA': '72202',   # Miami International
    'LAX': '72295',   # Los Angeles Airport
           }

In [3]:
period_start = "2024-01-01"
period_end = "2024-03-31"

In [4]:
# Let's load values from the .env file
from dotenv import dotenv_values

config = dotenv_values()

pg_api_key = config['X-RapidAPI-Key']  # align the key label with your .env file
pg_user = config['POSTGRES_USER']
pg_pass = config['POSTGRES_PASS']
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']

In [5]:
url = "https://meteostat.p.rapidapi.com/stations/monthly"

headers = {
    "X-RapidAPI-Key": pg_api_key,
    "X-RapidAPI-Host": "meteostat.p.rapidapi.com"
}

# Just to inspect the query for one airport
for airport in airport_staids:
    querystring = {
        "station": airport_staids[airport],
        "start": period_start,
        "end": period_end,
        "model": "true"  # use model-based data where necessary
    }
    print(airport, "\n", querystring)

JFK
 {'station': '74486', 'start': '2024-01-01', 'end': '2024-03-31', 'model': 'true'}
MIA
 {'station': '72202', 'start': '2024-01-01', 'end': '2024-03-31', 'model': 'true'}
LAX
 {'station': '72295', 'start': '2024-01-01', 'end': '2024-03-31', 'model': 'true'}

In [6]:
#  let's catch each response in a dictionary. create an empty dictionary with the following keys:

weather_dict = {'extracted_at':[], 
                'airport_code':[], 
                'station_id':[], 
                'extracted_data':[]
               }


# for-loop for the querystrings
for airport in airport_staids:
    querystring = {
        "station":airport_staids[airport]
        ,"start":period_start
        ,"end":period_end
        ,"model":"true"
    }
    
    # making one call with the current querystring
    response = requests.get(url, headers=headers, params=querystring)

    # Add a slight delay to respect API limits
    time.sleep(1)
                
    # appending data to the dictionary:
    weather_dict['extracted_at'].append(pd.Timestamp.now())       # timestamp, 
    weather_dict['airport_code'].append(airport)       # airport code    
    weather_dict['station_id'].append(airport_staids[airport])         # weater Station ID
    weather_dict['extracted_data'].append(json.loads(response.text))   # JSON string

In [7]:
weather_monthly_df= pd.DataFrame(weather_dict)

In [8]:
weather_monthly_df

,extracted_at,airport_code,station_id,extracted_data
0,2025-10-28 22:18:41.448163,JFK,74486,"{'meta': {'generated': '2025-10-28 20:40:27'},..."
1,2025-10-28 22:18:42.681020,MIA,72202,"{'meta': {'generated': '2025-10-28 20:40:28'},..."
2,2025-10-28 22:18:43.922574,LAX,72295,"{'meta': {'generated': '2025-10-28 20:30:44'},..."

In [9]:
# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# creating the engine
engine = create_engine(url, echo=False)

In [10]:
engine.url # checking the url (pass is hidden)

postgresql://jingwang:***@data-analytics-course-2.c8g8r1deus2v.eu-central-1.rds.amazonaws.com:5432/nf_180825

In [11]:
# defining data types for the DB
dtype_dict = {
    'extracted_at':types.DateTime,
    'airport_code': types.String,
    'station_id': types.Integer,
    'extracted_data':postgres_json
             }

In [12]:
weather_monthly_df.dtypes

extracted_at      datetime64[ns]
airport_code              object
station_id                object
extracted_data            object
dtype: object

In [13]:
weather_monthly_df['airport_code'] = weather_monthly_df['airport_code'].astype('string')

In [14]:
weather_monthly_df.dtypes

extracted_at      datetime64[ns]
airport_code      string[python]
station_id                object
extracted_data            object
dtype: object

In [15]:
weather_monthly_df['station_id'] = weather_monthly_df['station_id'].astype('int')

In [16]:
weather_monthly_df.dtypes

extracted_at      datetime64[ns]
airport_code      string[python]
station_id                 int64
extracted_data            object
dtype: object

In [31]:
# writing dataframe to DB
weather_monthly_df.to_sql(name = 'weather_monthly_raw', 
                       con = engine, 
                       schema = pg_schema, # pandas is allowing to specify, in which schema the table shall be created
                       if_exists='replace', 
                       dtype=dtype_dict,
                       index=False
                      )

3

In [32]:
weather_monthly_df['extracted_data']

0    {'meta': {'generated': '2025-10-28 20:40:27'},...
1    {'meta': {'generated': '2025-10-28 20:40:28'},...
2    {'meta': {'generated': '2025-10-28 20:30:44'},...
Name: extracted_data, dtype: object

In [19]:
sample_jfk= weather_monthly_df['extracted_data'][0] #all data from the first airport:JFK, we can see that we have meta and data
print(json.dumps(sample_jfk, indent=2)[:1000])

{
  "meta": {
    "generated": "2025-10-28 20:40:27"
  },
  "data": [
    {
      "date": "2024-01-01 00:00:00",
      "tavg": 2.3,
      "tmin": -0.7,
      "tmax": 5.2,
      "prcp": 148.0,
      "wspd": null,
      "pres": 1017.3,
      "tsun": null
    },
    {
      "date": "2024-02-01 00:00:00",
      "tavg": 3.0,
      "tmin": -0.3,
      "tmax": 6.7,
      "prcp": 43.0,
      "wspd": null,
      "pres": 1016.0,
      "tsun": null
    },
    {
      "date": "2024-03-01 00:00:00",
      "tavg": 8.2,
      "tmin": 4.1,
      "tmax": 12.5,
      "prcp": 251.0,
      "wspd": null,
      "pres": 1015.4,
      "tsun": null
    }
  ]
}

In [20]:
pd.json_normalize(sample_jfk)

                                                data       meta.generated
0  [{'date': '2024-01-01 00:00:00', 'tavg': 2.3, ...  2025-10-28 20:40:27

In [21]:
pd.json_normalize(weather_monthly_df['extracted_data']).loc[0, 'data'] #extract only data from the json data of first airport:JFK

[{'date': '2024-01-01 00:00:00',
  'tavg': 2.3,
  'tmin': -0.7,
  'tmax': 5.2,
  'prcp': 148.0,
  'wspd': None,
  'pres': 1017.3,
  'tsun': None},
 {'date': '2024-02-01 00:00:00',
  'tavg': 3.0,
  'tmin': -0.3,
  'tmax': 6.7,
  'prcp': 43.0,
  'wspd': None,
  'pres': 1016.0,
  'tsun': None},
 {'date': '2024-03-01 00:00:00',
  'tavg': 8.2,
  'tmin': 4.1,
  'tmax': 12.5,
  'prcp': 251.0,
  'wspd': None,
  'pres': 1015.4,
  'tsun': None}]

In [22]:
# using pd.json_normalize() twice to get to the weather_stats of one airport under 'data'

df_JFK = pd.json_normalize(pd.json_normalize(weather_monthly_df['extracted_data']).loc[0, 'data'])
df_JFK

                  date  tavg  tmin  tmax   prcp  wspd    pres  tsun
0  2024-01-01 00:00:00   2.3  -0.7   5.2  148.0  None  1017.3  None
1  2024-02-01 00:00:00   3.0  -0.3   6.7   43.0  None  1016.0  None
2  2024-03-01 00:00:00   8.2   4.1  12.5  251.0  None  1015.4  None

In [23]:
sample_mia= weather_monthly_df['extracted_data'][1] #all data from the first airport:JFK, we can see that we have meta and data
print(json.dumps(sample_mia, indent=2)[:1000])

{
  "meta": {
    "generated": "2025-10-28 20:40:28"
  },
  "data": [
    {
      "date": "2024-01-01 00:00:00",
      "tavg": 21.6,
      "tmin": 17.8,
      "tmax": 25.3,
      "prcp": 23.0,
      "wspd": null,
      "pres": 1018.9,
      "tsun": null
    },
    {
      "date": "2024-02-01 00:00:00",
      "tavg": 20.5,
      "tmin": 16.1,
      "tmax": 25.0,
      "prcp": 77.0,
      "wspd": null,
      "pres": 1016.6,
      "tsun": null
    },
    {
      "date": "2024-03-01 00:00:00",
      "tavg": 24.3,
      "tmin": 20.6,
      "tmax": 28.0,
      "prcp": 121.0,
      "wspd": null,
      "pres": 1016.0,
      "tsun": null
    }
  ]
}

In [24]:
pd.json_normalize(sample_mia)

                                                data       meta.generated
0  [{'date': '2024-01-01 00:00:00', 'tavg': 21.6,...  2025-10-28 20:40:28

In [25]:
pd.json_normalize(weather_monthly_df['extracted_data']).loc[1, 'data'] #extract only data from the json data of first airport:MIA

[{'date': '2024-01-01 00:00:00',
  'tavg': 21.6,
  'tmin': 17.8,
  'tmax': 25.3,
  'prcp': 23.0,
  'wspd': None,
  'pres': 1018.9,
  'tsun': None},
 {'date': '2024-02-01 00:00:00',
  'tavg': 20.5,
  'tmin': 16.1,
  'tmax': 25.0,
  'prcp': 77.0,
  'wspd': None,
  'pres': 1016.6,
  'tsun': None},
 {'date': '2024-03-01 00:00:00',
  'tavg': 24.3,
  'tmin': 20.6,
  'tmax': 28.0,
  'prcp': 121.0,
  'wspd': None,
  'pres': 1016.0,
  'tsun': None}]

In [26]:
# using pd.json_normalize() twice to get to the weather_stats of one airport under 'data'

df_MIA = pd.json_normalize(pd.json_normalize(weather_monthly_df['extracted_data']).loc[1, 'data'])
df_MIA

                  date  tavg  tmin  tmax   prcp  wspd    pres  tsun
0  2024-01-01 00:00:00  21.6  17.8  25.3   23.0  None  1018.9  None
1  2024-02-01 00:00:00  20.5  16.1  25.0   77.0  None  1016.6  None
2  2024-03-01 00:00:00  24.3  20.6  28.0  121.0  None  1016.0  None

In [27]:
sample_lax= weather_monthly_df['extracted_data'][2] #all data from the first airport:JFK, we can see that we have meta and data
print(json.dumps(sample_lax, indent=2)[:1000])

{
  "meta": {
    "generated": "2025-10-28 20:30:44"
  },
  "data": [
    {
      "date": "2024-01-01 00:00:00",
      "tavg": 13.9,
      "tmin": 9.8,
      "tmax": 17.9,
      "prcp": 50.0,
      "wspd": null,
      "pres": 1017.9,
      "tsun": null
    },
    {
      "date": "2024-02-01 00:00:00",
      "tavg": 13.5,
      "tmin": 10.3,
      "tmax": 16.7,
      "prcp": 255.0,
      "wspd": null,
      "pres": 1016.6,
      "tsun": null
    },
    {
      "date": "2024-03-01 00:00:00",
      "tavg": 14.1,
      "tmin": 10.5,
      "tmax": 17.7,
      "prcp": 84.0,
      "wspd": null,
      "pres": 1015.7,
      "tsun": null
    }
  ]
}

In [28]:
pd.json_normalize(sample_lax)

                                                data       meta.generated
0  [{'date': '2024-01-01 00:00:00', 'tavg': 13.9,...  2025-10-28 20:30:44

In [29]:
pd.json_normalize(weather_monthly_df['extracted_data']).loc[2, 'data'] #extract only data from the json data of first airport:LAX

[{'date': '2024-01-01 00:00:00',
  'tavg': 13.9,
  'tmin': 9.8,
  'tmax': 17.9,
  'prcp': 50.0,
  'wspd': None,
  'pres': 1017.9,
  'tsun': None},
 {'date': '2024-02-01 00:00:00',
  'tavg': 13.5,
  'tmin': 10.3,
  'tmax': 16.7,
  'prcp': 255.0,
  'wspd': None,
  'pres': 1016.6,
  'tsun': None},
 {'date': '2024-03-01 00:00:00',
  'tavg': 14.1,
  'tmin': 10.5,
  'tmax': 17.7,
  'prcp': 84.0,
  'wspd': None,
  'pres': 1015.7,
  'tsun': None}]

In [30]:
# using pd.json_normalize() twice to get to the weather_stats of one airport under 'data'

df_LAX = pd.json_normalize(pd.json_normalize(weather_monthly_df['extracted_data']).loc[2, 'data'])
df_LAX

                  date  tavg  tmin  tmax   prcp  wspd    pres  tsun
0  2024-01-01 00:00:00  13.9   9.8  17.9   50.0  None  1017.9  None
1  2024-02-01 00:00:00  13.5  10.3  16.7  255.0  None  1016.6  None
2  2024-03-01 00:00:00  14.1  10.5  17.7   84.0  None  1015.7  None